package resources

import "github.com/dvmrry/zscalerctl/internal/redact"

func catalogZIA() ResourceCatalog {
	return ResourceCatalog{
		{
			Product:    ProductZIA,
			Name:       "locations",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				{
					Name:           "id",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "name",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "ipAddresses",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:                   "description",
					Classification:         ClassFreeText,
					AllowedModes:           []redact.Mode{redact.ModeStandard},
					StandardFreeTextReason: standardFreeTextReason("ZIA location description"),
				},
				{
					Name:           "preSharedKey",
					Classification: ClassSecret,
				},
				{
					Name:           "vpnCredentials",
					Classification: ClassSecret,
				},
			},
		},
		{
			Product:    ProductZIA,
			Name:       "location-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				{
					Name:           "id",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "name",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "deleted",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "groupType",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:                   "comments",
					Classification:         ClassFreeText,
					AllowedModes:           []redact.Mode{redact.ModeStandard},
					StandardFreeTextReason: standardFreeTextReason("ZIA location group comments"),
				},
				{
					Name:           "lastModTime",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "predefined",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
			},
		},
		{
			Product:    ProductZIA,
			Name:       "rule-labels",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				{
					Name:           "id",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "name",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:                   "description",
					Classification:         ClassFreeText,
					AllowedModes:           []redact.Mode{redact.ModeStandard},
					StandardFreeTextReason: standardFreeTextReason("ZIA rule label description"),
				},
				{
					Name:           "lastModifiedTime",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "referencedRuleCount",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
			},
		},
		{
			Product:    ProductZIA,
			Name:       "auth-settings",
			Shape:      ShapeSingleton,
			Operations: SingletonOperations(),
			Fields: []FieldSpec{
				operationalField("orgAuthType", standardShareModes()),
				operationalField("oneTimeAuth", standardShareModes()),
				operationalField("samlEnabled", standardShareModes()),
				operationalField("kerberosEnabled", standardShareModes()),
				secretField("kerberosPwd"),
				operationalField("authFrequency", standardShareModes()),
				operationalField("authCustomFrequency", standardShareModes()),
				secretField("passwordStrength"),
				secretField("passwordExpiry"),
				operationalField("lastSyncStartTime", standardShareModes()),
				operationalField("lastSyncEndTime", standardShareModes()),
				operationalField("mobileAdminSamlIdpEnabled", standardShareModes()),
				operationalField("autoProvision", standardShareModes()),
				operationalField("directorySyncMigrateToScimEnabled", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "static-ips",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				{
					Name:           "id",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "ipAddress",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:           "routableIP",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "geoOverride",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "latitude",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:           "longitude",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:                   "comment",
					Classification:         ClassFreeText,
					AllowedModes:           []redact.Mode{redact.ModeStandard},
					StandardFreeTextReason: standardFreeTextReason("ZIA static IP comment"),
				},
				{
					Name:           "lastModificationTime",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
			},
		},
		{
			Product:    ProductZIA,
			Name:       "gre-tunnels",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				{
					Name:           "id",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "sourceIp",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:           "internalIpRange",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:           "lastModificationTime",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "withinCountry",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:                   "comment",
					Classification:         ClassFreeText,
					AllowedModes:           []redact.Mode{redact.ModeStandard},
					StandardFreeTextReason: standardFreeTextReason("ZIA GRE tunnel comment"),
				},
				{
					Name:           "ipUnnumbered",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "subcloud",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
			},
		},
		{
			Product:    ProductZIA,
			Name:       "sublocations",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				{
					Name:           "id",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "parentId",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "name",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "ipAddresses",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:           "ports",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:                   "description",
					Classification:         ClassFreeText,
					AllowedModes:           []redact.Mode{redact.ModeStandard},
					StandardFreeTextReason: standardFreeTextReason("ZIA sublocation description"),
				},
				{
					Name:           "profile",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "country",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:           "state",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:           "tz",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "authRequired",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "sslScanEnabled",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "ofwEnabled",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "ipsControl",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "vpnCredentials",
					Classification: ClassSecret,
				},
			},
		},
		{
			Product:    ProductZIA,
			Name:       "ssl-inspection-rules",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				{
					Name:           "id",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "name",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:                   "description",
					Classification:         ClassFreeText,
					AllowedModes:           []redact.Mode{redact.ModeStandard},
					StandardFreeTextReason: standardFreeTextReason("ZIA SSL inspection rule description"),
				},
				{
					Name:           "action",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
					Fields: []FieldSpec{
						{
							Name:           "type",
							Classification: ClassOperational,
							AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
						},
					},
				},
				{
					Name:           "state",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "order",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "rank",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "urlCategories",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "platforms",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "cloudApplications",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "lastModifiedTime",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "defaultRule",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "predefined",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
			},
		},
		{
			Product:    ProductZIA,
			Name:       "url-categories",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				{
					Name:           "id",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "configuredName",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:                   "description",
					Classification:         ClassFreeText,
					AllowedModes:           []redact.Mode{redact.ModeStandard},
					StandardFreeTextReason: standardFreeTextReason("ZIA URL category description"),
				},
				{
					Name:           "type",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "customCategory",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "editable",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "customUrlsCount",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "urlsRetainingParentCategoryCount",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "customIpRangesCount",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "ipRangesRetainingParentCategoryCount",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
				},
				{
					Name:           "categoryGroup",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "superCategory",
					Classification: ClassTenantConfig,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "urlType",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare},
				},
				{
					Name:           "urlKeywordCounts",
					Classification: ClassOperational,
					AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
					Fields: []FieldSpec{
						{
							Name:           "totalUrlCount",
							Classification: ClassOperational,
							AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
						},
						{
							Name:           "retainParentUrlCount",
							Classification: ClassOperational,
							AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
						},
						{
							Name:           "totalKeywordCount",
							Classification: ClassOperational,
							AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
						},
						{
							Name:           "retainParentKeywordCount",
							Classification: ClassOperational,
							AllowedModes:   []redact.Mode{redact.ModeStandard, redact.ModeShare, redact.ModeParanoid},
						},
					},
				},
				{
					Name:           "keywords",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:           "keywordsRetainingParentCategory",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:           "urls",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:           "dbCategorizedUrls",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:           "ipRanges",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:           "ipRangesRetainingParentCategory",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:           "regexPatterns",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
				{
					Name:           "regexPatternsRetainingParentCategory",
					Classification: ClassSensitiveIdentifier,
					AllowedModes:   []redact.Mode{redact.ModeStandard},
				},
			},
		},
		{
			Product:    ProductZIA,
			Name:       "url-filtering-rules",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA URL filtering rule description"),
				operationalField("state", allModes()),
				operationalField("order", allModes()),
				operationalField("rank", allModes()),
				tenantConfigField("action", standardShareModes()),
				tenantConfigField("protocols", standardShareModes()),
				tenantConfigField("requestMethods", standardShareModes()),
				tenantConfigField("urlCategories", standardShareModes()),
				tenantConfigField("urlCategories2", standardShareModes()),
				tenantConfigField("userRiskScoreLevels", standardShareModes()),
				tenantConfigField("userAgentTypes", standardShareModes()),
				operationalField("sourceCountries", standardShareModes()),
				operationalField("lastModifiedTime", standardShareModes()),
				operationalField("enforceTimeValidity", allModes()),
				operationalField("validityStartTime", standardShareModes()),
				operationalField("validityEndTime", standardShareModes()),
				operationalField("validityTimeZoneId", standardShareModes()),
				operationalField("blockOverride", allModes()),
				operationalField("timeQuota", standardShareModes()),
				operationalField("sizeQuota", standardShareModes()),
				operationalField("ciparule", allModes()),
				sensitiveIdentifierField("endUserNotificationUrl"),
				sensitiveIdentifierField("cbiProfileId"),
				idNameExtensionsField("labels", standardShareModes()),
				idNameExtensionsField("timeWindows", standardShareModes()),
				idNameExtensionsField("locations", standardOnlyMode()),
				idNameExtensionsField("locationGroups", standardOnlyMode()),
				idNameExtensionsField("sourceIpGroups", standardOnlyMode()),
				idNameField("workloadGroups", standardOnlyMode()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "firewall-filtering-rules",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA firewall filtering rule description"),
				operationalField("state", allModes()),
				operationalField("order", allModes()),
				operationalField("rank", allModes()),
				tenantConfigField("action", standardShareModes()),
				operationalField("accessControl", standardShareModes()),
				operationalField("enableFullLogging", allModes()),
				operationalField("defaultRule", allModes()),
				operationalField("predefined", allModes()),
				operationalField("lastModifiedTime", standardShareModes()),
				operationalField("sourceCountries", standardShareModes()),
				operationalField("destCountries", standardShareModes()),
				operationalField("excludeSrcCountries", allModes()),
				tenantConfigField("nwApplications", standardShareModes()),
				sensitiveIdentifierField("srcIps"),
				sensitiveIdentifierField("destAddresses"),
				sensitiveIdentifierField("destIpCategories"),
				tenantConfigField("deviceTrustLevels", standardShareModes()),
				idNameExtensionsField("labels", standardShareModes()),
				idNameExtensionsField("timeWindows", standardShareModes()),
				idNameExtensionsField("locations", standardOnlyMode()),
				idNameExtensionsField("locationGroups", standardOnlyMode()),
				idNameExtensionsField("srcIpGroups", standardOnlyMode()),
				idNameExtensionsField("destIpGroups", standardOnlyMode()),
				idNameExtensionsField("nwServices", standardOnlyMode()),
				idNameExtensionsField("nwServiceGroups", standardOnlyMode()),
				idNameExtensionsField("nwApplicationGroups", standardOnlyMode()),
				idNameExtensionsField("appServices", standardOnlyMode()),
				idNameExtensionsField("appServiceGroups", standardOnlyMode()),
				idNameField("workloadGroups", standardOnlyMode()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "ips-policies",
			Operations: ReadOperations(),
			Fields: fieldList(
				operationalFields("id", "order", "rank", "lastModifiedTime"),
				[]FieldSpec{
					tenantConfigField("name", standardShareModes()),
					freeTextField("description", "ZIA IPS policy description"),
					tenantConfigField("accessControl", standardShareModes()),
					tenantConfigField("enableFullLogging", standardShareModes()),
					tenantConfigField("action", standardShareModes()),
					tenantConfigField("state", standardShareModes()),
					tenantConfigField("defaultRule", standardShareModes()),
					tenantConfigField("capturePCAP", standardShareModes()),
					tenantConfigField("predefined", standardShareModes()),
					tenantConfigField("isEunEnabled", standardShareModes()),
					tenantConfigField("eunTemplateId", standardShareModes()),
					operationalField("sourceCountries", standardShareModes()),
					operationalField("destCountries", standardShareModes()),
					sensitiveIdentifierField("srcIps"),
					sensitiveIdentifierField("destAddresses"),
					sensitiveIdentifierField("destIpCategories"),
					sensitiveIdentifierField("resCategories"),
					secretField("lastModifiedBy"),
					idNameExtensionsField("labels", standardShareModes()),
					idNameExtensionsField("timeWindows", standardShareModes()),
					idNameExtensionsField("locations", standardOnlyMode()),
					idNameExtensionsField("locationGroups", standardOnlyMode()),
					idNameExtensionsField("departments", standardOnlyMode()),
					idNameExtensionsField("groups", standardOnlyMode()),
					idNameExtensionsField("users", standardOnlyMode()),
					idNameExtensionsField("destIpGroups", standardOnlyMode()),
					idNameExtensionsField("destIpv6Groups", standardOnlyMode()),
					idNameExtensionsField("nwServices", standardOnlyMode()),
					idNameExtensionsField("nwServiceGroups", standardOnlyMode()),
					idNameExtensionsField("srcIpGroups", standardOnlyMode()),
					idNameExtensionsField("srcIpv6Groups", standardOnlyMode()),
					idNameExtensionsField("deviceGroups", standardOnlyMode()),
					idNameExtensionsField("devices", standardOnlyMode()),
					idNameExtensionsField("threatCategories", standardOnlyMode()),
					idNameExternalIDField("zpaAppSegments", standardOnlyMode()),
				},
			),
		},
		{
			Product:    ProductZIA,
			Name:       "forwarding-rules",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA forwarding rule description"),
				operationalField("type", allModes()),
				operationalField("state", allModes()),
				operationalField("order", allModes()),
				operationalField("rank", allModes()),
				tenantConfigField("forwardMethod", standardShareModes()),
				operationalField("lastModifiedTime", standardShareModes()),
				operationalField("zpaBrokerRule", allModes()),
				operationalField("destCountries", standardShareModes()),
				sensitiveIdentifierField("srcIps"),
				sensitiveIdentifierField("destAddresses"),
				sensitiveIdentifierField("destIpCategories"),
				sensitiveIdentifierField("resCategories"),
				idNameExtensionsField("labels", standardShareModes()),
				idNameExtensionsField("locations", standardOnlyMode()),
				idNameExtensionsField("locationGroups", standardOnlyMode()),
				idNameExtensionsField("ecGroups", standardOnlyMode()),
				idNameExtensionsField("srcIpGroups", standardOnlyMode()),
				idNameExtensionsField("srcIpv6Groups", standardOnlyMode()),
				idNameExtensionsField("destIpGroups", standardOnlyMode()),
				idNameExtensionsField("destIpv6Groups", standardOnlyMode()),
				idNameExtensionsField("nwServices", standardOnlyMode()),
				idNameExtensionsField("nwServiceGroups", standardOnlyMode()),
				idNameExtensionsField("nwApplicationGroups", standardOnlyMode()),
				idNameExtensionsField("appServiceGroups", standardOnlyMode()),
				idNameField("proxyGateway", standardOnlyMode()),
				idNameField("dedicatedIPGateway", standardOnlyMode()),
				idNameField("zpaGateway", standardOnlyMode()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "ip-source-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA IP source group description"),
				sensitiveIdentifierField("ipAddresses"),
				operationalField("isNonEditable", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "ip-destination-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA IP destination group description"),
				operationalField("type", allModes()),
				sensitiveIdentifierField("addresses"),
				sensitiveIdentifierField("ipCategories"),
				operationalField("countries", standardShareModes()),
				operationalField("isNonEditable", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "network-services",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA network service description"),
				tenantConfigField("tag", standardShareModes()),
				operationalField("type", allModes()),
				tenantConfigField("protocol", standardShareModes()),
				operationalField("isNameL10nTag", allModes()),
				networkPortsField("srcTcpPorts", standardShareModes()),
				networkPortsField("destTcpPorts", standardShareModes()),
				networkPortsField("srcUdpPorts", standardShareModes()),
				networkPortsField("destUdpPorts", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "network-service-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA network service group description"),
				idNameField("services", standardOnlyMode()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "network-applications",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("parentCategory", standardShareModes()),
				freeTextField("description", "ZIA network application description"),
				operationalField("deprecated", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "application-services",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("nameL10nTag", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "application-service-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("nameL10nTag", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "network-application-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA network application group description"),
				tenantConfigField("networkApplications", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "time-windows",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				tenantConfigField("startTime", standardShareModes()),
				tenantConfigField("endTime", standardShareModes()),
				tenantConfigField("dayOfWeek", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "proxies",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("type", allModes()),
				sensitiveIdentifierField("address"),
				operationalField("port", standardShareModes()),
				freeTextField("description", "ZIA proxy description"),
				tenantConfigField("insertXauHeader", standardShareModes()),
				tenantConfigField("base64EncodeXauHeader", standardShareModes()),
				idNameExternalIDField("cert", standardShareModes()),
				operationalField("lastModifiedTime", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "proxy-gateways",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA proxy gateway description"),
				operationalField("failClosed", allModes()),
				operationalField("type", allModes()),
				idNameExternalIDField("primaryProxy", standardShareModes()),
				idNameExternalIDField("secondaryProxy", standardShareModes()),
				operationalField("lastModifiedTime", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "dedicated-ip-gateways",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA dedicated IP gateway description"),
				idNameExtensionsField("primaryDataCenter", standardShareModes()),
				idNameExtensionsField("secondaryDataCenter", standardShareModes()),
				operationalField("createTime", standardShareModes()),
				operationalField("lastModifiedTime", standardShareModes()),
				operationalField("default", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "time-intervals",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				tenantConfigField("startTime", standardShareModes()),
				tenantConfigField("endTime", standardShareModes()),
				tenantConfigField("daysOfWeek", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "bandwidth-classes",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				operationalField("isNameL10nTag", allModes()),
				tenantConfigField("name", standardShareModes()),
				tenantConfigField("getfileSize", standardShareModes()),
				tenantConfigField("fileSize", standardShareModes()),
				operationalField("type", allModes()),
				tenantConfigField("webApplications", standardShareModes()),
				sensitiveIdentifierField("urls"),
				tenantConfigField("applicationServiceGroups", standardShareModes()),
				tenantConfigField("networkApplications", standardShareModes()),
				tenantConfigField("networkServices", standardShareModes()),
				tenantConfigField("urlCategories", standardShareModes()),
				tenantConfigField("applications", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "bandwidth-control-rules",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA bandwidth control rule description"),
				operationalField("order", allModes()),
				operationalField("state", allModes()),
				operationalField("rank", allModes()),
				tenantConfigField("maxBandwidth", standardShareModes()),
				tenantConfigField("minBandwidth", standardShareModes()),
				operationalField("lastModifiedTime", standardShareModes()),
				operationalField("accessControl", standardShareModes()),
				operationalField("defaultRule", allModes()),
				tenantConfigField("protocols", standardShareModes()),
				tenantConfigField("deviceTrustLevels", standardShareModes()),
				idNameExtensionsField("bandwidthClasses", standardShareModes()),
				idNameExtensionsField("labels", standardShareModes()),
				idNameExtensionsField("timeWindows", standardShareModes()),
				idNameExtensionsField("locations", standardOnlyMode()),
				idNameExtensionsField("locationGroups", standardOnlyMode()),
				idNameExtensionsField("devices", standardOnlyMode()),
				idNameExtensionsField("deviceGroups", standardOnlyMode()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "dns-gateways",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("dnsGatewayType", allModes()),
				sensitiveIdentifierField("primaryIpOrFqdn"),
				tenantConfigField("primaryPorts", standardShareModes()),
				sensitiveIdentifierField("secondaryIpOrFqdn"),
				tenantConfigField("secondaryPorts", standardShareModes()),
				tenantConfigField("protocols", standardShareModes()),
				tenantConfigField("failureBehavior", standardShareModes()),
				operationalField("lastModifiedTime", standardShareModes()),
				operationalField("autoCreated", allModes()),
				operationalField("natZtrGateway", allModes()),
				tenantConfigField("dnsGatewayProtocols", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "nat-control-rules",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA NAT control rule description"),
				operationalField("order", allModes()),
				operationalField("rank", allModes()),
				operationalField("state", allModes()),
				operationalField("accessControl", standardShareModes()),
				sensitiveIdentifierField("redirectFqdn"),
				sensitiveIdentifierField("redirectIp"),
				tenantConfigField("redirectPort", standardShareModes()),
				operationalField("lastModifiedTime", standardShareModes()),
				operationalField("trustedResolverRule", allModes()),
				operationalField("enableFullLogging", allModes()),
				operationalField("predefined", allModes()),
				operationalField("defaultRule", allModes()),
				sensitiveIdentifierField("destAddresses"),
				sensitiveIdentifierField("srcIps"),
				operationalField("destCountries", standardShareModes()),
				sensitiveIdentifierField("destIpCategories"),
				sensitiveIdentifierField("resCategories"),
				idNameExtensionsField("labels", standardShareModes()),
				idNameExtensionsField("timeWindows", standardShareModes()),
				idNameExtensionsField("locations", standardOnlyMode()),
				idNameExtensionsField("locationGroups", standardOnlyMode()),
				idNameExtensionsField("srcIpGroups", standardOnlyMode()),
				idNameExtensionsField("srcIpv6Groups", standardOnlyMode()),
				idNameExtensionsField("destIpGroups", standardOnlyMode()),
				idNameExtensionsField("destIpv6Groups", standardOnlyMode()),
				idNameExtensionsField("nwServices", standardOnlyMode()),
				idNameExtensionsField("nwServiceGroups", standardOnlyMode()),
				idNameExtensionsField("groups", standardOnlyMode()),
				idNameExtensionsField("departments", standardOnlyMode()),
				idNameExtensionsField("users", standardOnlyMode()),
				idNameExtensionsField("devices", standardOnlyMode()),
				idNameExtensionsField("deviceGroups", standardOnlyMode()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				tenantConfigField("idpId", standardShareModes()),
				freeTextField("comments", "ZIA group comments"),
				operationalField("isSystemDefined", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "departments",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				tenantConfigField("idpId", standardShareModes()),
				freeTextField("comments", "ZIA department comments"),
				operationalField("deleted", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "users",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				sensitiveIdentifierField("name"),
				sensitiveIdentifierField("email"),
				idNameField("groups", standardOnlyMode()),
				idNameField("department", standardOnlyMode()),
				freeTextField("comments", "ZIA user comments"),
				sensitiveIdentifierField("tempAuthEmail"),
				tenantConfigField("authMethods", standardOnlyMode()),
				secretField("password"),
				operationalField("adminUser", standardShareModes()),
				tenantConfigField("type", standardShareModes()),
				operationalField("deleted", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "device-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("groupType", allModes()),
				freeTextField("description", "ZIA device group description"),
				operationalField("osType", allModes()),
				operationalField("predefined", allModes()),
				sensitiveIdentifierField("deviceNames"),
				operationalField("deviceCount", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "devices",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				sensitiveIdentifierField("name"),
				tenantConfigField("deviceGroupType", standardShareModes()),
				sensitiveIdentifierField("deviceModel"),
				tenantConfigField("osType", standardShareModes()),
				tenantConfigField("osVersion", standardShareModes()),
				freeTextField("description", "ZIA device description"),
				sensitiveIdentifierField("ownerUserId"),
				sensitiveIdentifierField("ownerName"),
				sensitiveIdentifierField("hostName"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "workload-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA workload group description"),
				sensitiveIdentifierField("expression"),
				operationalField("lastModifiedTime", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "alert-subscriptions",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				freeTextField("description", "ZIA alert subscription description"),
				sensitiveIdentifierField("email"),
				operationalField("deleted", allModes()),
				tenantConfigField("pt0Severities", standardShareModes()),
				tenantConfigField("secureSeverities", standardShareModes()),
				tenantConfigField("manageSeverities", standardShareModes()),
				tenantConfigField("complySeverities", standardShareModes()),
				tenantConfigField("systemSeverities", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "activation-status",
			Operations: ShowOperation(),
			Fields: []FieldSpec{
				operationalField("status", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "eusa-status",
			Operations: ShowOperation(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				idNameExtensionsField("version", standardShareModes()),
				tenantConfigField("acceptedStatus", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "auth-exempted-urls",
			Operations: ShowOperation(),
			Fields: []FieldSpec{
				sensitiveIdentifierField("urls"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "intermediate-ca-certificates",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA intermediate CA certificate description"),
				tenantConfigField("type", standardShareModes()),
				sensitiveIdentifierField("region"),
				tenantConfigField("status", standardShareModes()),
				tenantConfigField("defaultCertificate", standardShareModes()),
				operationalField("certStartDate", standardShareModes()),
				operationalField("certExpDate", standardShareModes()),
				tenantConfigField("currentState", standardShareModes()),
				secretField("publicKey"),
				operationalField("keyGenerationTime", standardShareModes()),
				operationalField("hsmAttestationVerifiedTime", standardShareModes()),
				sensitiveIdentifierField("csrFileName"),
				operationalField("csrGenerationTime", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "cloud-app-instances",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("instanceId", allModes()),
				operationalField("instanceType", allModes()),
				tenantConfigField("instanceName", standardShareModes()),
				operationalField("modifiedAt", standardShareModes()),
				secretField("modifiedBy"),
				secretField("instanceIdentifiers"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "tenancy-restriction-profiles",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("appType", allModes()),
				freeTextField("description", "ZIA tenancy restriction profile description"),
				operationalField("itemTypePrimary", allModes()),
				operationalField("itemTypeSecondary", allModes()),
				tenantConfigField("restrictPersonalO365Domains", standardShareModes()),
				tenantConfigField("allowGoogleConsumers", standardShareModes()),
				tenantConfigField("msLoginServicesTrV2", standardShareModes()),
				tenantConfigField("allowGoogleVisitors", standardShareModes()),
				tenantConfigField("allowGcpCloudStorageRead", standardShareModes()),
				sensitiveIdentifierField("itemDataPrimary"),
				sensitiveIdentifierField("itemDataSecondary"),
				sensitiveIdentifierField("itemValue"),
				operationalField("lastModifiedTime", standardShareModes()),
				sensitiveIdentifierField("lastModifiedUserId"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "vzen-clusters",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("status", allModes()),
				sensitiveIdentifierField("ipAddress"),
				sensitiveIdentifierField("subnetMask"),
				sensitiveIdentifierField("defaultGateway"),
				operationalField("type", allModes()),
				operationalField("ipSecEnabled", allModes()),
				idNameExternalIDField("virtualZenNodes", standardOnlyMode()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "vzen-nodes",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				operationalField("zgatewayId", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("status", allModes()),
				operationalField("inProduction", allModes()),
				sensitiveIdentifierField("ipAddress"),
				sensitiveIdentifierField("subnetMask"),
				sensitiveIdentifierField("defaultGateway"),
				operationalField("type", allModes()),
				operationalField("ipSecEnabled", allModes()),
				operationalField("onDemandSupportTunnelEnabled", allModes()),
				operationalField("establishSupportTunnelEnabled", allModes()),
				sensitiveIdentifierField("loadBalancerIpAddress"),
				operationalField("deploymentMode", allModes()),
				tenantConfigField("clusterName", standardShareModes()),
				operationalField("vzenSkuType", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "dlp-engines",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA DLP engine description"),
				tenantConfigField("predefinedEngineName", standardShareModes()),
				sensitiveIdentifierField("engineExpression"),
				operationalField("customDlpEngine", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "dlp-dictionaries",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA DLP dictionary description"),
				tenantConfigField("confidenceThreshold", standardShareModes()),
				tenantConfigField("customPhraseMatchType", standardShareModes()),
				operationalField("nameL10nTag", allModes()),
				operationalField("custom", allModes()),
				tenantConfigField("thresholdType", standardShareModes()),
				tenantConfigField("dictionaryType", standardShareModes()),
				operationalField("proximity", allModes()),
				secretField("phrases"),
				secretField("patterns"),
				secretField("exactDataMatchDetails"),
				secretField("idmProfileMatchAccuracyDetails"),
				operationalField("ignoreExactMatchIdmDict", allModes()),
				operationalField("includeBinNumbers", allModes()),
				secretField("binNumbers"),
				operationalField("dictTemplateId", allModes()),
				operationalField("predefinedClone", allModes()),
				tenantConfigField("predefinedCountActionType", standardShareModes()),
				operationalField("proximityLengthEnabled", allModes()),
				operationalField("proximityEnabledForCustomDictionary", allModes()),
				operationalField("dictionaryCloningEnabled", allModes()),
				operationalField("customPhraseSupported", allModes()),
				operationalField("hierarchicalDictionary", allModes()),
				secretField("hierarchicalIdentifiers"),
				secretField("predefinedPhrases"),
				operationalField("thresholdAllowed", allModes()),
				tenantConfigField("confidenceLevelForPredefinedDict", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "dlp-edm-schemas",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("schemaId", allModes()),
				idNameExtensionsField("edmClient", standardOnlyMode()),
				sensitiveIdentifierField("projectName"),
				operationalField("revision", allModes()),
				sensitiveIdentifierField("filename"),
				sensitiveIdentifierField("originalFileName"),
				operationalField("fileUploadStatus", allModes()),
				operationalField("schemaStatus", allModes()),
				operationalField("origColCount", standardOnlyMode()),
				operationalField("lastModifiedTime", allModes()),
				secretField("modifiedBy"),
				secretField("createdBy"),
				operationalField("cellsUsed", standardOnlyMode()),
				operationalField("schemaActive", allModes()),
				operationalField("schedulePresent", allModes()),
				secretField("tokenList"),
				secretField("schedule"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "dlp-idm-profile-lite",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("profileId", allModes()),
				sensitiveIdentifierField("templateName"),
				idNameExtensionsField("clientVm", standardOnlyMode()),
				operationalField("numDocuments", standardOnlyMode()),
				operationalField("lastModifiedTime", allModes()),
				secretField("modifiedBy"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "dlp-idm-profiles",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("profileId", allModes()),
				sensitiveIdentifierField("profileName"),
				freeTextField("profileDesc", "ZIA DLP IDM profile description"),
				tenantConfigField("profileType", standardShareModes()),
				sensitiveIdentifierField("host"),
				sensitiveIdentifierField("port"),
				sensitiveIdentifierField("profileDirPath"),
				tenantConfigField("scheduleType", standardOnlyMode()),
				operationalField("scheduleDay", standardOnlyMode()),
				tenantConfigField("scheduleDayOfMonth", standardOnlyMode()),
				tenantConfigField("scheduleDayOfWeek", standardOnlyMode()),
				operationalField("scheduleTime", standardOnlyMode()),
				operationalField("scheduleDisabled", standardOnlyMode()),
				operationalField("uploadStatus", allModes()),
				sensitiveIdentifierField("userName"),
				operationalField("version", allModes()),
				idNameExtensionsField("idmClient", standardOnlyMode()),
				operationalField("volumeOfDocuments", standardOnlyMode()),
				operationalField("numDocuments", standardOnlyMode()),
				operationalField("lastModifiedTime", allModes()),
				secretField("modifiedBy"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "dlp-web-rules",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				operationalField("order", allModes()),
				operationalField("accessControl", standardShareModes()),
				tenantConfigField("protocols", standardShareModes()),
				operationalField("rank", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA DLP web rule description"),
				tenantConfigField("fileTypes", standardShareModes()),
				tenantConfigField("cloudApplications", standardShareModes()),
				operationalField("minSize", allModes()),
				tenantConfigField("action", standardShareModes()),
				operationalField("state", allModes()),
				operationalField("matchOnly", allModes()),
				operationalField("lastModifiedTime", allModes()),
				operationalField("withoutContentInspection", allModes()),
				operationalField("ocrEnabled", allModes()),
				operationalField("dlpDownloadScanEnabled", allModes()),
				operationalField("zccNotificationsEnabled", allModes()),
				operationalField("zscalerIncidentReceiver", allModes()),
				sensitiveIdentifierField("eunTemplateId"),
				sensitiveIdentifierField("externalAuditorEmail"),
				idNameField("auditor", standardOnlyMode()),
				secretField("lastModifiedBy"),
				idNameField("notificationTemplate", standardOnlyMode()),
				idNameField("icapServer", standardOnlyMode()),
				{
					Name:           "receiver",
					Classification: ClassTenantConfig,
					AllowedModes:   standardOnlyMode(),
					Fields: []FieldSpec{
						operationalField("id", allModes()),
						tenantConfigField("name", standardShareModes()),
						operationalField("type", allModes()),
						secretField("tenant"),
					},
				},
				idNameExtensionsField("locations", standardOnlyMode()),
				idNameExtensionsField("locationGroups", standardOnlyMode()),
				idNameExtensionsField("groups", standardOnlyMode()),
				idNameExtensionsField("departments", standardOnlyMode()),
				idNameExtensionsField("users", standardOnlyMode()),
				idNameExtensionsField("urlCategories", standardOnlyMode()),
				idNameExtensionsField("dlpEngines", standardOnlyMode()),
				idNameExtensionsField("timeWindows", standardOnlyMode()),
				idNameExtensionsField("labels", standardOnlyMode()),
				idNameExtensionsField("excludedGroups", standardOnlyMode()),
				idNameExtensionsField("excludedDepartments", standardOnlyMode()),
				idNameExtensionsField("excludedUsers", standardOnlyMode()),
				idNameExtensionsField("includedDomainProfiles", standardOnlyMode()),
				idNameExtensionsField("excludedDomainProfiles", standardOnlyMode()),
				idNameExtensionsField("sourceIpGroups", standardOnlyMode()),
				idNameField("workloadGroups", standardOnlyMode()),
				idNameField("fileTypeCategories", standardOnlyMode()),
				tenantConfigField("severity", standardShareModes()),
				operationalField("parentRule", allModes()),
				secretField("subRules"),
				tenantConfigField("userRiskScoreLevels", standardOnlyMode()),
				tenantConfigField("dlpContentLocationsScopes", standardShareModes()),
				operationalField("inspectHttpGetEnabled", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "dlp-icap-servers",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				sensitiveIdentifierField("url"),
				operationalField("status", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "dlp-incident-receiver-servers",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				sensitiveIdentifierField("url"),
				tenantConfigField("status", standardShareModes()),
				operationalField("flags", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "dlp-notification-templates",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("subject", "DLP notification template subject"),
				tenantConfigField("attachContent", standardOnlyMode()),
				secretField("plainTextMessage"),
				secretField("htmlMessage"),
				tenantConfigField("tlsEnabled", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "c2c-incident-receivers",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("status", allModes()),
				operationalField("modifiedTime", allModes()),
				operationalField("lastTenantValidationTime", standardOnlyMode()),
				secretField("lastValidationMsg"),
				secretField("lastModifiedBy"),
				{
					Name:           "onboardableEntity",
					Classification: ClassTenantConfig,
					AllowedModes:   standardOnlyMode(),
					Fields: []FieldSpec{
						operationalField("id", allModes()),
						tenantConfigField("name", standardShareModes()),
						operationalField("type", allModes()),
						sensitiveIdentifierField("enterpriseTenantId"),
						tenantConfigField("application", standardShareModes()),
						secretField("lastValidationMsg"),
						secretField("tenantAuthorizationInfo"),
						idNameExtensionsField("zscalerAppTenantId", standardOnlyMode()),
					},
				},
			},
		},
		{
			Product:    ProductZIA,
			Name:       "risk-profiles",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("profileName", standardShareModes()),
				operationalField("profileType", allModes()),
				operationalField("status", allModes()),
				operationalField("createTime", allModes()),
				operationalField("lastModTime", allModes()),
				idNameExternalIDField("customTags", standardOnlyMode()),
				idNameExtensionsField("modifiedBy", standardOnlyMode()),
				sensitiveIdentifierField("sourceIpRestrictions"),
				secretField("adminAuditLogs"),
				secretField("certifications"),
				secretField("dataBreach"),
				secretField("dataEncryptionInTransit"),
				secretField("dnsCaaPolicy"),
				secretField("domainBasedMessageAuth"),
				secretField("domainKeysIdentifiedMail"),
				secretField("evasive"),
				secretField("excludeCertificates"),
				secretField("fileSharing"),
				secretField("httpSecurityHeaders"),
				secretField("malwareScanningForContent"),
				secretField("mfaSupport"),
				secretField("passwordStrength"),
				secretField("poorItemsOfService"),
				secretField("remoteScreenSharing"),
				secretField("riskIndex"),
				secretField("senderPolicyFramework"),
				secretField("sslCertKeySize"),
				secretField("sslCertValidity"),
				secretField("sslPinned"),
				secretField("supportForWaf"),
				secretField("vulnerability"),
				secretField("vulnerabilityDisclosure"),
				secretField("vulnerableToHeartBleed"),
				secretField("vulnerableToLogJam"),
				secretField("vulnerableToPoodle"),
				secretField("weakCipherSupport"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "nss-servers",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("status", allModes()),
				operationalField("state", allModes()),
				operationalField("type", allModes()),
				sensitiveIdentifierField("icapSvrId"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "nss-feeds",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("feedStatus", allModes()),
				operationalField("nssLogType", allModes()),
				operationalField("nssFeedType", allModes()),
				tenantConfigField("feedOutputFormat", standardShareModes()),
				tenantConfigField("userObfuscation", standardShareModes()),
				tenantConfigField("timeZone", standardShareModes()),
				operationalField("epsRateLimit", allModes()),
				operationalField("jsonArrayToggle", allModes()),
				tenantConfigField("siemType", standardShareModes()),
				operationalField("maxBatchSize", allModes()),
				sensitiveIdentifierField("connectionURL"),
				secretField("authenticationToken"),
				secretField("connectionHeaders"),
				operationalField("lastSuccessFullTest", standardShareModes()),
				operationalField("testConnectivityCode", allModes()),
				secretField("base64EncodedCertificate"),
				operationalField("nssType", allModes()),
				secretField("clientId"),
				secretField("clientSecret"),
				sensitiveIdentifierField("authenticationUrl"),
				tenantConfigField("grantType", standardShareModes()),
				secretField("scope"),
				operationalField("cloudNss", allModes()),
				operationalField("oauthAuthentication", allModes()),
				sensitiveIdentifierField("serverIps"),
				sensitiveIdentifierField("clientIps"),
				sensitiveIdentifierField("domains"),
				tenantConfigField("dnsRequestTypes", standardShareModes()),
				tenantConfigField("dnsResponseTypes", standardShareModes()),
				tenantConfigField("dnsResponses", standardShareModes()),
				tenantConfigField("durations", standardShareModes()),
				tenantConfigField("dnsActions", standardShareModes()),
				tenantConfigField("firewallLoggingMode", standardShareModes()),
				sensitiveIdentifierField("clientSourceIps"),
				tenantConfigField("firewallActions", standardShareModes()),
				operationalField("countries", standardShareModes()),
				secretField("serverSourcePorts"),
				secretField("clientSourcePorts"),
				tenantConfigField("actionFilter", standardShareModes()),
				tenantConfigField("emailDlpPolicyAction", standardShareModes()),
				tenantConfigField("direction", standardShareModes()),
				tenantConfigField("event", standardShareModes()),
				tenantConfigField("policyReasons", standardShareModes()),
				tenantConfigField("protocolTypes", standardShareModes()),
				sensitiveIdentifierField("userAgents"),
				tenantConfigField("requestMethods", standardShareModes()),
				tenantConfigField("casbPolicyTypes", standardShareModes()),
				tenantConfigField("urlSuperCategories", standardShareModes()),
				tenantConfigField("responseCodes", standardShareModes()),
				tenantConfigField("nwApplications", standardShareModes()),
				tenantConfigField("natActions", standardShareModes()),
				tenantConfigField("tunnelTypes", standardShareModes()),
				tenantConfigField("auditLogType", standardShareModes()),
				sensitiveIdentifierField("projectName"),
				sensitiveIdentifierField("repoName"),
				sensitiveIdentifierField("objectName"),
				sensitiveIdentifierField("channelName"),
				sensitiveIdentifierField("fileSource"),
				sensitiveIdentifierField("fileName"),
				tenantConfigField("sessionCounts", standardShareModes()),
				sensitiveIdentifierField("refererUrls"),
				sensitiveIdentifierField("hostNames"),
				sensitiveIdentifierField("fullUrls"),
				tenantConfigField("threatNames", standardShareModes()),
				tenantConfigField("pageRiskIndexes", standardShareModes()),
				sensitiveIdentifierField("clientDestinationPorts"),
				sensitiveIdentifierField("tunnelSourcePort"),
				secretField("customEscapedCharacter"),
				secretField("casbSeverity"),
				secretField("casbApplications"),
				secretField("casbAction"),
				secretField("webApplications"),
				secretField("webApplicationClasses"),
				secretField("malwareNames"),
				secretField("urlClasses"),
				secretField("malwareClasses"),
				secretField("advancedThreats"),
				secretField("trafficForwards"),
				secretField("webTrafficForwards"),
				secretField("alerts"),
				secretField("objectType"),
				secretField("activity"),
				secretField("objectType1"),
				secretField("objectType2"),
				secretField("endPointDLPLogType"),
				secretField("emailDLPLogType"),
				tenantConfigField("fileTypeSuperCategories", standardShareModes()),
				tenantConfigField("fileTypeCategories", standardShareModes()),
				tenantConfigField("casbFileType", standardShareModes()),
				tenantConfigField("casbFileTypeSuperCategories", standardShareModes()),
				tenantConfigField("messageSize", standardShareModes()),
				tenantConfigField("fileSizes", standardShareModes()),
				tenantConfigField("requestSizes", standardShareModes()),
				tenantConfigField("responseSizes", standardShareModes()),
				tenantConfigField("transactionSizes", standardShareModes()),
				tenantConfigField("inBoundBytes", standardShareModes()),
				tenantConfigField("outBoundBytes", standardShareModes()),
				tenantConfigField("downloadTime", standardShareModes()),
				tenantConfigField("scanTime", standardShareModes()),
				sensitiveIdentifierField("serverSourceIps"),
				sensitiveIdentifierField("serverDestinationIps"),
				sensitiveIdentifierField("tunnelIps"),
				sensitiveIdentifierField("internalIps"),
				sensitiveIdentifierField("tunnelSourceIps"),
				sensitiveIdentifierField("tunnelDestIps"),
				sensitiveIdentifierField("clientDestinationIps"),
				sensitiveIdentifierField("advUserAgents"),
				idNameExtensionsField("externalOwners", standardOnlyMode()),
				idNameExtensionsField("externalCollaborators", standardOnlyMode()),
				idNameExtensionsField("internalCollaborators", standardOnlyMode()),
				idNameExtensionsField("itsmObjectType", standardOnlyMode()),
				idNameExtensionsField("urlCategories", standardOnlyMode()),
				idNameExtensionsField("dlpEngines", standardOnlyMode()),
				idNameExtensionsField("dlpDictionaries", standardOnlyMode()),
				idNameExtensionsField("rules", standardOnlyMode()),
				idNameExtensionsField("nwServices", standardOnlyMode()),
				secretField("casbTenant"),
				secretField("locations"),
				secretField("locationGroups"),
				secretField("users"),
				secretField("departments"),
				secretField("senderName"),
				secretField("buckets"),
				secretField("vpnCredentials"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "file-type-rules",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA file type rule description"),
				operationalField("state", allModes()),
				operationalField("order", allModes()),
				operationalField("rank", allModes()),
				tenantConfigField("filteringAction", standardShareModes()),
				operationalField("timeQuota", standardShareModes()),
				operationalField("sizeQuota", standardShareModes()),
				operationalField("accessControl", standardShareModes()),
				operationalField("capturePCAP", allModes()),
				secretField("passwordProtected"),
				tenantConfigField("operation", standardShareModes()),
				operationalField("activeContent", allModes()),
				operationalField("unscannable", allModes()),
				sensitiveIdentifierField("browserEunTemplateId"),
				tenantConfigField("cloudApplications", standardShareModes()),
				tenantConfigField("fileTypes", standardShareModes()),
				operationalField("minSize", standardShareModes()),
				operationalField("maxSize", standardShareModes()),
				tenantConfigField("protocols", standardShareModes()),
				tenantConfigField("urlCategories", standardShareModes()),
				operationalField("lastModifiedTime", standardShareModes()),
				secretField("lastModifiedBy"),
				idNameExtensionsField("locations", standardOnlyMode()),
				idNameExtensionsField("locationGroups", standardOnlyMode()),
				idNameExtensionsField("groups", standardOnlyMode()),
				idNameExtensionsField("departments", standardOnlyMode()),
				idNameExtensionsField("users", standardOnlyMode()),
				idNameExtensionsField("timeWindows", standardShareModes()),
				idNameExtensionsField("labels", standardShareModes()),
				idNameExtensionsField("deviceGroups", standardOnlyMode()),
				idNameExtensionsField("devices", standardOnlyMode()),
				tenantConfigField("deviceTrustLevels", standardShareModes()),
				idNameExternalIDField("zpaAppSegments", standardOnlyMode()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "sandbox-rules",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA sandbox rule description"),
				operationalField("state", allModes()),
				operationalField("order", allModes()),
				operationalField("rank", allModes()),
				tenantConfigField("baRuleAction", standardShareModes()),
				operationalField("firstTimeEnable", allModes()),
				tenantConfigField("firstTimeOperation", standardShareModes()),
				operationalField("mlActionEnabled", allModes()),
				operationalField("byThreatScore", standardShareModes()),
				operationalField("accessControl", standardShareModes()),
				tenantConfigField("protocols", standardShareModes()),
				tenantConfigField("baPolicyCategories", standardShareModes()),
				tenantConfigField("fileTypes", standardShareModes()),
				operationalField("lastModifiedTime", standardShareModes()),
				secretField("lastModifiedBy"),
				idNameExtensionsField("locations", standardOnlyMode()),
				idNameExtensionsField("locationGroups", standardOnlyMode()),
				idNameExtensionsField("groups", standardOnlyMode()),
				idNameExtensionsField("departments", standardOnlyMode()),
				idNameExtensionsField("users", standardOnlyMode()),
				idNameExtensionsField("timeWindows", standardShareModes()),
				idNameExtensionsField("labels", standardShareModes()),
				idNameExtensionsField("deviceGroups", standardOnlyMode()),
				idNameExtensionsField("devices", standardOnlyMode()),
				tenantConfigField("urlCategories", standardShareModes()),
				idNameExternalIDField("zpaAppSegments", standardOnlyMode()),
				operationalField("defaultRule", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "firewall-dns-rules",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("order", allModes()),
				operationalField("rank", allModes()),
				operationalField("accessControl", standardShareModes()),
				tenantConfigField("action", standardShareModes()),
				operationalField("state", allModes()),
				freeTextField("description", "ZIA firewall DNS rule description"),
				sensitiveIdentifierField("redirectIp"),
				tenantConfigField("blockResponseCode", standardShareModes()),
				operationalField("lastModifiedTime", standardShareModes()),
				secretField("lastModifiedBy"),
				sensitiveIdentifierField("srcIps"),
				sensitiveIdentifierField("destAddresses"),
				sensitiveIdentifierField("destIpCategories"),
				operationalField("destCountries", standardShareModes()),
				operationalField("sourceCountries", standardShareModes()),
				sensitiveIdentifierField("resCategories"),
				tenantConfigField("applications", standardShareModes()),
				tenantConfigField("dnsRuleRequestTypes", standardShareModes()),
				tenantConfigField("protocols", standardShareModes()),
				operationalField("defaultRule", allModes()),
				operationalField("capturePCAP", allModes()),
				operationalField("predefined", allModes()),
				operationalField("isWebEunEnabled", allModes()),
				operationalField("defaultDnsRuleNameUsed", allModes()),
				idNameExtensionsField("applicationGroups", standardShareModes()),
				idNameField("dnsGateway", standardOnlyMode()),
				idNameField("zpaIpGroup", standardOnlyMode()),
				idNameField("ednsEcsObject", standardOnlyMode()),
				idNameExtensionsField("locations", standardOnlyMode()),
				idNameExtensionsField("locationGroups", standardOnlyMode()),
				idNameExtensionsField("departments", standardOnlyMode()),
				idNameExtensionsField("groups", standardOnlyMode()),
				idNameExtensionsField("users", standardOnlyMode()),
				idNameExtensionsField("timeWindows", standardShareModes()),
				idNameExtensionsField("labels", standardShareModes()),
				idNameExtensionsField("destIpGroups", standardOnlyMode()),
				idNameExtensionsField("destIpv6Groups", standardOnlyMode()),
				idNameExtensionsField("srcIpGroups", standardOnlyMode()),
				idNameExtensionsField("srcIpv6Groups", standardOnlyMode()),
				idNameExtensionsField("deviceGroups", standardOnlyMode()),
				idNameExtensionsField("devices", standardOnlyMode()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "custom-file-types",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA custom file type description"),
				tenantConfigField("extension", standardShareModes()),
				operationalField("fileTypeId", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "zpa-gateways",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA ZPA gateway description"),
				idNameExternalIDField("zpaServerGroup", standardOnlyMode()),
				idNameExternalIDField("zpaAppSegments", standardOnlyMode()),
				sensitiveIdentifierField("zpaTenantId"),
				secretField("lastModifiedBy"),
				operationalField("lastModifiedTime", standardShareModes()),
				operationalField("type", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "browser-isolation-profiles",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				sensitiveIdentifierField("id"),
				tenantConfigField("name", standardShareModes()),
				sensitiveIdentifierField("url"),
				operationalField("defaultProfile", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "dlp-edm-schemas-lite",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				{
					Name:           "schema",
					Classification: ClassTenantConfig,
					AllowedModes:   standardOnlyMode(),
					Fields: []FieldSpec{
						operationalField("id", allModes()),
						sensitiveIdentifierField("name"),
						sensitiveIdentifierField("externalId"),
					},
				},
				secretField("tokenList"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "dc-exclusions",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("dcid", allModes()),
				operationalField("expired", allModes()),
				operationalField("startTime", standardShareModes()),
				operationalField("endTime", standardShareModes()),
				freeTextField("description", "ZIA DC exclusion description"),
				idNameExtensionsField("dcName", standardOnlyMode()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "sub-clouds",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				{
					Name:           "dcs",
					Classification: ClassTenantConfig,
					AllowedModes:   standardOnlyMode(),
					Fields: []FieldSpec{
						operationalField("id", allModes()),
						tenantConfigField("name", standardShareModes()),
						sensitiveIdentifierField("country"),
					},
				},
				{
					Name:           "exclusions",
					Classification: ClassTenantConfig,
					AllowedModes:   standardOnlyMode(),
					Fields: []FieldSpec{
						idNameExtensionsField("datacenter", standardOnlyMode()),
						secretField("lastModifiedUser"),
						sensitiveIdentifierField("country"),
						operationalField("expired", allModes()),
						operationalField("disabledByOps", allModes()),
						operationalField("createTime", allModes()),
						operationalField("startTime", standardShareModes()),
						operationalField("endTime", standardShareModes()),
						operationalField("lastModifiedTime", allModes()),
					},
				},
			},
		},
		{
			Product:    ProductZIA,
			Name:       "ipv6-config",
			Operations: ShowOperation(),
			Fields: []FieldSpec{
				operationalField("ipV6Enabled", allModes()),
				{
					Name:           "natPrefixes",
					Classification: ClassTenantConfig,
					AllowedModes:   standardOnlyMode(),
					Fields: []FieldSpec{
						operationalField("id", allModes()),
						tenantConfigField("name", standardShareModes()),
						freeTextField("description", "ZIA IPv6 NAT prefix description"),
						sensitiveIdentifierField("prefixMask"),
						operationalField("dnsPrefix", allModes()),
						operationalField("nonEditable", allModes()),
					},
				},
				sensitiveIdentifierField("dnsPrefix"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "ipv6-dns64-prefixes",
			Operations: ListOperations(),
			Fields:     ipv6PrefixFields("ZIA IPv6 DNS64 prefix description"),
		},
		{
			Product:    ProductZIA,
			Name:       "ipv6-nat64-prefixes",
			Operations: ListOperations(),
			Fields:     ipv6PrefixFields("ZIA IPv6 NAT64 prefix description"),
		},
		{
			Product:    ProductZIA,
			Name:       "pac-files",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA PAC file description"),
				sensitiveIdentifierField("domain"),
				sensitiveIdentifierField("pacUrl"),
				freeTextField("pacContent", "ZIA PAC file content"),
				operationalField("editable", allModes()),
				sensitiveIdentifierField("pacSubURL"),
				operationalField("pacUrlObfuscated", allModes()),
				operationalField("pacVerificationStatus", standardShareModes()),
				tenantConfigField("pacVersionStatus", standardShareModes()),
				operationalField("pacVersion", allModes()),
				freeTextField("pacCommitMessage", "ZIA PAC file commit message"),
				operationalField("totalHits", standardShareModes()),
				operationalField("lastModificationTime", standardShareModes()),
				secretField("lastModifiedBy"),
				operationalField("createTime", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "cloud-application-policy",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				tenantConfigField("app", standardShareModes()),
				tenantConfigField("appName", standardShareModes()),
				tenantConfigField("parent", standardShareModes()),
				tenantConfigField("parentName", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "cloud-application-ssl-policy",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				tenantConfigField("app", standardShareModes()),
				tenantConfigField("appName", standardShareModes()),
				tenantConfigField("parent", standardShareModes()),
				tenantConfigField("parentName", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "domain-profiles",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("profileId", allModes()),
				tenantConfigField("profileName", standardShareModes()),
				operationalField("includeCompanyDomains", allModes()),
				operationalField("includeSubdomains", allModes()),
				freeTextField("description", "ZIA SaaS domain profile description"),
				sensitiveIdentifierField("customDomains"),
				tenantConfigField("predefinedEmailDomains", standardOnlyMode()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "casb-tombstone-templates",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "CASB tombstone template text"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "casb-email-labels",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("labelDesc", "CASB email label description"),
				tenantConfigField("labelColor", standardShareModes()),
				operationalField("labelDeleted", allModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "casb-tenants",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("tenantId", allModes()),
				operationalField("modifiedTime", standardShareModes()),
				operationalField("lastTenantValidationTime", standardOnlyMode()),
				operationalField("tenantDeleted", allModes()),
				operationalField("tenantWebhookEnabled", allModes()),
				operationalField("reAuth", allModes()),
				tenantConfigField("featuresSupported", standardShareModes()),
				tenantConfigField("status", standardShareModes()),
				sensitiveIdentifierField("enterpriseTenantId"),
				sensitiveIdentifierField("tenantName"),
				tenantConfigField("saasApplication", standardShareModes()),
				idNameField("zscalerAppTenantId", standardOnlyMode()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "casb-dlp-rules",
			Operations: ListOperations(),
			Fields: fieldList(
				operationalFields("id", "order", "rank", "lastModifiedTime"),
				tenantConfigFields("type", "name", "state", "action", "severity", "accessControl"),
				[]FieldSpec{freeTextField("description", "CASB DLP rule description")},
				sensitiveIdentifierFields(
					"bucketOwner",
					"externalAuditorEmail",
					"contentLocation",
					"recipient",
					"quarantineLocation",
					"domains",
				),
				tenantConfigFields(
					"numberOfInternalCollaborators",
					"numberOfExternalCollaborators",
					"watermarkDeleteOldVersion",
					"includeCriteriaDomainProfile",
					"includeEmailRecipientProfile",
					"withoutContentInspection",
					"includeEntityGroups",
					"fileTypes",
					"collaborationScope",
					"components",
					"deviceTrustLevels",
				),
				[]FieldSpec{
					idNameExtensionsField("objectTypes", standardOnlyMode()),
					idNameExtensionsField("buckets", standardOnlyMode()),
					idNameExtensionsField("labels", standardShareModes()),
					idNameExtensionsField("includedDomainProfiles", standardOnlyMode()),
					idNameExtensionsField("excludedDomainProfiles", standardOnlyMode()),
					idNameExtensionsField("criteriaDomainProfiles", standardOnlyMode()),
					idNameExtensionsField("emailRecipientProfiles", standardOnlyMode()),
					idNameExtensionsField("devices", standardOnlyMode()),
					idNameExtensionsField("deviceGroups", standardOnlyMode()),
					idNameExtensionsField("entityGroups", standardOnlyMode()),
					idNameExtensionsField("cloudAppTenants", standardOnlyMode()),
					idNameExtensionsField("users", standardOnlyMode()),
					idNameExtensionsField("groups", standardOnlyMode()),
					idNameExtensionsField("departments", standardOnlyMode()),
					idNameExtensionsField("dlpEngines", standardOnlyMode()),
					secretField("lastModifiedBy"),
					idNameField("auditor", standardOnlyMode()),
					idNameField("zscalerIncidentReceiver", standardOnlyMode()),
					idNameField("auditorNotification", standardOnlyMode()),
					idNameField("tag", standardOnlyMode()),
					idNameField("watermarkProfile", standardOnlyMode()),
					idNameField("redactionProfile", standardOnlyMode()),
					idNameField("casbEmailLabel", standardOnlyMode()),
					idNameField("casbTombstoneTemplate", standardOnlyMode()),
					{
						Name:           "receiver",
						Classification: ClassTenantConfig,
						AllowedModes:   standardOnlyMode(),
						Fields: []FieldSpec{
							operationalField("id", allModes()),
							tenantConfigField("name", standardShareModes()),
							tenantConfigField("type", standardShareModes()),
							idNameExtensionsField("tenant", standardOnlyMode()),
						},
					},
				},
			),
		},
		{
			Product:    ProductZIA,
			Name:       "casb-malware-rules",
			Operations: ListOperations(),
			Fields: fieldList(
				operationalFields("id", "order", "lastModifiedTime"),
				tenantConfigFields("type", "name", "state", "action", "accessControl"),
				sensitiveIdentifierFields("quarantineLocation", "scanInboundEmailLink"),
				[]FieldSpec{
					secretField("lastModifiedBy"),
					idNameField("casbEmailLabel", standardOnlyMode()),
					idNameField("casbTombstoneTemplate", standardOnlyMode()),
					idNameExtensionsField("buckets", standardOnlyMode()),
					idNameExtensionsField("labels", standardShareModes()),
					idNameExtensionsField("cloudAppTenantIds", standardOnlyMode()),
					idNameExtensionsField("cloudAppTenants", standardOnlyMode()),
					{
						Name:           "cloudApplicationTenant",
						Classification: ClassTenantConfig,
						AllowedModes:   standardOnlyMode(),
						Fields: []FieldSpec{
							operationalField("tenantId", allModes()),
							operationalField("modifiedTime", standardShareModes()),
							operationalField("lastTenantValidationTime", standardOnlyMode()),
							operationalField("tenantDeleted", allModes()),
							operationalField("tenantWebhookEnabled", allModes()),
							operationalField("reAuth", allModes()),
							tenantConfigField("featuresSupported", standardShareModes()),
							tenantConfigField("status", standardShareModes()),
							sensitiveIdentifierField("enterpriseTenantId"),
							sensitiveIdentifierField("tenantName"),
							tenantConfigField("saasApplication", standardShareModes()),
							idNameField("zscalerAppTenantId", standardOnlyMode()),
						},
					},
				},
			),
		},
		{
			Product:    ProductZIA,
			Name:       "browser-control-settings",
			Operations: ShowOperation(),
			Fields: fieldList(
				tenantConfigFields(
					"pluginCheckFrequency",
					"bypassAllBrowsers",
					"allowAllBrowsers",
					"enableWarnings",
					"enableSmartBrowserIsolation",
				),
				sensitiveIdentifierFields(
					"bypassPlugins",
					"bypassApplications",
					"blockedInternetExplorerVersions",
					"blockedChromeVersions",
					"blockedFirefoxVersions",
					"blockedSafariVersions",
					"blockedOperaVersions",
				),
				[]FieldSpec{
					operationalField("smartIsolationProfileId", standardOnlyMode()),
					idNameExtensionsField("smartIsolationUsers", standardOnlyMode()),
					idNameExtensionsField("smartIsolationGroups", standardOnlyMode()),
					{
						Name:           "smartIsolationProfile",
						Classification: ClassTenantConfig,
						AllowedModes:   standardOnlyMode(),
						Fields: []FieldSpec{
							operationalField("id", allModes()),
							tenantConfigField("name", standardShareModes()),
							sensitiveIdentifierField("url"),
							operationalField("defaultProfile", allModes()),
						},
					},
				},
			),
		},
		{
			Product:    ProductZIA,
			Name:       "supported-browser-versions",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				tenantConfigField("browserType", standardShareModes()),
				tenantConfigField("versions", standardShareModes()),
				tenantConfigField("olderVersions", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "ftp-control-policy",
			Operations: ShowOperation(),
			Fields: []FieldSpec{
				tenantConfigField("ftpOverHttpEnabled", standardShareModes()),
				tenantConfigField("ftpEnabled", standardShareModes()),
				tenantConfigField("urlCategories", standardShareModes()),
				sensitiveIdentifierField("urls"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "remote-assistance",
			Operations: ShowOperation(),
			Fields: []FieldSpec{
				operationalField("viewOnlyUntil", standardShareModes()),
				operationalField("fullAccessUntil", standardShareModes()),
				tenantConfigField("usernameObfuscated", standardShareModes()),
				tenantConfigField("deviceInfoObfuscate", standardShareModes()),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "admin-users",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				sensitiveIdentifierField("loginName"),
				sensitiveIdentifierField("userName"),
				sensitiveIdentifierField("email"),
				freeTextField("comments", "ZIA admin user comments"),
				operationalField("disabled", allModes()),
				secretField("password"),
				operationalField("pwdLastModifiedTime", standardOnlyMode()),
				operationalField("isNonEditable", allModes()),
				secretField("isPasswordLoginAllowed"),
				secretField("isPasswordExpired"),
				operationalField("isAuditor", allModes()),
				tenantConfigField("isSecurityReportCommEnabled", standardShareModes()),
				tenantConfigField("isServiceUpdateCommEnabled", standardShareModes()),
				tenantConfigField("isProductUpdateCommEnabled", standardShareModes()),
				tenantConfigField("isExecMobileAppEnabled", standardShareModes()),
				idNameExtensionsField("adminScopescopeGroupMemberEntities", standardOnlyMode()),
				idNameExtensionsField("adminScopeScopeEntities", standardOnlyMode()),
				tenantConfigField("adminScopeType", standardShareModes()),
				{
					Name:           "role",
					Classification: ClassTenantConfig,
					AllowedModes:   standardOnlyMode(),
					Fields: []FieldSpec{
						operationalField("id", allModes()),
						tenantConfigField("name", standardShareModes()),
						operationalField("isNameL10nTag", allModes()),
						secretField("extensions"),
					},
				},
				secretField("execMobileAppTokens"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "admin-roles",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				operationalField("rank", standardOnlyMode()),
				tenantConfigField("name", standardShareModes()),
				tenantConfigField("policyAccess", standardOnlyMode()),
				tenantConfigField("alertingAccess", standardOnlyMode()),
				tenantConfigField("dashboardAccess", standardOnlyMode()),
				tenantConfigField("reportAccess", standardOnlyMode()),
				tenantConfigField("analysisAccess", standardOnlyMode()),
				tenantConfigField("usernameAccess", standardOnlyMode()),
				tenantConfigField("adminAcctAccess", standardOnlyMode()),
				tenantConfigField("deviceInfoAccess", standardOnlyMode()),
				operationalField("isAuditor", allModes()),
				tenantConfigField("permissions", standardOnlyMode()),
				operationalField("isNonEditable", allModes()),
				tenantConfigField("logsLimit", standardOnlyMode()),
				tenantConfigField("roleType", standardShareModes()),
				tenantConfigField("reportTimeDuration", standardOnlyMode()),
				secretField("featurePermissions"),
				secretField("extFeaturePermissions"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "email-profiles",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZIA email recipient profile description"),
				sensitiveIdentifierField("emails"),
			},
		},
		{
			Product:    ProductZIA,
			Name:       "advanced-settings",
			Operations: ShowOperation(),
			Fields: fieldList(
				operationalFields(
					"apiSessionTimeout",
					"blockConnectHostSniMismatch",
					"blockDomainFrontingOnHostHeader",
					"blockHttpTunnelOnNonHttpPorts",
					"blockNonCompliantHttpRequestOnHttpPorts",
					"blockNonHttpOnHttpPortEnabled",
					"cascadeUrlFiltering",
					"dynamicUserRiskEnabled",
					"ecsForAllEnabled",
					"enableAdminRankAccess",
					"enableDnsResolutionOnTransparentProxy",
					"enableEvaluatePolicyOnGlobalSSLBypass",
					"enableIPv6DnsOptimizationOnAllTransparentProxy",
					"enableIPv6DnsResolutionOnTransparentProxy",
					"enableOffice365",
					"enablePolicyForUnauthenticatedTraffic",
					"enforceSurrogateIpForWindowsApp",
					"http2NonbrowserTrafficEnabled",
					"logInternalIp",
					"preferSniOverConnHost",
					"sipaXffHeaderEnabled",
					"trackHttpTunnelOnHttpPorts",
					"uiSessionTimeout",
					"zscalerClientConnector1AndPacRoadWarriorInFirewall",
				),
				sensitiveIdentifierFields(
					"authBypassApps",
					"authBypassUrlCategories",
					"authBypassUrls",
					"basicBypassApps",
					"basicBypassUrlCategories",
					"blockDomainFrontingApps",
					"digestAuthBypassApps",
					"digestAuthBypassUrlCategories",
					"digestAuthBypassUrls",
					"dnsResolutionOnTransparentProxyApps",
					"dnsResolutionOnTransparentProxyExemptApps",
					"dnsResolutionOnTransparentProxyExemptUrlCategories",
					"dnsResolutionOnTransparentProxyExemptUrls",
					"dnsResolutionOnTransparentProxyIPv6Apps",
					"dnsResolutionOnTransparentProxyIPv6ExemptApps",
					"dnsResolutionOnTransparentProxyIPv6ExemptUrlCategories",
					"dnsResolutionOnTransparentProxyIPv6UrlCategories",
					"dnsResolutionOnTransparentProxyUrlCategories",
					"dnsResolutionOnTransparentProxyUrls",
					"domainFrontingBypassUrlCategories",
					"httpRangeHeaderRemoveUrlCategories",
					"kerberosBypassApps",
					"kerberosBypassUrlCategories",
					"kerberosBypassUrls",
					"preferSniOverConnHostApps",
					"sniDnsOptimizationBypassUrlCategories",
				),
				secretFields("ecsObject"),
			),
		},
		{
			Product:    ProductZIA,
			Name:       "advanced-threat-settings",
			Operations: ShowOperation(),
			Fields: fieldList(
				operationalFields(
					"activeXBlocked",
					"activeXCapture",
					"adSpywareSitesBlocked",
					"adSpywareSitesCapture",
					"alertForUnknownOrSuspiciousC2Traffic",
					"anonymizerBlocked",
					"anonymizerCapture",
					"bitTorrentBlocked",
					"bitTorrentCapture",
					"blockCountriesCapture",
					"browserExploitsBlocked",
					"browserExploitsCapture",
					"cmdCtlServerBlocked",
					"cmdCtlServerCapture",
					"cmdCtlTrafficBlocked",
					"cmdCtlTrafficCapture",
					"cryptoMiningBlocked",
					"cryptoMiningCapture",
					"dgaDomainsBlocked",
					"dgaDomainsCapture",
					"fileFormatVunerabilitesBlocked",
					"fileFormatVunerabilitesCapture",
					"googleTalkBlocked",
					"googleTalkCapture",
					"ircTunnellingBlocked",
					"ircTunnellingCapture",
					"knownPhishingSitesBlocked",
					"knownPhishingSitesCapture",
					"maliciousUrlsCapture",
					"malwareSitesBlocked",
					"malwareSitesCapture",
					"potentialMaliciousRequestsBlocked",
					"potentialMaliciousRequestsCapture",
					"riskTolerance",
					"riskToleranceCapture",
					"sshTunnellingBlocked",
					"sshTunnellingCapture",
					"suspectAdwareSpywareSitesBlocked",
					"suspectAdwareSpywareSitesCapture",
					"suspectedPhishingSitesBlocked",
					"suspectedPhishingSitesCapture",
					"torBlocked",
					"torCapture",
					"webspamBlocked",
					"webspamCapture",
				),
				[]FieldSpec{
					operationalControlField("cookieStealingBlocked", "boolean security control; field name describes cookie-theft protection, not cookie material"),
					operationalControlField("cookieStealingPCAPEnabled", "boolean security control; field name describes packet capture for cookie-theft protection, not cookie material"),
				},
				sensitiveIdentifierFields("blockedCountries"),
			),
		},
		{
			Product:    ProductZIA,
			Name:       "mobile-threat-settings",
			Operations: ShowOperation(),
			Fields: fieldList(
				operationalFields(
					"blockAppsCommunicatingWithAdWebsites",
					"blockAppsCommunicatingWithRemoteUnknownServers",
					"blockAppsSendingDeviceIdentifier",
					"blockAppsSendingLocationInfo",
					"blockAppsSendingPersonallyIdentifiableInfo",
					"blockAppsWithKnownVulnerabilities",
					"blockAppsWithMaliciousActivity",
				),
				[]FieldSpec{
					operationalControlField("blockAppsSendingUnencryptedUserCredentials", "boolean security control; field name describes credential-exfiltration blocking, not credential material"),
				},
			),
		},
		{
			Product:    ProductZIA,
			Name:       "sandbox-settings",
			Operations: ShowOperation(),
			Fields: fieldList(
				sensitiveIdentifierFields("fileHashesToBeBlocked"),
			),
		},
		{
			Product:    ProductZIA,
			Name:       "end-user-notification-settings",
			Operations: ShowOperation(),
			Fields: fieldList(
				operationalFields(
					"aupCustomFrequency",
					"aupDayOffset",
					"aupFrequency",
					"cautionAgainAfter",
					"cautionPerDomain",
					"displayCompLogo",
					"displayReason",
					"notificationType",
					"securityReviewEnabled",
					"securityReviewSubmitToSecurityCloud",
					"urlCatReviewEnabled",
					"urlCatReviewSubmitToSecurityCloud",
					"webDlpReviewEnabled",
					"webDlpReviewSubmitToSecurityCloud",
				),
				tenantConfigFields("displayCompName"),
				sensitiveIdentifierFields(
					"redirectUrl",
					"securityReviewCustomLocation",
					"supportEmail",
					"supportPhone",
					"urlCatReviewCustomLocation",
					"webDlpReviewCustomLocation",
				),
				secretFields(
					"aupMessage",
					"cautionCustomText",
					"customText",
					"idpProxyNotificationText",
					"orgPolicyLink",
					"quarantineCustomNotificationText",
					"securityReviewText",
					"urlCatReviewText",
					"webDlpReviewText",
				),
			),
		},
		{
			Product:    ProductZIA,
			Name:       "org-information",
			Operations: ShowOperation(),
			Fields: fieldList(
				operationalFields(
					"alertTimer",
					"customerContactInherit",
					"employeeCount",
					"externalEmailPortal",
					"internalCompany",
					"language",
					"legacyInsightsReportWasEnabled",
					"logoMimeType",
					"timezone",
				),
				tenantConfigFields("cloudName", "name"),
				sensitiveIdentifierFields(
					"addrLine1",
					"addrLine2",
					"city",
					"country",
					"domains",
					"geoLocation",
					"hqLocation",
					"orgId",
					"pdomain",
					"state",
					"zipcode",
					"zpaTenantCloud",
					"zpaTenantId",
				),
				secretFields(
					"execInsightsHref",
					"industryVertical",
					"logoBase64Data",
					"primaryBillingContactAltPhone",
					"primaryBillingContactEmail",
					"primaryBillingContactInsightsHref",
					"primaryBillingContactName",
					"primaryBillingContactPhone",
					"primaryBillingContactTitle",
					"primaryBillingContactcontactType",
					"primaryBusinessContactAltPhone",
					"primaryBusinessContactEmail",
					"primaryBusinessContactInsightsHref",
					"primaryBusinessContactName",
					"primaryBusinessContactPhone",
					"primaryBusinessContactTitle",
					"primaryBusinessContactcontactType",
					"primaryTechnicalContactAltPhone",
					"primaryTechnicalContactEmail",
					"primaryTechnicalContactInsightsHref",
					"primaryTechnicalContactName",
					"primaryTechnicalContactPhone",
					"primaryTechnicalContactTitle",
					"primaryTechnicalContactcontactType",
					"secondaryBillingContactAltPhone",
					"secondaryBillingContactEmail",
					"secondaryBillingContactInsightsHref",
					"secondaryBillingContactName",
					"secondaryBillingContactPhone",
					"secondaryBillingContactTitle",
					"secondaryBillingContactcontactType",
					"secondaryBusinessContactAltPhone",
					"secondaryBusinessContactEmail",
					"secondaryBusinessContactInsightsHref",
					"secondaryBusinessContactName",
					"secondaryBusinessContactPhone",
					"secondaryBusinessContactTitle",
					"secondaryBusinessContactcontactType",
					"secondaryTechnicalContactAltPhone",
					"secondaryTechnicalContactEmail",
					"secondaryTechnicalContactInsightsHref",
					"secondaryTechnicalContactName",
					"secondaryTechnicalContactPhone",
					"secondaryTechnicalContactTitle",
					"secondaryTechnicalContactcontactType",
				),
			),
		},
		{
			Product:    ProductZIA,
			Name:       "atp-malware-policy",
			Operations: ShowOperation(),
			Fields: fieldList(
				[]FieldSpec{
					operationalControlField("blockPasswordProtectedArchiveFiles", "boolean security control; field name describes password-protected archive handling, not password material"),
				},
				operationalFields("blockUnscannableFiles"),
			),
		},
		{
			Product:    ProductZIA,
			Name:       "atp-malware-settings",
			Operations: ShowOperation(),
			Fields: fieldList(
				operationalFields(
					"adwareBlocked",
					"adwareCapture",
					"ransomwareBlocked",
					"ransomwareCapture",
					"remoteAccessToolBlocked",
					"remoteAccessToolCapture",
					"spywareBlocked",
					"spywareCapture",
					"trojanBlocked",
					"trojanCapture",
					"unwantedApplicationsBlocked",
					"unwantedApplicationsCapture",
					"virusBlocked",
					"virusCapture",
					"wormBlocked",
					"wormCapture",
				),
			),
		},
		{
			Product:    ProductZIA,
			Name:       "atp-malware-inspection",
			Operations: ShowOperation(),
			Fields: fieldList(
				operationalFields("inspectInbound", "inspectOutbound"),
			),
		},
		{
			Product:    ProductZIA,
			Name:       "atp-malware-protocols",
			Operations: ShowOperation(),
			Fields: fieldList(
				operationalFields("inspectFtp", "inspectFtpOverHttp", "inspectHttp"),
			),
		},
		{
			Product:    ProductZIA,
			Name:       "malicious-urls",
			Operations: ShowOperation(),
			Fields: fieldList(
				sensitiveIdentifierFields("maliciousUrls"),
			),
		},
		{
			Product:    ProductZIA,
			Name:       "security-exceptions",
			Operations: ShowOperation(),
			Fields: fieldList(
				sensitiveIdentifierFields("bypassUrls"),
			),
		},
		{
			Product:    ProductZIA,
			Name:       "url-allow-list",
			Operations: ShowOperation(),
			Fields: fieldList(
				// The SDK shape carries both URL lists; each resource renders only its own list.
				sensitiveIdentifierFields("whitelistUrls"),
				secretFields("blacklistUrls"),
			),
		},
		{
			Product:    ProductZIA,
			Name:       "url-deny-list",
			Operations: ShowOperation(),
			Fields: fieldList(
				// The SDK shape carries both URL lists; each resource renders only its own list.
				sensitiveIdentifierFields("blacklistUrls"),
				secretFields("whitelistUrls"),
			),
		},
	}
}
