package resources

func catalogZTW() ResourceCatalog {
	return ResourceCatalog{
		{
			Product:    ProductZTW,
			Name:       "workload-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZTW workload group description"),
				secretField("expression"),
				operationalField("lastModifiedTime", standardShareModes()),
				secretField("lastModifiedBy"),
				secretField("expressionJson"),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "public-cloud-accounts",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				sensitiveIdentifierField("accountId"),
				operationalField("platformId", allModes()),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "dns-gateways",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("dnsGatewayType", allModes()),
				secretField("ecDnsGatewayOptionsPrimary"),
				secretField("ecDnsGatewayOptionsSecondary"),
				tenantConfigField("failureBehavior", standardShareModes()),
				sensitiveIdentifierField("primaryIp"),
				sensitiveIdentifierField("secondaryIp"),
				operationalField("lastModifiedTime", standardShareModes()),
				secretField("lastModifiedBy"),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "forwarding-gateways",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZTW forwarding gateway description"),
				operationalField("failClosed", allModes()),
				sensitiveIdentifierField("manualPrimary"),
				sensitiveIdentifierField("manualSecondary"),
				idNameExternalIDField("subcloudPrimary", standardOnlyMode()),
				idNameExternalIDField("subcloudSecondary", standardOnlyMode()),
				operationalField("primaryType", allModes()),
				operationalField("secondaryType", allModes()),
				operationalField("type", allModes()),
				tenantConfigField("failureBehavior", standardShareModes()),
				operationalField("dnsGatewayType", allModes()),
				sensitiveIdentifierField("primaryIp"),
				sensitiveIdentifierField("secondaryIp"),
				secretField("ecDnsGatewayOptionsPrimary"),
				secretField("ecDnsGatewayOptionsSecondary"),
				secretField("lastModifiedBy"),
				operationalField("lastModifiedTime", standardShareModes()),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "ec-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("desc", "ZTW EC group description"),
				operationalField("deployType", allModes()),
				operationalField("status", allModes()),
				operationalField("platform", allModes()),
				sensitiveIdentifierField("awsAvailabilityZone"),
				sensitiveIdentifierField("azureAvailabilityZone"),
				operationalField("maxEcCount", allModes()),
				tenantConfigField("tunnelMode", standardShareModes()),
				idNameExternalIDField("location", standardOnlyMode()),
				idNameExternalIDField("provTemplate", standardOnlyMode()),
				secretField("ecVMs"),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "ip-source-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZTW IP source group description"),
				sensitiveIdentifierField("ipAddresses"),
				operationalField("creatorContext", allModes()),
				operationalField("isNonEditable", allModes()),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "ip-destination-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZTW IP destination group description"),
				operationalField("type", allModes()),
				sensitiveIdentifierField("addresses"),
				sensitiveIdentifierField("ipCategories"),
				operationalField("countries", standardShareModes()),
				operationalField("isNonEditable", allModes()),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "ip-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZTW IP group description"),
				sensitiveIdentifierField("ipAddresses"),
				operationalField("creatorContext", allModes()),
				operationalField("isNonEditable", allModes()),
				operationalField("extranetIpPool", allModes()),
				operationalField("isPredefined", allModes()),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "network-services",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZTW network service description"),
				tenantConfigField("tag", standardShareModes()),
				networkPortsField("srcTcpPorts", standardShareModes()),
				networkPortsField("destTcpPorts", standardShareModes()),
				networkPortsField("srcUdpPorts", standardShareModes()),
				networkPortsField("destUdpPorts", standardShareModes()),
				operationalField("type", allModes()),
				operationalField("isNameL10nTag", allModes()),
				operationalField("creatorContext", allModes()),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "network-service-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				idNameField("services", standardOnlyMode()),
				freeTextField("description", "ZTW network service group description"),
				operationalField("creatorContext", allModes()),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "admin-users",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				sensitiveIdentifierField("loginName"),
				sensitiveIdentifierField("userName"),
				sensitiveIdentifierField("email"),
				freeTextField("comments", "ZTW admin user comments"),
				operationalField("disabled", allModes()),
				secretField("password"),
				operationalField("pwdLastModifiedTime", standardOnlyMode()),
				operationalField("isNonEditable", allModes()),
				secretField("isPasswordLoginAllowed"),
				secretField("isPasswordExpired"),
				operationalField("isAuditor", allModes()),
				tenantConfigField("isSecurityReportCommEnabled", standardShareModes()),
				tenantConfigField("isServiceUpdateCommEnabled", standardShareModes()),
				tenantConfigField("isProductUpdateCommEnabled", standardShareModes()),
				tenantConfigField("isExecMobileAppEnabled", standardShareModes()),
				idNameExtensionsField("adminScopescopeGroupMemberEntities", standardOnlyMode()),
				idNameExtensionsField("adminScopeScopeEntities", standardOnlyMode()),
				tenantConfigField("adminScopeType", standardShareModes()),
				{
					Name:           "role",
					Classification: ClassTenantConfig,
					AllowedModes:   standardOnlyMode(),
					Fields: []FieldSpec{
						operationalField("id", allModes()),
						tenantConfigField("name", standardShareModes()),
						operationalField("isNameL10nTag", allModes()),
						secretField("extensions"),
					},
				},
				secretField("execMobileAppTokens"),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "admin-roles",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				operationalField("rank", standardOnlyMode()),
				tenantConfigField("name", standardShareModes()),
				tenantConfigField("policyAccess", standardOnlyMode()),
				tenantConfigField("alertingAccess", standardOnlyMode()),
				tenantConfigField("dashboardAccess", standardOnlyMode()),
				tenantConfigField("reportAccess", standardOnlyMode()),
				tenantConfigField("analysisAccess", standardOnlyMode()),
				tenantConfigField("usernameAccess", standardOnlyMode()),
				tenantConfigField("adminAcctAccess", standardOnlyMode()),
				tenantConfigField("deviceInfoAccess", standardOnlyMode()),
				operationalField("isAuditor", allModes()),
				tenantConfigField("permissions", standardOnlyMode()),
				operationalField("isNonEditable", allModes()),
				tenantConfigField("logsLimit", standardOnlyMode()),
				tenantConfigField("roleType", standardShareModes()),
				secretField("featurePermissions"),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "locations",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("parentId", standardOnlyMode()),
				tenantConfigField("enforceBandwidthControl", standardOnlyMode()),
				operationalField("upBandwidth", standardOnlyMode()),
				operationalField("dnBandwidth", standardOnlyMode()),
				operationalField("overrideUpBandwidth", standardOnlyMode()),
				operationalField("overrideDnBandwidth", standardOnlyMode()),
				operationalField("sharedUpBandwidth", standardOnlyMode()),
				operationalField("sharedDownBandwidth", standardOnlyMode()),
				operationalField("unusedUpBandwidth", standardOnlyMode()),
				tenantConfigField("country", standardOnlyMode()),
				tenantConfigField("state", standardOnlyMode()),
				tenantConfigField("language", standardOnlyMode()),
				tenantConfigField("tz", standardOnlyMode()),
				sensitiveIdentifierField("ipAddresses"),
				tenantConfigField("ports", standardOnlyMode()),
				tenantConfigField("authRequired", standardOnlyMode()),
				tenantConfigField("sslScanEnabled", standardOnlyMode()),
				tenantConfigField("zappSSLScanEnabled", standardOnlyMode()),
				tenantConfigField("xffForwardEnabled", standardOnlyMode()),
				operationalField("otherSubLocation", standardOnlyMode()),
				operationalField("other6SubLocation", standardOnlyMode()),
				tenantConfigField("ecLocation", standardOnlyMode()),
				tenantConfigField("surrogateIP", standardOnlyMode()),
				operationalField("idleTimeInMinutes", standardOnlyMode()),
				operationalField("displayTimeUnit", standardOnlyMode()),
				tenantConfigField("surrogateIPEnforcedForKnownBrowsers", standardOnlyMode()),
				operationalField("surrogateRefreshTimeInMinutes", standardOnlyMode()),
				operationalField("surrogateRefreshTimeUnit", standardOnlyMode()),
				tenantConfigField("ofwEnabled", standardOnlyMode()),
				tenantConfigField("ipsControl", standardOnlyMode()),
				tenantConfigField("aupEnabled", standardOnlyMode()),
				tenantConfigField("cautionEnabled", standardOnlyMode()),
				tenantConfigField("aupBlockInternetUntilAccepted", standardOnlyMode()),
				tenantConfigField("aupForceSslInspection", standardOnlyMode()),
				operationalField("aupTimeoutInDays", standardOnlyMode()),
				tenantConfigField("profile", standardOnlyMode()),
				freeTextField("description", "ZTW location description"),
				tenantConfigField("ipv6Enabled", standardOnlyMode()),
				tenantConfigField("ipv6Dns64Prefix", standardOnlyMode()),
				tenantConfigField("kerberosAuth", standardOnlyMode()),
				tenantConfigField("digestAuthEnabled", standardOnlyMode()),
				operationalField("childCount", standardOnlyMode()),
				tenantConfigField("matchInChild", standardOnlyMode()),
				tenantConfigField("excludeFromDynamicGroups", standardOnlyMode()),
				tenantConfigField("excludeFromManualGroups", standardOnlyMode()),
				secretField("vpnCredentials"),
				idNameExternalIDField("virtualZens", standardOnlyMode()),
				idNameExternalIDField("virtualZenClusters", standardOnlyMode()),
				idNameExternalIDField("staticLocationGroups", standardOnlyMode()),
				idNameExternalIDField("dynamiclocationGroups", standardOnlyMode()),
				idNameField("publicCloudAccountId", standardOnlyMode()),
				secretField("vpcInfo"),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "location-templates",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("desc", "ZTW location template description"),
				{
					Name:           "template",
					Classification: ClassTenantConfig,
					AllowedModes:   standardOnlyMode(),
					Fields: []FieldSpec{
						tenantConfigField("templatePrefix", standardOnlyMode()),
						tenantConfigField("xffForwardEnabled", standardOnlyMode()),
						tenantConfigField("authRequired", standardOnlyMode()),
						tenantConfigField("cautionEnabled", standardOnlyMode()),
						tenantConfigField("aupEnabled", standardOnlyMode()),
						operationalField("aupTimeoutInDays", standardOnlyMode()),
						tenantConfigField("ofwEnabled", standardOnlyMode()),
						tenantConfigField("ipsControl", standardOnlyMode()),
						tenantConfigField("enforceBandwidthControl", standardOnlyMode()),
						operationalField("upBandwidth", standardOnlyMode()),
						operationalField("dnBandwidth", standardOnlyMode()),
						operationalField("displayTimeUnit", standardOnlyMode()),
						operationalField("idleTimeInMinutes", standardOnlyMode()),
						tenantConfigField("surrogateIPEnforcedForKnownBrowsers", standardOnlyMode()),
						operationalField("surrogateRefreshTimeUnit", standardOnlyMode()),
						operationalField("surrogateRefreshTimeInMinutes", standardOnlyMode()),
						tenantConfigField("surrogateIP", standardOnlyMode()),
						operationalField("editable", standardOnlyMode()),
						secretField("lastModUid"),
					},
				},
				operationalField("editable", allModes()),
				operationalField("lastModTime", standardShareModes()),
				secretField("lastModUid"),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "account-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZTW account group description"),
				tenantConfigField("cloudType", standardShareModes()),
				idNameExtensionsField("publicCloudAccounts", standardOnlyMode()),
				idNameExtensionsField("cloudConnectorGroups", standardOnlyMode()),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "public-cloud-info",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				sensitiveIdentifierField("name"),
				tenantConfigField("cloudType", standardShareModes()),
				secretField("externalId"),
				operationalField("lastModTime", standardShareModes()),
				operationalField("lastSyncTime", standardShareModes()),
				idNameExtensionsField("accountGroups", standardOnlyMode()),
				secretField("lastModUser"),
				{
					Name:           "regionStatus",
					Classification: ClassTenantConfig,
					AllowedModes:   standardOnlyMode(),
					Fields: []FieldSpec{
						operationalField("id", allModes()),
						tenantConfigField("name", standardShareModes()),
						tenantConfigField("cloudType", standardShareModes()),
						operationalField("status", allModes()),
					},
				},
				{
					Name:           "supportedRegions",
					Classification: ClassTenantConfig,
					AllowedModes:   standardOnlyMode(),
					Fields: []FieldSpec{
						operationalField("id", allModes()),
						tenantConfigField("name", standardShareModes()),
						tenantConfigField("cloudType", standardShareModes()),
					},
				},
				secretField("accountDetails"),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "zpa-application-segments",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZTW ZPA application segment description"),
				sensitiveIdentifierField("zpaId"),
				operationalField("deleted", allModes()),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "forwarding-rules",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("accessControl", standardShareModes()),
				freeTextField("description", "ZTW forwarding rule description"),
				operationalField("type", allModes()),
				operationalField("order", allModes()),
				operationalField("rank", allModes()),
				tenantConfigField("forwardMethod", standardShareModes()),
				operationalField("defaultRule", allModes()),
				tenantConfigField("wanSelection", standardShareModes()),
				operationalField("state", allModes()),
				tenantConfigField("blockResponseCode", standardShareModes()),
				operationalField("lastModifiedTime", standardShareModes()),
				sensitiveIdentifierField("srcIps"),
				sensitiveIdentifierField("destAddresses"),
				sensitiveIdentifierField("destIpCategories"),
				sensitiveIdentifierField("resCategories"),
				operationalField("destCountries", standardShareModes()),
				operationalField("sourceCountries", standardShareModes()),
				tenantConfigField("nwApplications", standardShareModes()),
				operationalField("sourceIpGroupExclusion", allModes()),
				operationalField("zpaBrokerRule", allModes()),
				idNameExtensionsField("locations", standardOnlyMode()),
				idNameExtensionsField("locationGroups", standardOnlyMode()),
				idNameExtensionsField("ecGroups", standardOnlyMode()),
				idNameExtensionsField("departments", standardOnlyMode()),
				idNameExtensionsField("groups", standardOnlyMode()),
				idNameExtensionsField("users", standardOnlyMode()),
				secretField("lastModifiedBy"),
				idNameExtensionsField("srcIpGroups", standardOnlyMode()),
				idNameExtensionsField("srcIpv6Groups", standardOnlyMode()),
				idNameExtensionsField("destIpGroups", standardOnlyMode()),
				idNameExtensionsField("destIpv6Groups", standardOnlyMode()),
				idNameExtensionsField("nwServices", standardOnlyMode()),
				idNameExtensionsField("nwServiceGroups", standardOnlyMode()),
				idNameExtensionsField("labels", standardShareModes()),
				idNameExtensionsField("nwApplicationGroups", standardOnlyMode()),
				idNameExtensionsField("appServiceGroups", standardOnlyMode()),
				idNameExtensionsField("srcWorkloadGroups", standardOnlyMode()),
				idNameField("proxyGateway", standardOnlyMode()),
				{
					Name:           "zpaApplicationSegments",
					Classification: ClassTenantConfig,
					AllowedModes:   standardOnlyMode(),
					Fields: []FieldSpec{
						operationalField("id", allModes()),
						tenantConfigField("name", standardShareModes()),
						freeTextField("description", "ZTW forwarding rule ZPA application segment description"),
						sensitiveIdentifierField("zpaId"),
						operationalField("deleted", allModes()),
					},
				},
				{
					Name:           "zpaApplicationSegmentGroups",
					Classification: ClassTenantConfig,
					AllowedModes:   standardOnlyMode(),
					Fields: []FieldSpec{
						operationalField("id", allModes()),
						tenantConfigField("name", standardShareModes()),
						sensitiveIdentifierField("zpaId"),
						operationalField("deleted", allModes()),
						operationalField("zpaAppSegmentsCount", standardOnlyMode()),
					},
				},
			},
		},
		{
			Product:    ProductZTW,
			Name:       "traffic-dns-rules",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZTW traffic DNS rule description"),
				operationalField("type", allModes()),
				tenantConfigField("action", standardShareModes()),
				operationalField("order", allModes()),
				operationalField("rank", allModes()),
				operationalField("state", allModes()),
				operationalField("predefined", allModes()),
				operationalField("defaultRule", allModes()),
				sensitiveIdentifierField("srcIps"),
				sensitiveIdentifierField("destAddresses"),
				idNameExtensionsField("locations", standardOnlyMode()),
				idNameExtensionsField("locationGroups", standardOnlyMode()),
				idNameExtensionsField("ecGroups", standardOnlyMode()),
				idNameExtensionsField("srcIpGroups", standardOnlyMode()),
				idNameExtensionsField("destIpGroups", standardOnlyMode()),
				idNameField("dnsGateway", standardOnlyMode()),
				idNameField("zpaIpGroup", standardOnlyMode()),
				operationalField("lastModifiedTime", standardShareModes()),
				secretField("lastModifiedBy"),
			},
		},
		{
			Product:    ProductZTW,
			Name:       "traffic-log-rules",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZTW traffic log rule description"),
				operationalField("order", allModes()),
				operationalField("rank", allModes()),
				operationalField("state", allModes()),
				operationalField("type", allModes()),
				tenantConfigField("forwardMethod", standardShareModes()),
				operationalField("defaultRule", allModes()),
				idNameExtensionsField("locations", standardOnlyMode()),
				idNameField("proxyGateway", standardOnlyMode()),
				operationalField("lastModifiedTime", standardShareModes()),
				secretField("lastModifiedBy"),
				idNameExtensionsField("ecGroups", standardOnlyMode()),
			},
		},
	}
}
