package resources

func catalogZCC() ResourceCatalog {
	return ResourceCatalog{
		{
			Product:    ProductZCC,
			Name:       "fail-open-policy",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				operationalField("active", allModes()),
				operationalField("enableFailOpen", allModes()),
				operationalField("enableCaptivePortalDetection", allModes()),
				operationalField("captivePortalWebSecDisableMinutes", allModes()),
				operationalField("enableStrictEnforcementPrompt", allModes()),
				operationalField("strictEnforcementPromptDelayMinutes", allModes()),
				freeTextField("strictEnforcementPromptMessage", "ZCC fail-open strict enforcement prompt message"),
				operationalField("enableWebSecOnProxyUnreachable", allModes()),
				operationalField("enableWebSecOnTunnelFailure", allModes()),
				operationalField("tunnelFailureRetryCount", allModes()),
				secretField("createdBy"),
				secretField("editedBy"),
				secretField("companyId"),
			},
		},
		{
			Product:    ProductZCC,
			Name:       "forwarding-profiles",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("active", allModes()),
				operationalField("conditionType", allModes()),
				operationalField("enableLWFDriver", allModes()),
				operationalField("predefinedTnAll", allModes()),
				operationalField("enableUnifiedTunnel", allModes()),
				operationalField("enableAllDefaultAdaptersTN", allModes()),
				operationalField("enableSplitVpnTN", allModes()),
				operationalField("evaluateTrustedNetwork", allModes()),
				operationalField("skipTrustedCriteriaMatch", allModes()),
				sensitiveIdentifierField("dnsServers"),
				sensitiveIdentifierField("dnsSearchDomains"),
				sensitiveIdentifierField("hostname"),
				sensitiveIdentifierField("resolvedIpsForHostname"),
				sensitiveIdentifierField("trustedSubnets"),
				sensitiveIdentifierField("trustedGateways"),
				sensitiveIdentifierField("trustedDhcpServers"),
				sensitiveIdentifierField("trustedEgressIps"),
				secretField("predefinedTrustedNetworks"),
				secretField("forwardingProfileActions"),
				secretField("forwardingProfileZpaActions"),
				secretField("unifiedTunnel"),
				secretField("trustedNetworkIds"),
				secretField("trustedNetworks"),
				secretField("trustedNetworkIdsSelected"),
			},
		},
		{
			Product:    ProductZCC,
			Name:       "trusted-networks",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				operationalField("active", allModes()),
				operationalField("conditionType", allModes()),
				tenantConfigField("networkName", standardShareModes()),
				sensitiveIdentifierField("dnsSearchDomains"),
				sensitiveIdentifierField("dnsServers"),
				sensitiveIdentifierField("hostnames"),
				sensitiveIdentifierField("resolvedIpsForHostname"),
				sensitiveIdentifierField("ssids"),
				sensitiveIdentifierField("trustedDhcpServers"),
				sensitiveIdentifierField("trustedEgressIps"),
				sensitiveIdentifierField("trustedGateways"),
				sensitiveIdentifierField("trustedSubnets"),
				secretField("guid"),
				secretField("companyId"),
				secretField("createdBy"),
				secretField("editedBy"),
			},
		},
		{
			Product:    ProductZCC,
			Name:       "web-app-services",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("appName", standardShareModes()),
				operationalField("active", allModes()),
				operationalField("appVersion", allModes()),
				operationalField("appSvcId", allModes()),
				operationalField("version", allModes()),
				operationalField("editedTimestamp", allModes()),
				secretField("uid"),
				secretField("appDataBlob"),
				secretField("appDataBlobV6"),
				secretField("zappDataBlob"),
				secretField("zappDataBlobV6"),
				secretField("createdBy"),
				secretField("editedBy"),
			},
		},
		{
			Product:    ProductZCC,
			Name:       "application-profiles",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZCC application profile description"),
				operationalField("deviceType", allModes()),
				sensitiveIdentifierField("pac_url"),
				operationalField("active", allModes()),
				operationalField("ruleOrder", allModes()),
				operationalField("logMode", allModes()),
				operationalField("logLevel", allModes()),
				operationalField("logFileSize", allModes()),
				operationalField("reauth_period", allModes()),
				operationalField("reactivateWebSecurityMinutes", allModes()),
				operationalField("highlightActiveControl", allModes()),
				operationalField("sendDisableServiceReason", allModes()),
				operationalControlField("refreshKerberosToken", "boolean flag controlling Kerberos token refresh, not a token value"),
				operationalField("enableDeviceGroups", allModes()),
				operationalField("onNetPolicy", allModes()),
				operationalField("notificationTemplateId", allModes()),
				operationalField("forwardingProfileId", allModes()),
				operationalField("ziaPostureConfigId", allModes()),
				operationalField("tunnelZappTraffic", allModes()),
				operationalField("groupAll", allModes()),
				operationalField("showVPNTunNotification", allModes()),
				operationalField("useTunnelSDK4_3", allModes()),
				operationalField("ipv6Mode", allModes()),
				secretField("passcode"),
				secretField("logout_password"),
				secretField("disable_password"),
				secretField("uninstall_password"),
				secretField("policyToken"),
				secretField("groups"),
				secretField("deviceGroups"),
				secretField("users"),
				secretField("notificationTemplateContract"),
				secretField("policyExtension"),
				secretField("disasterRecovery"),
				secretField("ziaPostureConfig"),
				secretField("groupIds"),
				secretField("deviceGroupIds"),
				secretField("userIds"),
				secretField("bypassAppIds"),
				secretField("appServiceIds"),
				secretField("bypassCustomAppIds"),
				secretField("bypassApps"),
				secretField("bypassCustomApps"),
				secretField("appServices"),
			},
		},
		{
			Product:    ProductZCC,
			Name:       "custom-ip-apps",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("appName", standardShareModes()),
				operationalField("active", allModes()),
				secretField("uid"),
				secretField("appDataBlob"),
				secretField("appDataBlobV6"),
				secretField("zappDataBlob"),
				secretField("zappDataBlobV6"),
				secretField("createdBy"),
				secretField("editedBy"),
				operationalField("editedTimestamp", allModes()),
			},
		},
		{
			Product:    ProductZCC,
			Name:       "predefined-ip-apps",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("appName", standardShareModes()),
				operationalField("active", allModes()),
				operationalField("appVersion", allModes()),
				operationalField("appSvcId", allModes()),
				secretField("uid"),
				secretField("appDataBlob"),
				secretField("appDataBlobV6"),
				secretField("zappDataBlob"),
				secretField("zappDataBlobV6"),
				secretField("createdBy"),
				secretField("editedBy"),
				operationalField("editedTimestamp", allModes()),
			},
		},
		{
			Product:    ProductZCC,
			Name:       "process-based-apps",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("appName", standardShareModes()),
				operationalField("matchingCriteria", allModes()),
				sensitiveIdentifierField("fileNames"),
				sensitiveIdentifierField("filePaths"),
				secretField("signaturePayload"),
				secretField("certificatePayload"),
				secretField("createdBy"),
				secretField("editedBy"),
				operationalField("editedTimestamp", allModes()),
			},
		},
		{
			Product:    ProductZCC,
			Name:       "devices",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("agentVersion", allModes()),
				operationalField("config_download_time", allModes()),
				operationalField("deregistrationTimestamp", allModes()),
				operationalField("download_count", allModes()),
				operationalField("keepAliveTime", allModes()),
				operationalField("last_seen_time", allModes()),
				operationalField("osVersion", allModes()),
				operationalField("policyName", allModes()),
				operationalField("registrationState", allModes()),
				operationalField("registration_time", allModes()),
				operationalField("state", allModes()),
				operationalField("tunnelVersion", allModes()),
				operationalField("type", allModes()),
				operationalField("upmVersion", allModes()),
				operationalField("vpnState", allModes()),
				operationalField("zappArch", allModes()),
				operationalField("manufacturer", allModes()),
				sensitiveIdentifierField("companyName"),
				sensitiveIdentifierField("machineHostname"),
				sensitiveIdentifierField("macAddress"),
				sensitiveIdentifierField("owner"),
				sensitiveIdentifierField("user"),
				sensitiveIdentifierField("udid"),
				secretField("hardwareFingerprint"),
				secretField("detail"),
			},
		},
		{
			Product:    ProductZCC,
			Name:       "admin-roles",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("roleName", standardShareModes()),
				operationalField("isEditable", allModes()),
				operationalField("adminManagement", allModes()),
				operationalField("administratorGroup", allModes()),
				operationalField("androidProfile", allModes()),
				operationalField("appBypass", allModes()),
				operationalField("appProfileGroup", allModes()),
				operationalField("auditLogs", allModes()),
				operationalField("authSetting", allModes()),
				operationalField("clientConnectorAppStore", allModes()),
				operationalField("clientConnectorIdp", allModes()),
				operationalField("clientConnectorNotifications", allModes()),
				operationalField("clientConnectorSupport", allModes()),
				operationalField("dashboard", allModes()),
				operationalField("ddilConfiguration", allModes()),
				operationalField("dedicatedProxyPorts", allModes()),
				operationalField("deviceGroups", allModes()),
				operationalField("deviceOverview", allModes()),
				operationalField("devicePosture", allModes()),
				operationalField("enrolledDevicesGroup", allModes()),
				operationalField("forwardingProfile", allModes()),
				operationalField("iosProfile", allModes()),
				operationalField("linuxProfile", allModes()),
				operationalField("macProfile", allModes()),
				operationalField("machineTunnel", allModes()),
				operationalField("obfuscateData", allModes()),
				operationalField("partnerDeviceOverview", allModes()),
				operationalField("publicApi", allModes()),
				operationalField("trustedNetwork", allModes()),
				operationalField("userAgent", allModes()),
				operationalField("windowsProfile", allModes()),
				operationalField("zpaPartnerLogin", allModes()),
				operationalField("zscalerDeception", allModes()),
				operationalField("zscalerEntitlement", allModes()),
				secretField("companyId"),
				secretField("createdBy"),
				secretField("updatedBy"),
			},
		},
		{
			Product:    ProductZCC,
			Name:       "company-info",
			Operations: ShowOperation(),
			Fields: []FieldSpec{
				secretField("orgId"),
				secretField("masterCustomerId"),
				tenantConfigField("name", standardShareModes()),
				tenantConfigField("businessName", standardShareModes()),
				sensitiveIdentifierField("businessContactNumber"),
				sensitiveIdentifierField("activationRecipient"),
				operationalField("activationCopy", allModes()),
				operationalField("mdmStatus", allModes()),
				operationalField("sendEmail", allModes()),
				operationalField("proxyEnabled", allModes()),
				operationalField("zpnEnabled", allModes()),
				operationalField("upmEnabled", allModes()),
				operationalField("zadEnabled", allModes()),
				operationalField("enableDeceptionForAll", allModes()),
				operationalField("dlpEnabled", allModes()),
				operationalField("tunnelProtocolType", allModes()),
				operationalField("secureAgentBasic", allModes()),
				operationalField("secureAgentAdvanced", allModes()),
				sensitiveIdentifierField("supportAdminEmail"),
				operationalField("supportEnabled", allModes()),
				operationalField("fetchLogsForAdminsEnabled", allModes()),
				operationalField("enableRectifyUtils", allModes()),
				operationalField("supportTicketEnabled", allModes()),
				operationalField("disableLoggingControls", allModes()),
				operationalField("defaultAuthType", allModes()),
				operationalField("version", allModes()),
				operationalField("policyActivationRequired", allModes()),
				operationalField("enableAutofillUsername", allModes()),
				operationalField("autoFillUsingLoginHint", allModes()),
				operationalField("dcServiceReadOnly", allModes()),
				operationalField("enableTunnelZappTrafficToggle", allModes()),
				operationalField("machineIdpAuth", allModes()),
				operationalField("linuxVisibility", allModes()),
				sensitiveIdentifierField("registryPathForPac"),
				operationalField("usePollsetForSocketReactor", allModes()),
				operationalField("enableDtlsForZpa", allModes()),
				operationalField("useV8JsEngine", allModes()),
				operationalField("disableParallelIpv4AndIPv6", allModes()),
				operationalField("send64BitBuild", allModes()),
				operationalField("useAddIfscopeRoute", allModes()),
				operationalField("useClearArpCache", allModes()),
				operationalField("useDnsPriorityOrdering", allModes()),
				operationalField("enableBrowserAuth", allModes()),
				operationalField("enablePublicAPI", allModes()),
				operationalField("disableReasonVisibility", allModes()),
				operationalField("followRoutingTable", allModes()),
				operationalField("useDefaultAdapterForDNS", allModes()),
				operationalField("enableMinimumDeviceCleanupAsOne", allModes()),
				operationalField("dnsPriorityOrderingForTrustedDnsCriteria", allModes()),
				operationalField("machineTunnelPosture", allModes()),
				operationalField("zpaPartnerLogin", allModes()),
				operationalField("proxyPort", allModes()),
				operationalField("dnsCacheTtlWindows", allModes()),
				operationalField("dnsCacheTtlMac", allModes()),
				operationalField("dnsCacheTtlAndroid", allModes()),
				operationalField("dnsCacheTtlIos", allModes()),
				operationalField("dnsCacheTtlLinux", allModes()),
				operationalField("zpaClientCertExpInDays", allModes()),
				operationalField("enableFlowLogger", allModes()),
				operationalField("flowLoggingBufferLimit", allModes()),
				operationalField("flowLoggingTimeInterval", allModes()),
				operationalField("postureBasedService", allModes()),
				operationalField("enablePostureBasedProfile", allModes()),
				operationalField("disasterRecovery", allModes()),
				sensitiveIdentifierField("ziaGlobalDbUrlForDR"),
				operationalField("enableReactUI", allModes()),
				operationalField("launchReactUIbyDefault", allModes()),
				operationalField("dlpNotification", allModes()),
				operationalField("vpnGatewayCharLimit", allModes()),
				operationalField("deviceGroupsCount", allModes()),
				operationalField("vpnBypassRefreshInterval", allModes()),
				operationalField("destIncludeExcludeCharLimit", allModes()),
				operationalField("ipV6SupportForTunnel2", allModes()),
				operationalField("destIncludeExcludeCharLimitForIpv6", allModes()),
				operationalField("enableSetProxyOnVPNAdapters", allModes()),
				operationalField("disableDNSRouteExclusion", allModes()),
				operationalField("showVPNTunNotification", allModes()),
				operationalField("addAppBypassToVPNGateway", allModes()),
				operationalField("enableZscalerFirewall", allModes()),
				operationalField("persistentZscalerFirewall", allModes()),
				operationalField("clearMupCache", allModes()),
				operationalField("executeGpoUpdate", allModes()),
				operationalField("enablePortBasedZPAFilter", allModes()),
				operationalField("enableAntiTampering", allModes()),
				operationalField("zpaReauthEnabled", allModes()),
				operationalField("zpaAutoReauthTimeout", allModes()),
				operationalField("enableZpaAuthUserName", allModes()),
				operationalField("enableGlobalZCCTelemetry", allModes()),
				operationalField("configureTunnel2fallbackForZia", allModes()),
				operationalField("webAppConfig", allModes()),
				operationalField("enableInstallWebView2", allModes()),
				operationalField("enableCustomProxyPorts", allModes()),
				operationalField("interceptZIATrafficAllAdapters", allModes()),
				sensitiveIdentifierField("swaggerLink"),
				operationalField("enableOneIdAdmin", allModes()),
				operationalField("enableOneIdUser", allModes()),
				operationalField("restrictAdminAccess", allModes()),
				operationalField("enableZiaUserDepartmentSync", allModes()),
				operationalField("enableUDPTransportSelection", allModes()),
				operationalField("computeDeviceGroupsForZIA", allModes()),
				operationalField("computeDeviceGroupsForZPA", allModes()),
				operationalField("computeDeviceGroupsForZDX", allModes()),
				operationalField("computeDeviceGroupsForZAD", allModes()),
				operationalField("useTunnel2SmeForTunnel1", allModes()),
				operationalField("maCloudName", allModes()),
				operationalField("ziaCloudName", allModes()),
				operationalField("zt2HealthProbeInterval", allModes()),
				operationalField("devicePostureFrequency", allModes()),
				operationalField("zdxManualRollout", allModes()),
				operationalField("winZdxLiteEnabled", allModes()),
				operationalField("telemetryDefault", allModes()),
			},
		},
	}
}
