package resources

func catalogZPA() ResourceCatalog {
	return ResourceCatalog{
		{
			Product:    ProductZPA,
			Name:       "microtenants",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA microtenant description"),
				operationalField("enabled", allModes()),
				tenantConfigField("criteriaAttribute", standardShareModes()),
				sensitiveIdentifierField("criteriaAttributeValues"),
				operationalField("privilegedApprovalsEnabled", allModes()),
				operationalField("operator", allModes()),
				operationalField("priority", allModes()),
				operationalField("creationTime", allModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				secretField("roles"),
				secretField("user"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "version-profiles",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA version profile description"),
				operationalField("creationTime", allModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				secretField("customerId"),
				secretField("customScopeCustomerIds"),
				secretField("customScopeRequestCustomerIds"),
				secretField("versions"),
				operationalField("visibilityScope", allModes()),
				tenantConfigField("upgradePriority", standardShareModes()),
				operationalField("numberOfAssistants", allModes()),
				operationalField("numberOfCustomers", allModes()),
				operationalField("numberOfPrivateBrokers", allModes()),
				operationalField("numberOfSiteControllers", allModes()),
				operationalField("numberOfUpdatedAssistants", allModes()),
				operationalField("numberOfUpdatedPrivateBrokers", allModes()),
				operationalField("numberOfUpdatedSiteControllers", allModes()),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "client-types",
			Operations: ListOperations(),
			Shape:      ShapeSingleton,
			Fields: []FieldSpec{
				operationalField("zpn_client_type_exporter", allModes()),
				operationalField("zpn_client_type_exporter_noauth", allModes()),
				operationalField("zpn_client_type_browser_isolation", allModes()),
				operationalField("zpn_client_type_machine_tunnel", allModes()),
				operationalField("zpn_client_type_ip_anchoring", allModes()),
				operationalField("zpn_client_type_edge_connector", allModes()),
				operationalField("zpn_client_type_zapp", allModes()),
				operationalField("zpn_client_type_slogger", allModes()),
				operationalField("zpn_client_type_branch_connector", allModes()),
				operationalField("zpn_client_type_zapp_partner", allModes()),
				operationalField("zpn_client_type_vdi", allModes()),
				operationalField("zpn_client_type_zia_inspection", allModes()),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "platforms",
			Operations: ListOperations(),
			Shape:      ShapeSingleton,
			Fields: []FieldSpec{
				operationalField("linux", allModes()),
				operationalField("android", allModes()),
				operationalField("windows", allModes()),
				operationalField("ios", allModes()),
				operationalField("mac", allModes()),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "isolation-profiles",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA isolation profile description"),
				operationalField("enabled", allModes()),
				operationalField("creationTime", allModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				sensitiveIdentifierField("isolationProfileId"),
				secretField("isolationTenantId"),
				sensitiveIdentifierField("isolationUrl"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "branch-connectors",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA branch connector description"),
				operationalField("enabled", allModes()),
				operationalField("creationTime", allModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				secretField("branchConnectorGroupId"),
				tenantConfigField("branchConnectorGroupName", standardShareModes()),
				secretField("edgeConnectorGroupId"),
				tenantConfigField("edgeConnectorGroupName", standardShareModes()),
				secretField("enrollmentCert"),
				secretField("fingerprint"),
				sensitiveIdentifierField("ipAcl"),
				secretField("issuedCertId"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "user-portals",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA user portal description"),
				operationalField("enabled", allModes()),
				operationalField("creationTime", allModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				secretField("certificateId"),
				tenantConfigField("certificateName", standardShareModes()),
				sensitiveIdentifierField("domain"),
				sensitiveIdentifierField("extDomain"),
				sensitiveIdentifierField("extDomainName"),
				sensitiveIdentifierField("extDomainTranslation"),
				tenantConfigField("extLabel", standardShareModes()),
				operationalField("getcName", allModes()),
				secretField("imageData"),
				operationalField("managedByZs", allModes()),
				secretField("microtenantId"),
				tenantConfigField("microtenantName", standardShareModes()),
				tenantConfigField("userNotification", standardShareModes()),
				operationalField("userNotificationEnabled", allModes()),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "user-portal-aups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA user portal AUP description"),
				operationalField("enabled", allModes()),
				operationalField("creationTime", allModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				freeTextField("aup", "ZPA user portal acceptable-use-policy text"),
				sensitiveIdentifierField("email"),
				secretField("microtenantId"),
				tenantConfigField("microtenantName", standardShareModes()),
				sensitiveIdentifierField("phoneNum"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "user-portal-links",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA user portal link description"),
				operationalField("enabled", allModes()),
				operationalField("creationTime", allModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				secretField("applicationId"),
				tenantConfigField("iconText", standardShareModes()),
				sensitiveIdentifierField("link"),
				sensitiveIdentifierField("linkPath"),
				secretField("microtenantId"),
				tenantConfigField("microtenantName", standardShareModes()),
				tenantConfigField("nameWithoutTrim", standardShareModes()),
				operationalField("protocol", allModes()),
				secretField("userPortalId"),
				secretField("userPortals"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "browser-access",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA browser access segment description"),
				tenantConfigField("segmentGroupName", standardShareModes()),
				operationalField("bypassType", allModes()),
				operationalField("bypassOnReauth", allModes()),
				operationalField("enabled", allModes()),
				operationalField("passiveHealthEnabled", allModes()),
				operationalField("fqdnDnsCheck", allModes()),
				operationalField("apiProtectionEnabled", allModes()),
				operationalField("selectConnectorCloseToApp", allModes()),
				operationalField("doubleEncrypt", allModes()),
				operationalField("healthCheckType", allModes()),
				operationalField("isCnameEnabled", allModes()),
				operationalField("ipAnchored", allModes()),
				operationalField("tcpKeepAlive", allModes()),
				operationalField("useInDrMode", allModes()),
				operationalField("inspectTrafficWithZia", allModes()),
				operationalField("healthReporting", allModes()),
				operationalField("icmpAccessType", allModes()),
				operationalField("creationTime", allModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				operationalField("readOnly", allModes()),
				operationalField("restrictionType", allModes()),
				tenantConfigField("microtenantName", standardShareModes()),
				sensitiveIdentifierField("domainNames"),
				sensitiveIdentifierField("tcpPortRanges"),
				sensitiveIdentifierField("udpPortRanges"),
				secretField("segmentGroupId"),
				secretField("extranetEnabled"),
				secretField("appRecommendationId"),
				secretField("matchStyle"),
				secretField("configSpace"),
				secretField("isIncompleteDRConfig"),
				secretField("microtenantId"),
				secretField("zscalerManaged"),
				secretField("weightedLoadBalancing"),
				secretField("tcpPortRange"),
				secretField("udpPortRange"),
				secretField("clientlessApps"),
				secretField("serverGroups"),
				secretField("sharedMicrotenantDetails"),
				secretField("policyStyle"),
				secretField("zpnErId"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "inspection-app-segments",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA inspection application segment description"),
				tenantConfigField("segmentGroupName", standardShareModes()),
				operationalField("bypassType", allModes()),
				operationalField("bypassOnReauth", allModes()),
				operationalField("enabled", allModes()),
				operationalField("adpEnabled", allModes()),
				operationalField("autoAppProtectEnabled", allModes()),
				operationalField("passiveHealthEnabled", allModes()),
				operationalField("fqdnDnsCheck", allModes()),
				operationalField("apiProtectionEnabled", allModes()),
				operationalField("selectConnectorCloseToApp", allModes()),
				operationalField("doubleEncrypt", allModes()),
				operationalField("healthCheckType", allModes()),
				operationalField("isCnameEnabled", allModes()),
				operationalField("ipAnchored", allModes()),
				operationalField("tcpKeepAlive", allModes()),
				operationalField("useInDrMode", allModes()),
				operationalField("healthReporting", allModes()),
				operationalField("icmpAccessType", allModes()),
				operationalField("creationTime", allModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				operationalField("readOnly", allModes()),
				operationalField("restrictionType", allModes()),
				operationalField("tcpProtocols", allModes()),
				operationalField("udpProtocols", allModes()),
				tenantConfigField("microtenantName", standardShareModes()),
				sensitiveIdentifierField("domainNames"),
				sensitiveIdentifierField("tcpPortRanges"),
				sensitiveIdentifierField("udpPortRanges"),
				secretField("segmentGroupId"),
				secretField("extranetEnabled"),
				secretField("appRecommendationId"),
				secretField("matchStyle"),
				secretField("configSpace"),
				secretField("isIncompleteDRConfig"),
				secretField("microtenantId"),
				secretField("zscalerManaged"),
				secretField("weightedLoadBalancing"),
				secretField("tcpPortRange"),
				secretField("udpPortRange"),
				secretField("inspectionApps"),
				secretField("commonAppsDto"),
				secretField("serverGroups"),
				secretField("sharedMicrotenantDetails"),
				secretField("policyStyle"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "pra-app-segments",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA PRA application segment description"),
				tenantConfigField("segmentGroupName", standardShareModes()),
				operationalField("bypassType", allModes()),
				operationalField("bypassOnReauth", allModes()),
				operationalField("enabled", allModes()),
				operationalField("passiveHealthEnabled", allModes()),
				operationalField("fqdnDnsCheck", allModes()),
				operationalField("apiProtectionEnabled", allModes()),
				operationalField("selectConnectorCloseToApp", allModes()),
				operationalField("doubleEncrypt", allModes()),
				operationalField("healthCheckType", allModes()),
				operationalField("isCnameEnabled", allModes()),
				operationalField("ipAnchored", allModes()),
				operationalField("tcpKeepAlive", allModes()),
				operationalField("useInDrMode", allModes()),
				operationalField("healthReporting", allModes()),
				operationalField("icmpAccessType", allModes()),
				operationalField("creationTime", allModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				operationalField("readOnly", allModes()),
				operationalField("restrictionType", allModes()),
				tenantConfigField("microtenantName", standardShareModes()),
				sensitiveIdentifierField("domainNames"),
				sensitiveIdentifierField("tcpPortRanges"),
				sensitiveIdentifierField("udpPortRanges"),
				secretField("segmentGroupId"),
				secretField("extranetEnabled"),
				secretField("appRecommendationId"),
				secretField("matchStyle"),
				secretField("configSpace"),
				secretField("applications"),
				secretField("isIncompleteDRConfig"),
				secretField("microtenantId"),
				secretField("zscalerManaged"),
				secretField("weightedLoadBalancing"),
				secretField("tcpPortRange"),
				secretField("udpPortRange"),
				secretField("defaultIdleTimeout"),
				secretField("defaultMaxAge"),
				secretField("praApps"),
				secretField("commonAppsDto"),
				secretField("serverGroups"),
				secretField("sharedMicrotenantDetails"),
				secretField("policyStyle"),
				secretField("zpnErId"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "server-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA server group description"),
				operationalField("enabled", allModes()),
				sensitiveIdentifierField("ipAnchored"),
				secretField("configSpace"),
				secretField("dynamicDiscovery"),
				secretField("extranetEnabled"),
				operationalField("creationTime", allModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				secretField("microtenantId"),
				tenantConfigField("microtenantName", standardShareModes()),
				operationalField("readOnly", allModes()),
				operationalField("restrictionType", allModes()),
				secretField("zscalerManaged"),
				secretField("appConnectorGroups"),
				secretField("servers"),
				secretField("applications"),
				secretField("extranetDTO"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "segment-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA segment group description"),
				operationalField("enabled", allModes()),
				secretField("configSpace"),
				operationalField("creationTime", allModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				operationalField("policyMigrated", allModes()),
				operationalField("tcpKeepAliveEnabled", allModes()),
				secretField("microtenantId"),
				tenantConfigField("microtenantName", standardShareModes()),
				secretField("addedApps"),
				operationalField("deletedApps", allModes()),
				secretField("applications"),
				secretField("applicationNames"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "application-segments",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA application segment description"),
				operationalField("enabled", allModes()),
				operationalField("bypassType", allModes()),
				operationalField("healthCheckType", allModes()),
				operationalField("icmpAccessType", allModes()),
				operationalField("healthReporting", allModes()),
				operationalField("passiveHealthEnabled", allModes()),
				operationalField("ipAnchored", allModes()),
				operationalField("fqdnDnsCheck", allModes()),
				operationalField("tcpKeepAlive", allModes()),
				operationalField("isCnameEnabled", allModes()),
				operationalField("selectConnectorCloseToApp", allModes()),
				operationalField("restrictionType", allModes()),
				operationalField("useInDrMode", allModes()),
				operationalField("creationTime", standardShareModes()),
				operationalField("modifiedTime", standardShareModes()),
				operationalField("apiProtectionEnabled", standardOnlyMode()),
				operationalField("inspectTrafficWithZia", standardOnlyMode()),
				operationalField("doubleEncrypt", standardOnlyMode()),
				operationalField("adpEnabled", standardOnlyMode()),
				operationalField("autoAppProtectEnabled", standardOnlyMode()),
				operationalField("bypassOnReauth", standardOnlyMode()),
				tenantConfigField("segmentGroupName", standardShareModes()),
				tenantConfigField("microtenantName", standardShareModes()),
				sensitiveIdentifierField("domainNames"),
				sensitiveIdentifierField("tcpPortRanges"),
				sensitiveIdentifierField("udpPortRanges"),
				{
					Name:           "serverGroups",
					Classification: ClassTenantConfig,
					AllowedModes:   allModes(),
					Fields: []FieldSpec{
						operationalField("id", allModes()),
						tenantConfigField("name", standardShareModes()),
					},
				},
				secretField("modifiedBy"),
				secretField("segmentGroupId"),
				secretField("microtenantId"),
				secretField("appRecommendationId"),
				secretField("applications"),
				secretField("configSpace"),
				secretField("matchStyle"),
				secretField("policyStyle"),
				secretField("isIncompleteDRConfig"),
				secretField("defaultMaxAge"),
				secretField("defaultIdleTimeout"),
				secretField("readOnly"),
				secretField("zscalerManaged"),
				secretField("clientlessApps"),
				secretField("sharedMicrotenantDetails"),
				secretField("shareToMicrotenants"),
				secretField("tags"),
				secretField("zpnErId"),
				secretField("tcpPortRange"),
				secretField("udpPortRange"),
				secretField("weightedLoadBalancing"),
				secretField("extranetEnabled"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "app-connectors",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				secretField("appConnectorGroupId"),
				tenantConfigField("appConnectorGroupName", standardShareModes()),
				operationalField("applicationStartTime", allModes()),
				secretField("assistantVersion"),
				operationalField("controlChannelStatus", allModes()),
				operationalField("creationTime", allModes()),
				tenantConfigField("ctrlBrokerName", standardShareModes()),
				tenantConfigField("currentVersion", standardShareModes()),
				freeTextField("description", "ZPA app connector description"),
				operationalField("enabled", allModes()),
				secretField("enrollmentCert"),
				operationalField("expectedUpgradeTime", allModes()),
				tenantConfigField("expectedVersion", standardShareModes()),
				secretField("fingerprint"),
				operationalField("id", allModes()),
				sensitiveIdentifierField("ipAcl"),
				secretField("issuedCertId"),
				operationalField("lastBrokerConnectTime", allModes()),
				operationalField("lastBrokerConnectTimeDuration", allModes()),
				operationalField("lastBrokerDisconnectTime", allModes()),
				operationalField("lastBrokerDisconnectTimeDuration", allModes()),
				operationalField("lastUpgradeTime", allModes()),
				sensitiveIdentifierField("latitude"),
				sensitiveIdentifierField("location"),
				sensitiveIdentifierField("longitude"),
				secretField("microtenantId"),
				tenantConfigField("microtenantName", standardShareModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				tenantConfigField("name", standardShareModes()),
				tenantConfigField("platform", standardShareModes()),
				tenantConfigField("platformDetail", standardShareModes()),
				tenantConfigField("previousVersion", standardShareModes()),
				sensitiveIdentifierField("privateIp"),
				secretField("provisioningKeyId"),
				secretField("provisioningKeyName"),
				sensitiveIdentifierField("publicIp"),
				operationalField("readOnly", allModes()),
				operationalField("restrictionType", allModes()),
				operationalField("runtimeOS", allModes()),
				tenantConfigField("sargeVersion", standardShareModes()),
				secretField("upgradeAttempt"),
				operationalField("upgradeStatus", allModes()),
				secretField("zpnSubModuleUpgradeList"),
				secretField("zscalerManaged"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "app-connector-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA app connector group description"),
				operationalField("enabled", allModes()),
				sensitiveIdentifierField("cityCountry"),
				sensitiveIdentifierField("countryCode"),
				operationalField("creationTime", allModes()),
				operationalField("dnsQueryType", allModes()),
				operationalField("connectorGroupType", allModes()),
				secretField("geoLocationId"),
				sensitiveIdentifierField("latitude"),
				sensitiveIdentifierField("location"),
				sensitiveIdentifierField("longitude"),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				secretField("overrideVersionProfile"),
				secretField("praEnabled"),
				operationalField("wafDisabled", allModes()),
				operationalField("upgradeDay", allModes()),
				operationalField("upgradeTimeInSecs", allModes()),
				secretField("versionProfileId"),
				tenantConfigField("versionProfileName", standardShareModes()),
				secretField("versionProfileVisibilityScope"),
				operationalField("tcpQuickAckApp", allModes()),
				operationalField("tcpQuickAckAssistant", allModes()),
				operationalField("useInDrMode", allModes()),
				operationalField("tcpQuickAckReadAssistant", allModes()),
				operationalField("lssAppConnectorGroup", allModes()),
				secretField("microtenantId"),
				tenantConfigField("microtenantName", standardShareModes()),
				secretField("siteId"),
				tenantConfigField("siteName", standardShareModes()),
				operationalField("readOnly", allModes()),
				operationalField("restrictionType", allModes()),
				secretField("zscalerManaged"),
				secretField("dcHostingInfo"),
				tenantConfigField("nameWithoutTrim", standardShareModes()),
				secretField("serverGroups"),
				secretField("connectors"),
				secretField("npAssistantGroup"),
				secretField("enrollmentCertId"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "app-servers",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				sensitiveIdentifierField("address"),
				secretField("appServerGroupIds"),
				secretField("configSpace"),
				operationalField("creationTime", allModes()),
				freeTextField("description", "ZPA app server description"),
				operationalField("enabled", allModes()),
				operationalField("id", allModes()),
				secretField("microtenantId"),
				tenantConfigField("microtenantName", standardShareModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				tenantConfigField("name", standardShareModes()),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "machine-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("id", allModes()),
				tenantConfigField("name", standardShareModes()),
				freeTextField("description", "ZPA machine group description"),
				operationalField("enabled", allModes()),
				operationalField("creationTime", allModes()),
				secretField("machines"),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				secretField("microtenantId"),
				tenantConfigField("microtenantName", standardShareModes()),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "trusted-networks",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("creationTime", allModes()),
				sensitiveIdentifierField("domain"),
				operationalField("id", allModes()),
				secretField("masterCustomerId"),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				tenantConfigField("name", standardShareModes()),
				secretField("networkId"),
				secretField("zscalerCloud"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "service-edge-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				secretField("altCloud"),
				secretField("city"),
				sensitiveIdentifierField("cityCountry"),
				sensitiveIdentifierField("countryCode"),
				operationalField("creationTime", allModes()),
				freeTextField("description", "ZPA service edge group description"),
				operationalField("enabled", allModes()),
				secretField("enrollmentCertId"),
				operationalField("exclusiveForBusinessContinuity", allModes()),
				secretField("geoLocationId"),
				operationalField("graceDistanceEnabled", allModes()),
				secretField("graceDistanceValue"),
				secretField("graceDistanceValueUnit"),
				operationalField("id", allModes()),
				operationalField("isPublic", allModes()),
				sensitiveIdentifierField("latitude"),
				sensitiveIdentifierField("location"),
				sensitiveIdentifierField("longitude"),
				secretField("microtenantId"),
				tenantConfigField("microtenantName", standardShareModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				tenantConfigField("name", standardShareModes()),
				secretField("nameWithoutTrim"),
				operationalField("objectType", allModes()),
				operationalField("overrideVersionProfile", allModes()),
				operationalField("readOnly", allModes()),
				operationalField("restrictedEntity", allModes()),
				operationalField("restrictionType", allModes()),
				tenantConfigField("scopeName", standardShareModes()),
				secretField("serviceEdges"),
				secretField("siteId"),
				tenantConfigField("siteName", standardShareModes()),
				secretField("trustedNetworks"),
				operationalField("upgradeDay", allModes()),
				operationalField("upgradeTimeInSecs", allModes()),
				operationalField("useInDrMode", allModes()),
				secretField("versionProfileId"),
				tenantConfigField("versionProfileName", standardShareModes()),
				secretField("versionProfileVisibilityScope"),
				secretField("zscalerManaged"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "service-edges",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("applicationStartTime", allModes()),
				operationalField("controlChannelStatus", allModes()),
				operationalField("creationTime", allModes()),
				tenantConfigField("ctrlBrokerName", standardShareModes()),
				tenantConfigField("currentVersion", standardShareModes()),
				freeTextField("description", "ZPA service edge description"),
				operationalField("enabled", allModes()),
				secretField("enrollmentCert"),
				operationalField("expectedUpgradeTime", allModes()),
				tenantConfigField("expectedVersion", standardShareModes()),
				secretField("fingerprint"),
				operationalField("id", allModes()),
				sensitiveIdentifierField("ipAcl"),
				secretField("issuedCertId"),
				operationalField("lastBrokerConnectTime", allModes()),
				operationalField("lastBrokerConnectTimeDuration", allModes()),
				operationalField("lastBrokerDisconnectTime", allModes()),
				operationalField("lastBrokerDisconnectTimeDuration", allModes()),
				operationalField("lastUpgradeTime", allModes()),
				sensitiveIdentifierField("latitude"),
				sensitiveIdentifierField("listenIps"),
				sensitiveIdentifierField("location"),
				sensitiveIdentifierField("longitude"),
				secretField("microtenantId"),
				tenantConfigField("microtenantName", standardShareModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				tenantConfigField("name", standardShareModes()),
				tenantConfigField("platform", standardShareModes()),
				tenantConfigField("platformDetail", standardShareModes()),
				tenantConfigField("previousVersion", standardShareModes()),
				secretField("privateBrokerVersion"),
				sensitiveIdentifierField("privateIp"),
				secretField("provisioningKeyId"),
				secretField("provisioningKeyName"),
				sensitiveIdentifierField("publicIp"),
				sensitiveIdentifierField("publishIps"),
				operationalField("publishIpv6", allModes()),
				operationalField("runtimeOS", allModes()),
				tenantConfigField("sargeVersion", standardShareModes()),
				secretField("serviceEdgeGroupId"),
				tenantConfigField("serviceEdgeGroupName", standardShareModes()),
				secretField("upgradeAttempt"),
				operationalField("upgradeStatus", allModes()),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "cloud-connector-groups",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				secretField("cloudConnectors"),
				operationalField("creationTime", allModes()),
				freeTextField("description", "ZPA cloud connector group description"),
				operationalField("enabled", allModes()),
				secretField("geoLocationId"),
				operationalField("id", allModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				tenantConfigField("name", standardShareModes()),
				secretField("ziaCloud"),
				secretField("ziaOrgId"),
				operationalField("znfGroupType", allModes()),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "cloud-connectors",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				operationalField("creationTime", allModes()),
				freeTextField("description", "ZPA cloud connector description"),
				secretField("edgeConnectorGroupId"),
				tenantConfigField("edgeConnectorGroupName", standardShareModes()),
				operationalField("enabled", allModes()),
				secretField("enrollmentCert"),
				secretField("fingerprint"),
				operationalField("id", allModes()),
				sensitiveIdentifierField("ipAcl"),
				secretField("issuedCertId"),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				tenantConfigField("name", standardShareModes()),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "posture-profiles",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("applyToMachineTunnelEnabled", allModes()),
				operationalField("creationTime", allModes()),
				operationalField("crlCheckEnabled", allModes()),
				sensitiveIdentifierField("domain"),
				operationalField("id", allModes()),
				secretField("masterCustomerId"),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				tenantConfigField("name", standardShareModes()),
				secretField("nonExportablePrivateKeyEnabled"),
				tenantConfigField("platform", standardShareModes()),
				operationalField("postureType", allModes()),
				secretField("postureUdid"),
				secretField("rootCert"),
				secretField("zscalerCloud"),
				secretField("zscalerCustomerId"),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "cbi-zpa-profiles",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				sensitiveIdentifierField("cbiProfileId"),
				secretField("cbiTenantId"),
				sensitiveIdentifierField("cbiUrl"),
				operationalField("creationTime", allModes()),
				freeTextField("description", "ZPA CBI ZPA profile description"),
				operationalField("enabled", allModes()),
				operationalField("id", allModes()),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				tenantConfigField("name", standardShareModes()),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "c2c-ip-ranges",
			Operations: ReadOperations(),
			Fields: []FieldSpec{
				operationalField("availableIps", allModes()),
				sensitiveIdentifierField("countryCode"),
				operationalField("creationTime", allModes()),
				secretField("customerId"),
				freeTextField("description", "ZPA C2C IP range description"),
				operationalField("enabled", allModes()),
				operationalField("id", allModes()),
				sensitiveIdentifierField("ipRangeBegin"),
				sensitiveIdentifierField("ipRangeEnd"),
				operationalField("isDeleted", allModes()),
				sensitiveIdentifierField("latitudeInDb"),
				sensitiveIdentifierField("location"),
				sensitiveIdentifierField("locationHint"),
				sensitiveIdentifierField("longitudeInDb"),
				operationalField("modifiedBy", allModes()),
				operationalField("modifiedTime", allModes()),
				tenantConfigField("name", standardShareModes()),
				operationalField("sccmFlag", allModes()),
				sensitiveIdentifierField("subnetCidr"),
				operationalField("totalIps", allModes()),
				operationalField("usedIps", allModes()),
			},
		},
		{
			Product:    ProductZPA,
			Name:       "config-overrides",
			Operations: ListOperations(),
			Fields: []FieldSpec{
				tenantConfigField("brokerName", standardShareModes()),
				secretField("configKey"),
				secretField("configValue"),
				secretField("configValueInt"),
				secretField("customerId"),
				tenantConfigField("customerName", standardShareModes()),
				freeTextField("description", "ZPA config override description"),
				secretField("targetGid"),
				tenantConfigField("targetName", standardShareModes()),
				operationalField("targetType", allModes()),
			},
		},
	}
}
