package zscaler

import (
	"reflect"

	"github.com/dvmrry/zscalerctl/internal/resources"

	ztwactivation "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/activation"
	ztwadminroles "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/adminuserrolemgmt/adminroles"
	ztwadminusers "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/adminuserrolemgmt/adminusers"
	ztwdnsgateway "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/dns_gateway"
	ztwecgroup "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/ecgroup"
	ztwziaforwardinggateway "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/forwarding_gateways/zia_forwarding_gateway"
	ztwlocation "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/locationmanagement/location"
	ztwlocationtemplate "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/locationmanagement/locationtemplate"
	ztwaccountgroups "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/partner_integrations/account_groups"
	ztwpubliccloudinfo "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/partner_integrations/public_cloud_info"
	ztwforwardingrules "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/policy_management/forwarding_rules"
	ztwtrafficdnsrules "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/policy_management/traffic_dns_rules"
	ztwtrafficlogrules "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/policy_management/traffic_log_rules"
	ztwipdestinationgroups "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/policyresources/ipdestinationgroups"
	ztwipgroups "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/policyresources/ipgroups"
	ztwipsourcegroups "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/policyresources/ipsourcegroups"
	ztwnetworkservicegroups "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/policyresources/networkservicegroups"
	ztwnetworkservices "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/policyresources/networkservices"
	ztwzparesources "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/policyresources/zparesources"
	ztwpubliccloudaccount "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/provisioning/public_cloud_account"
	ztwworkloadgroups "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/workload_groups"
)

func reviewedSDKShapesZTW() []sdkShapeReview {
	return []sdkShapeReview{
		{
			name:         "ztwactivation.ECAdminActivation",
			resource:     resources.ProductZTW,
			resourceName: resourceZTWActivationStat,
			typ:          reflect.TypeOf(ztwactivation.ECAdminActivation{}),
			catalogFields: []string{
				"orgEditStatus",
				"orgLastActivateStatus",
				"adminActivateStatus",
			},
			ignoredFields: ignoredBecause(
				"admin-by-name activation status map is unmodeled tenant-identifying detail; the scalar org/admin status fields are projected instead",
				"adminStatusMap",
			),
		},
		{
			name:         "ztwworkloadgroups.WorkloadGroup",
			resource:     resources.ProductZTW,
			resourceName: resourceWorkloadGroups,
			typ:          reflect.TypeOf(ztwworkloadgroups.WorkloadGroup{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"expression",
				"lastModifiedTime",
				"lastModifiedBy",
				"expressionJson",
			},
		},
		{
			name:         "ztwpubliccloudaccount.PublicCloudAccountDetails",
			resource:     resources.ProductZTW,
			resourceName: resourcePublicCloudAccts,
			typ:          reflect.TypeOf(ztwpubliccloudaccount.PublicCloudAccountDetails{}),
			catalogFields: []string{
				"id",
				"accountId",
				"platformId",
			},
		},
		{
			name:         "ztwdnsgateway.DNSGateway",
			resource:     resources.ProductZTW,
			resourceName: resourceDNSGateways,
			typ:          reflect.TypeOf(ztwdnsgateway.DNSGateway{}),
			catalogFields: []string{
				"id",
				"name",
				"dnsGatewayType",
				"ecDnsGatewayOptionsPrimary",
				"ecDnsGatewayOptionsSecondary",
				"failureBehavior",
				"primaryIp",
				"secondaryIp",
				"lastModifiedTime",
				"lastModifiedBy",
			},
		},
		{
			name:         "ztwziaforwardinggateway.ECGateway",
			resource:     resources.ProductZTW,
			resourceName: resourceForwardingGWs,
			typ:          reflect.TypeOf(ztwziaforwardinggateway.ECGateway{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"failClosed",
				"manualPrimary",
				"manualSecondary",
				"subcloudPrimary",
				"subcloudSecondary",
				"primaryType",
				"secondaryType",
				"type",
				"failureBehavior",
				"dnsGatewayType",
				"primaryIp",
				"secondaryIp",
				"ecDnsGatewayOptionsPrimary",
				"ecDnsGatewayOptionsSecondary",
				"lastModifiedBy",
				"lastModifiedTime",
			},
		},
		{
			name:         "ztwecgroup.EcGroup",
			resource:     resources.ProductZTW,
			resourceName: resourceECGroups,
			typ:          reflect.TypeOf(ztwecgroup.EcGroup{}),
			catalogFields: []string{
				"id",
				"name",
				"desc",
				"deployType",
				"status",
				"platform",
				"awsAvailabilityZone",
				"azureAvailabilityZone",
				"maxEcCount",
				"tunnelMode",
				"location",
				"provTemplate",
				"ecVMs",
			},
		},
		{
			name:         "ztwipsourcegroups.IPSourceGroups",
			resource:     resources.ProductZTW,
			resourceName: resourceIPSourceGroups,
			typ:          reflect.TypeOf(ztwipsourcegroups.IPSourceGroups{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"ipAddresses",
				"creatorContext",
				"isNonEditable",
			},
		},
		{
			name:         "ztwipdestinationgroups.IPDestinationGroups",
			resource:     resources.ProductZTW,
			resourceName: resourceIPDestGroups,
			typ:          reflect.TypeOf(ztwipdestinationgroups.IPDestinationGroups{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"type",
				"addresses",
				"ipCategories",
				"countries",
				"isNonEditable",
			},
		},
		{
			name:         "ztwipgroups.IPGroups",
			resource:     resources.ProductZTW,
			resourceName: resourceIPGroups,
			typ:          reflect.TypeOf(ztwipgroups.IPGroups{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"ipAddresses",
				"creatorContext",
				"isNonEditable",
				"extranetIpPool",
				"isPredefined",
			},
		},
		{
			name:         "ztwnetworkservices.NetworkServices",
			resource:     resources.ProductZTW,
			resourceName: resourceNetworkServices,
			typ:          reflect.TypeOf(ztwnetworkservices.NetworkServices{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"tag",
				"srcTcpPorts",
				"destTcpPorts",
				"srcUdpPorts",
				"destUdpPorts",
				"type",
				"isNameL10nTag",
				"creatorContext",
			},
		},
		{
			name:         "ztwnetworkservicegroups.NetworkServiceGroups",
			resource:     resources.ProductZTW,
			resourceName: resourceNetworkSvcGroups,
			typ:          reflect.TypeOf(ztwnetworkservicegroups.NetworkServiceGroups{}),
			catalogFields: []string{
				"id",
				"name",
				"services",
				"description",
				"creatorContext",
			},
		},
		{
			name:         "ztwadminusers.AdminUsers",
			resource:     resources.ProductZTW,
			resourceName: resourceAdminUsers,
			typ:          reflect.TypeOf(ztwadminusers.AdminUsers{}),
			catalogFields: []string{
				"id",
				"loginName",
				"userName",
				"email",
				"comments",
				"disabled",
				"password",
				"pwdLastModifiedTime",
				"isNonEditable",
				"isPasswordLoginAllowed",
				"isPasswordExpired",
				"isAuditor",
				"isSecurityReportCommEnabled",
				"isServiceUpdateCommEnabled",
				"isProductUpdateCommEnabled",
				"isExecMobileAppEnabled",
				"adminScopescopeGroupMemberEntities",
				"adminScopeScopeEntities",
				"adminScopeType",
				"role",
				"execMobileAppTokens",
			},
		},
		{
			name: "ztwadminusers.Role",
			typ:  reflect.TypeOf(ztwadminusers.Role{}),
			ignoredFields: ignoredBecause(
				"covered by the ztw/admin-users role nested field",
				"id",
				"name",
				"isNameL10nTag",
				"extensions",
			),
		},
		{
			name: "ztwadminusers.ExecMobileAppTokens",
			typ:  reflect.TypeOf(ztwadminusers.ExecMobileAppTokens{}),
			ignoredFields: ignoredBecause(
				"covered by dropped execMobileAppTokens parent",
				"cloud",
				"orgId",
				"name",
				"tokenId",
				"token",
				"tokenExpiry",
				"createTime",
				"deviceId",
				"deviceName",
			),
		},
		{
			name:         "ztwadminroles.AdminRoles",
			resource:     resources.ProductZTW,
			resourceName: resourceAdminRoles,
			typ:          reflect.TypeOf(ztwadminroles.AdminRoles{}),
			catalogFields: []string{
				"id",
				"rank",
				"name",
				"policyAccess",
				"alertingAccess",
				"dashboardAccess",
				"reportAccess",
				"analysisAccess",
				"usernameAccess",
				"adminAcctAccess",
				"deviceInfoAccess",
				"isAuditor",
				"permissions",
				"isNonEditable",
				"logsLimit",
				"roleType",
				"featurePermissions",
			},
		},
		{
			name:         "ztwlocation.Locations",
			resource:     resources.ProductZTW,
			resourceName: resourceLocations,
			typ:          reflect.TypeOf(ztwlocation.Locations{}),
			catalogFields: []string{
				"id",
				"name",
				"parentId",
				"enforceBandwidthControl",
				"upBandwidth",
				"dnBandwidth",
				"overrideUpBandwidth",
				"overrideDnBandwidth",
				"sharedUpBandwidth",
				"sharedDownBandwidth",
				"unusedUpBandwidth",
				"country",
				"state",
				"language",
				"tz",
				"ipAddresses",
				"ports",
				"authRequired",
				"sslScanEnabled",
				"zappSSLScanEnabled",
				"xffForwardEnabled",
				"otherSubLocation",
				"other6SubLocation",
				"ecLocation",
				"surrogateIP",
				"idleTimeInMinutes",
				"displayTimeUnit",
				"surrogateIPEnforcedForKnownBrowsers",
				"surrogateRefreshTimeInMinutes",
				"surrogateRefreshTimeUnit",
				"ofwEnabled",
				"ipsControl",
				"aupEnabled",
				"cautionEnabled",
				"aupBlockInternetUntilAccepted",
				"aupForceSslInspection",
				"aupTimeoutInDays",
				"profile",
				"description",
				"ipv6Enabled",
				"ipv6Dns64Prefix",
				"kerberosAuth",
				"digestAuthEnabled",
				"childCount",
				"matchInChild",
				"excludeFromDynamicGroups",
				"excludeFromManualGroups",
				"vpnCredentials",
				"virtualZens",
				"virtualZenClusters",
				"staticLocationGroups",
				"dynamiclocationGroups",
				"publicCloudAccountId",
				"vpcInfo",
			},
		},
		{
			name: "ztwlocation.VPNCredentials",
			typ:  reflect.TypeOf(ztwlocation.VPNCredentials{}),
			ignoredFields: ignoredBecause(
				"covered by dropped ztw/locations vpnCredentials parent",
				"id",
				"type",
				"fqdn",
				"ipAddress",
				"preSharedKey",
				"comments",
				"managedBy",
			),
		},
		{
			name: "ztwlocation.ManagedBy",
			typ:  reflect.TypeOf(ztwlocation.ManagedBy{}),
			ignoredFields: ignoredBecause(
				"covered by dropped ztw/locations vpnCredentials parent",
				"id",
				"name",
				"extensions",
			),
		},
		{
			name: "ztwlocation.VPCInfo",
			typ:  reflect.TypeOf(ztwlocation.VPCInfo{}),
			ignoredFields: ignoredBecause(
				"covered by dropped ztw/locations vpcInfo parent",
				"cloudProvider",
				"cloudMeta",
			),
		},
		{
			name: "ztwlocation.CloudMeta",
			typ:  reflect.TypeOf(ztwlocation.CloudMeta{}),
			ignoredFields: ignoredBecause(
				"covered by dropped ztw/locations vpcInfo parent",
				"id",
				"name",
			),
		},
		{
			name:         "ztwlocationtemplate.LocationTemplate",
			resource:     resources.ProductZTW,
			resourceName: resourceLocationTmpls,
			typ:          reflect.TypeOf(ztwlocationtemplate.LocationTemplate{}),
			catalogFields: []string{
				"id",
				"name",
				"desc",
				"template",
				"editable",
				"lastModTime",
				"lastModUid",
			},
		},
		{
			name: "ztwlocationtemplate.LocationTemplateDetails",
			typ:  reflect.TypeOf(ztwlocationtemplate.LocationTemplateDetails{}),
			ignoredFields: ignoredBecause(
				"covered by ztw/location-templates template nested field",
				"templatePrefix",
				"xffForwardEnabled",
				"authRequired",
				"cautionEnabled",
				"aupEnabled",
				"aupTimeoutInDays",
				"ofwEnabled",
				"ipsControl",
				"enforceBandwidthControl",
				"upBandwidth",
				"dnBandwidth",
				"displayTimeUnit",
				"idleTimeInMinutes",
				"surrogateIPEnforcedForKnownBrowsers",
				"surrogateRefreshTimeUnit",
				"surrogateRefreshTimeInMinutes",
				"surrogateIP",
				"editable",
				"lastModUid",
			),
		},
		{
			name:         "ztwaccountgroups.AccountGroups",
			resource:     resources.ProductZTW,
			resourceName: resourceAccountGroups,
			typ:          reflect.TypeOf(ztwaccountgroups.AccountGroups{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"cloudType",
				"publicCloudAccounts",
				"cloudConnectorGroups",
			},
		},
		{
			name:         "ztwpubliccloudinfo.PublicCloudInfo",
			resource:     resources.ProductZTW,
			resourceName: resourcePublicCloudInfo,
			typ:          reflect.TypeOf(ztwpubliccloudinfo.PublicCloudInfo{}),
			catalogFields: []string{
				"id",
				"name",
				"cloudType",
				"externalId",
				"lastModTime",
				"lastSyncTime",
				"accountGroups",
				"lastModUser",
				"regionStatus",
				"supportedRegions",
				"accountDetails",
			},
		},
		{
			name: "ztwpubliccloudinfo.AccountDetails",
			typ:  reflect.TypeOf(ztwpubliccloudinfo.AccountDetails{}),
			ignoredFields: ignoredBecause(
				"covered by dropped ztw/public-cloud-info accountDetails parent",
				"name",
				"awsAccountId",
				"awsRoleName",
				"cloudWatchGroupArn",
				"eventBusName",
				"externalId",
				"logInfoType",
				"troubleShootingLogging",
				"trustedAccountId",
				"trustedRole",
			),
		},
		{
			name: "ztwpubliccloudinfo.PublicCloudInfoLite",
			typ:  reflect.TypeOf(ztwpubliccloudinfo.PublicCloudInfoLite{}),
			ignoredFields: ignoredBecause(
				"lite shape is not used by the ztw/public-cloud-info resource",
				"id",
				"name",
				"accountId",
				"cloudType",
			),
		},
		{
			name:         "ztwzparesources.ZPAApplicationSegment",
			resource:     resources.ProductZTW,
			resourceName: resourceZTWZPAAppSegs,
			typ:          reflect.TypeOf(ztwzparesources.ZPAApplicationSegment{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"zpaId",
				"deleted",
			},
		},
		{
			name:         "ztwforwardingrules.ForwardingRules",
			resource:     resources.ProductZTW,
			resourceName: resourceForwardingRules,
			typ:          reflect.TypeOf(ztwforwardingrules.ForwardingRules{}),
			catalogFields: []string{
				"id",
				"name",
				"accessControl",
				"description",
				"type",
				"order",
				"rank",
				"forwardMethod",
				"defaultRule",
				"wanSelection",
				"state",
				"blockResponseCode",
				"lastModifiedTime",
				"srcIps",
				"destAddresses",
				"destIpCategories",
				"resCategories",
				"destCountries",
				"sourceCountries",
				"nwApplications",
				"sourceIpGroupExclusion",
				"zpaBrokerRule",
				"locations",
				"locationGroups",
				"ecGroups",
				"departments",
				"groups",
				"users",
				"lastModifiedBy",
				"srcIpGroups",
				"srcIpv6Groups",
				"destIpGroups",
				"destIpv6Groups",
				"nwServices",
				"nwServiceGroups",
				"labels",
				"nwApplicationGroups",
				"appServiceGroups",
				"srcWorkloadGroups",
				"proxyGateway",
				"zpaApplicationSegments",
				"zpaApplicationSegmentGroups",
			},
		},
		{
			name: "ztwforwardingrules.ZPAApplicationSegments",
			typ:  reflect.TypeOf(ztwforwardingrules.ZPAApplicationSegments{}),
			ignoredFields: ignoredBecause(
				"SDK-local duplicate; resource uses ztwcommon.ZPAApplicationSegments references",
				"id",
				"name",
				"description",
				"zpaId",
				"deleted",
			),
		},
		{
			name: "ztwforwardingrules.ZPAApplicationSegmentGroups",
			typ:  reflect.TypeOf(ztwforwardingrules.ZPAApplicationSegmentGroups{}),
			ignoredFields: ignoredBecause(
				"SDK-local duplicate; resource uses ztwcommon.ZPAApplicationSegmentGroups references",
				"id",
				"name",
				"zpaId",
				"deleted",
				"zpaAppSegmentsCount",
			),
		},
		{
			name: "ztwforwardingrules.ForwardingRulesQuery",
			typ:  reflect.TypeOf(ztwforwardingrules.ForwardingRulesQuery{}),
			ignoredFields: ignoredBecause(
				"query helper type, not a response shape",
				"RuleName",
				"RuleOrder",
				"RuleDescription",
				"RuleForwardMethod",
				"Location",
				"SortBy",
				"SortOrder",
			),
		},
		{
			name: "ztwforwardingrules.ForwardingRulesCountQuery",
			typ:  reflect.TypeOf(ztwforwardingrules.ForwardingRulesCountQuery{}),
			ignoredFields: ignoredBecause(
				"count query helper type, not a response shape",
				"PredefinedRuleCount",
				"RuleName",
				"RuleOrder",
				"RuleDescription",
				"RuleForwardMethod",
				"Location",
			),
		},
		{
			name: "ztwforwardingrules.ForwardingRulesCountResponse",
			typ:  reflect.TypeOf(ztwforwardingrules.ForwardingRulesCountResponse{}),
			ignoredFields: ignoredBecause(
				"count response is not rendered by the ztw/forwarding-rules resource",
				"count",
			),
		},
		{
			name:         "ztwtrafficdnsrules.ECDNSRules",
			resource:     resources.ProductZTW,
			resourceName: resourceTrafficDNSRules,
			typ:          reflect.TypeOf(ztwtrafficdnsrules.ECDNSRules{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"type",
				"action",
				"order",
				"rank",
				"state",
				"predefined",
				"defaultRule",
				"srcIps",
				"destAddresses",
				"locations",
				"locationGroups",
				"ecGroups",
				"srcIpGroups",
				"destIpGroups",
				"dnsGateway",
				"zpaIpGroup",
				"lastModifiedTime",
				"lastModifiedBy",
			},
		},
		{
			name: "ztwtrafficdnsrules.DNSRulesCountQuery",
			typ:  reflect.TypeOf(ztwtrafficdnsrules.DNSRulesCountQuery{}),
			ignoredFields: ignoredBecause(
				"count query helper type, not a response shape",
				"PredefinedRuleCount",
				"RuleName",
				"RuleOrder",
				"RuleDescription",
				"Location",
			),
		},
		{
			name: "ztwtrafficdnsrules.DNSRulesCountResponse",
			typ:  reflect.TypeOf(ztwtrafficdnsrules.DNSRulesCountResponse{}),
			ignoredFields: ignoredBecause(
				"count response is not rendered by the ztw/traffic-dns-rules resource",
				"count",
			),
		},
		{
			name:         "ztwtrafficlogrules.ECTrafficLogRules",
			resource:     resources.ProductZTW,
			resourceName: resourceTrafficLogRules,
			typ:          reflect.TypeOf(ztwtrafficlogrules.ECTrafficLogRules{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"order",
				"rank",
				"state",
				"type",
				"forwardMethod",
				"defaultRule",
				"locations",
				"proxyGateway",
				"lastModifiedTime",
				"lastModifiedBy",
				"ecGroups",
			},
		},
		{
			name: "ztwtrafficlogrules.TrafficLogRulesCountQuery",
			typ:  reflect.TypeOf(ztwtrafficlogrules.TrafficLogRulesCountQuery{}),
			ignoredFields: ignoredBecause(
				"unused count query helper type, not a response shape",
				"PredefinedRuleCount",
				"RuleName",
				"RuleOrder",
				"RuleDescription",
				"Location",
			),
		},
		{
			name: "ztwtrafficlogrules.TrafficLogRulesCountResponse",
			typ:  reflect.TypeOf(ztwtrafficlogrules.TrafficLogRulesCountResponse{}),
			ignoredFields: ignoredBecause(
				"unused count response helper type, not rendered by the ztw/traffic-log-rules resource",
				"count",
			),
		},
	}
}
