package zscaler

import (
	"reflect"

	"github.com/dvmrry/zscalerctl/internal/resources"

	activation "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/activation"
	ziaadminusers "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/adminuserrolemgmt/admins"
	ziaadminroles "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/adminuserrolemgmt/roles"
	advancedsettings "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/advanced_settings"
	advancedthreatsettings "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/advancedthreatsettings"
	"github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/alerts"
	authsettings "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/auth_settings"
	bandwidthclasses "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/bandwidth_control/bandwidth_classes"
	bandwidthcontrolrules "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/bandwidth_control/bandwidth_control_rules"
	browsercontrolsettings "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/browser_control_settings"
	browserisolation "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/browser_isolation"
	c2cincidentreceiver "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/c2c_incident_receiver"
	cloudappinstances "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/cloud_app_instances"
	cloudappcontrol "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/cloudappcontrol"
	cloudapplications "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/cloudapplications/cloudapplications"
	riskprofiles "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/cloudapplications/risk_profiles"
	cloudnss "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/cloudnss/cloudnss"
	nssservers "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/cloudnss/nss_servers"
	ziacommon "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/common"
	"github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/devicegroups"
	dlpengines "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/dlp/dlp_engines"
	dlpexactdatamatch "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/dlp/dlp_exact_data_match"
	dlpedmlite "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/dlp/dlp_exact_data_match_lite"
	dlpicapservers "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/dlp/dlp_icap_servers"
	dlpidmprofilelite "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/dlp/dlp_idm_profile_lite"
	dlpidmprofiles "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/dlp/dlp_idm_profiles"
	dlpincidentreceivers "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/dlp/dlp_incident_receiver_servers"
	dlpnotificationtemplates "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/dlp/dlp_notification_templates"
	dlpwebrules "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/dlp/dlp_web_rules"
	dlpdictionaries "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/dlp/dlpdictionaries"
	emailprofiles "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/email_profiles"
	endusernotification "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/end_user_notification"
	filetypecontrol "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/filetypecontrol"
	customfiletypes "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/filetypecontrol/custom_file_types"
	firewalldnscontrolpolicies "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/firewalldnscontrolpolicies"
	applicationservices "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/firewallpolicies/applicationservices"
	appservicegroups "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/firewallpolicies/appservicegroups"
	dnsgateways "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/firewallpolicies/dns_gateways"
	filteringrules "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/firewallpolicies/filteringrules"
	ipdestinationgroups "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/firewallpolicies/ipdestinationgroups"
	ipsourcegroups "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/firewallpolicies/ipsourcegroups"
	networkapplicationgroups "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/firewallpolicies/networkapplicationgroups"
	networkapplications "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/firewallpolicies/networkapplications"
	networkservicegroups "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/firewallpolicies/networkservicegroups"
	networkservices "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/firewallpolicies/networkservices"
	"github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/firewallpolicies/timewindow"
	forwardingrules "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/forwarding_control_policy/forwarding_rules"
	"github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/forwarding_control_policy/proxies"
	proxygateways "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/forwarding_control_policy/proxy_gateways"
	zpagateways "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/forwarding_control_policy/zpa_gateways"
	ftpcontrolpolicy "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/ftp_control_policy"
	intermediatecacertificates "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/intermediatecacertificates"
	ipspolicies "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/ips_control_policies/ips_policies"
	ipssignaturerules "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/ips_control_policies/ips_signature_rules"
	"github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/location/locationgroups"
	"github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/location/locationmanagement"
	malwareprotection "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/malware_protection"
	mobilethreatsettings "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/mobile_threat_settings"
	natcontrol "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/nat_control_policies"
	organizationdetails "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/organization_details"
	pacfiles "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/pacfiles"
	remoteassistance "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/remote_assistance"
	rulelabels "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/rule_labels"
	saassecurityapi "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/saas_security_api"
	casbdlprules "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/saas_security_api/casb_dlp_rules"
	casbmalwarerules "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/saas_security_api/casb_malware_rules"
	sandboxrules "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/sandbox/sandbox_rules"
	sandboxsettings "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/sandbox/sandbox_settings"
	securebrowsing "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/secure_browsing"
	securitypolicysettings "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/security_policy_settings"
	"github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/sslinspection"
	tenancyrestriction "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/tenancy_restriction"
	timeintervals "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/time_intervals"
	dcexclusions "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/trafficforwarding/dc_exclusions"
	gretunnels "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/trafficforwarding/gretunnels"
	ipv6config "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/trafficforwarding/ipv6_config"
	staticips "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/trafficforwarding/staticips"
	subclouds "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/trafficforwarding/sub_clouds"
	"github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/urlcategories"
	"github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/urlfilteringpolicies"
	userauthsettings "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/user_authentication_settings"
	userdepartments "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/usermanagement/departments"
	usergroups "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/usermanagement/groups"
	ziausers "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/usermanagement/users"
	vzenclusters "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/vzen_clusters"
	vzennodes "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/vzen_nodes"
	"github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/workloadgroups"
)

func reviewedSDKShapesZIA() []sdkShapeReview {
	return []sdkShapeReview{
		{
			name:         "locationmanagement.Locations",
			resource:     resources.ProductZIA,
			resourceName: resourceLocations,
			typ:          reflect.TypeOf(locationmanagement.Locations{}),
			catalogFields: []string{
				"id",
				"name",
				"parentId",
				"description",
				"country",
				"state",
				"tz",
				"language",
				"profile",
				"upBandwidth",
				"dnBandwidth",
				"ipAddresses",
				"ports",
				"vpnCredentials",
				"authRequired",
				"basicAuthEnabled",
				"digestAuthEnabled",
				"kerberosAuth",
				"sslScanEnabled",
				"zappSSLScanEnabled",
				"xffForwardEnabled",
				"surrogateIP",
				"surrogateIPEnforcedForKnownBrowsers",
				"idleTimeInMinutes",
				"surrogateRefreshTimeInMinutes",
				"ofwEnabled",
				"ipsControl",
				"aupEnabled",
				"cautionEnabled",
				"aupBlockInternetUntilAccepted",
				"aupForceSslInspection",
				"aupTimeoutInDays",
				"iotDiscoveryEnabled",
				"iotEnforcePolicySet",
				"cookiesAndProxy",
			},
			ignoredFields: mergeIgnoredFields(
				ignoredBecause(
					"sublocation scope semantics need separate modeling before exposure",
					"subLocScopeEnabled",
					"subLocScope",
					"subLocScopeValues",
					"subLocAccIds",
				),
				ignoredBecause(
					"UI display-unit hints carry no configuration signal",
					"displayTimeUnit",
					"surrogateRefreshTimeUnit",
				),
				ignoredBecause(
					"hierarchy and membership references are intentionally omitted until separately modeled",
					"childCount",
					"matchInChild",
					"excludeFromDynamicGroups",
					"excludeFromManualGroups",
					"otherSubLocation",
					"other6SubLocation",
					"ecLocation",
					"dynamiclocationGroups",
					"staticLocationGroups",
					"virtualZenClusters",
					"virtualZens",
				),
				ignoredBecause(
					"extranet and IPv6 operational references are intentionally omitted until separately classified",
					"geoOverride",
					"ipv6Enabled",
					"defaultExtranetTsPool",
					"defaultExtranetDns",
					"extranet",
					"extranetIpPool",
					"extranetDns",
					"ipv6Dns64Prefix",
				),
			),
		},
		{
			name: "locationmanagement.VPNCredentials",
			typ:  reflect.TypeOf(locationmanagement.VPNCredentials{}),
			ignoredFields: ignoredBecause(
				"covered by secret vpnCredentials parent; nested credential payload is never emitted",
				"id",
				"type",
				"fqdn",
				"ipAddress",
				"preSharedKey",
				"comments",
				"location",
				"managedBy",
			),
		},
		{
			name:         "locationgroups.LocationGroup",
			resource:     resources.ProductZIA,
			resourceName: resourceLocationGroups,
			typ:          reflect.TypeOf(locationgroups.LocationGroup{}),
			catalogFields: []string{
				"id",
				"name",
				"deleted",
				"groupType",
				"dynamicLocationGroupCriteria",
				"comments",
				"locations",
				"lastModTime",
				"predefined",
			},
			ignoredFields: ignoredBecause(
				"admin reference is mapped then dropped by projection",
				"lastModUser",
			),
		},
		{
			name:         "locationgroups.DynamicLocationGroupCriteria",
			resource:     resources.ProductZIA,
			resourceName: resourceLocationGroups,
			typ:          reflect.TypeOf(locationgroups.DynamicLocationGroupCriteria{}),
			catalogFields: []string{
				"name",
				"countries",
				"city",
				"managedBy",
				"enforceAuthentication",
				"enforceAup",
				"enforceFirewallControl",
				"enableXffForwarding",
				"enableCaution",
				"enableBandwidthControl",
				"profiles",
			},
		},
		{
			name:         "locationgroups.Name",
			resource:     resources.ProductZIA,
			resourceName: resourceLocationGroups,
			typ:          reflect.TypeOf(locationgroups.Name{}),
			catalogFields: []string{
				"matchString",
				"matchType",
			},
		},
		{
			name:         "locationgroups.City",
			resource:     resources.ProductZIA,
			resourceName: resourceLocationGroups,
			typ:          reflect.TypeOf(locationgroups.City{}),
			catalogFields: []string{
				"matchString",
				"matchType",
			},
		},
		{
			name:         "locationgroups.ManagedBy",
			resource:     resources.ProductZIA,
			resourceName: resourceLocationGroups,
			typ:          reflect.TypeOf(locationgroups.ManagedBy{}),
			catalogFields: []string{
				"id",
				"name",
				"extensions",
			},
		},
		{
			name: "locationgroups.LastModUser",
			typ:  reflect.TypeOf(locationgroups.LastModUser{}),
			ignoredFields: ignoredBecause(
				"covered by dropped lastModUser parent",
				"id",
				"name",
				"extensions",
			),
		},
		{
			name:         "rulelabels.RuleLabels",
			resource:     resources.ProductZIA,
			resourceName: resourceRuleLabels,
			typ:          reflect.TypeOf(rulelabels.RuleLabels{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"lastModifiedTime",
				"referencedRuleCount",
			},
			ignoredFields: ignoredBecause(
				"admin references are mapped then dropped by projection",
				"createdBy",
				"lastModifiedBy",
			),
		},
		{
			name:         "authsettings.AuthenticationSettings",
			resource:     resources.ProductZIA,
			resourceName: resourceAuthSettings,
			typ:          reflect.TypeOf(authsettings.AuthenticationSettings{}),
			catalogFields: []string{
				"orgAuthType",
				"oneTimeAuth",
				"samlEnabled",
				"kerberosEnabled",
				"kerberosPwd",
				"authFrequency",
				"authCustomFrequency",
				"passwordStrength",
				"passwordExpiry",
				"lastSyncStartTime",
				"lastSyncEndTime",
				"mobileAdminSamlIdpEnabled",
				"autoProvision",
				"directorySyncMigrateToScimEnabled",
			},
			ignoredFields: map[string]string{},
		},
		{
			name: "ziacommon.IDNameExtensions",
			typ:  reflect.TypeOf(ziacommon.IDNameExtensions{}),
			ignoredFields: ignoredBecause(
				"used inside modeled and dropped reference parents; parent catalog fields decide whether id/name can render",
				"id",
				"name",
				"extensions",
			),
		},
		{
			name: "ziacommon.IDCustom",
			typ:  reflect.TypeOf(ziacommon.IDCustom{}),
			ignoredFields: ignoredBecause(
				"used inside dropped or explicitly modeled custom ID references; parent catalog fields decide whether id/name can render",
				"id",
				"name",
			),
		},
		{
			name: "ziacommon.CommonNSS",
			typ:  reflect.TypeOf(ziacommon.CommonNSS{}),
			ignoredFields: ignoredBecause(
				"used inside dropped or explicitly modeled NSS feed references; parent catalog fields decide whether nested fields can render",
				"id",
				"pid",
				"name",
				"description",
				"deleted",
				"getlId",
			),
		},
		{
			name:         "staticips.StaticIP",
			resource:     resources.ProductZIA,
			resourceName: resourceStaticIPs,
			typ:          reflect.TypeOf(staticips.StaticIP{}),
			catalogFields: []string{
				"id",
				"ipAddress",
				"geoOverride",
				"latitude",
				"longitude",
				"routableIP",
				"city",
				"lastModificationTime",
				"comment",
			},
			ignoredFields: ignoredBecause(
				"nested admin references are mapped then dropped by projection",
				"managedBy",
				"lastModifiedBy",
			),
		},
		{
			name: "staticips.City",
			typ:  reflect.TypeOf(staticips.City{}),
			ignoredFields: ignoredBecause(
				"used inside the modeled city reference parent; parent catalog fields decide whether id/name can render",
				"id",
				"name",
			),
		},
		{
			name: "staticips.ManagedBy",
			typ:  reflect.TypeOf(staticips.ManagedBy{}),
			ignoredFields: ignoredBecause(
				"covered by dropped managedBy parent",
				"id",
				"name",
				"extensions",
			),
		},
		{
			name: "staticips.LastModifiedBy",
			typ:  reflect.TypeOf(staticips.LastModifiedBy{}),
			ignoredFields: ignoredBecause(
				"covered by dropped lastModifiedBy parent",
				"id",
				"name",
				"extensions",
			),
		},
		{
			name:         "gretunnels.GreTunnels",
			resource:     resources.ProductZIA,
			resourceName: resourceGRETunnels,
			typ:          reflect.TypeOf(gretunnels.GreTunnels{}),
			catalogFields: []string{
				"id",
				"sourceIp",
				"internalIpRange",
				"lastModificationTime",
				"withinCountry",
				"comment",
				"ipUnnumbered",
				"subcloud",
				"primaryDestVip",
				"secondaryDestVip",
			},
			ignoredFields: ignoredBecause(
				"nested admin identity references are mapped then dropped by projection",
				"managedBy",
				"lastModifiedBy",
			),
		},
		{
			name: "gretunnels.ManagedBy",
			typ:  reflect.TypeOf(gretunnels.ManagedBy{}),
			ignoredFields: ignoredBecause(
				"covered by dropped managedBy parent",
				"id",
				"name",
				"extensions",
			),
		},
		{
			name: "gretunnels.LastModifiedBy",
			typ:  reflect.TypeOf(gretunnels.LastModifiedBy{}),
			ignoredFields: ignoredBecause(
				"covered by dropped lastModifiedBy parent",
				"id",
				"name",
				"extensions",
			),
		},
		{
			name:         "gretunnels.PrimaryDestVip",
			resource:     resources.ProductZIA,
			resourceName: resourceGRETunnels,
			typ:          reflect.TypeOf(gretunnels.PrimaryDestVip{}),
			catalogFields: []string{
				"id",
				"virtualIp",
				"privateServiceEdge",
				"datacenter",
				"latitude",
				"longitude",
				"city",
				"countryCode",
				"region",
			},
		},
		{
			name:         "gretunnels.SecondaryDestVip",
			resource:     resources.ProductZIA,
			resourceName: resourceGRETunnels,
			typ:          reflect.TypeOf(gretunnels.SecondaryDestVip{}),
			catalogFields: []string{
				"id",
				"virtualIp",
				"privateServiceEdge",
				"datacenter",
				"latitude",
				"longitude",
				"city",
				"countryCode",
				"region",
			},
		},
		{
			name:         "locationmanagement.Locations/sublocations",
			resource:     resources.ProductZIA,
			resourceName: resourceSublocations,
			typ:          reflect.TypeOf(locationmanagement.Locations{}),
			catalogFields: []string{
				"id",
				"parentId",
				"name",
				"ipAddresses",
				"ports",
				"description",
				"profile",
				"country",
				"state",
				"tz",
				"authRequired",
				"sslScanEnabled",
				"ofwEnabled",
				"ipsControl",
				"vpnCredentials",
			},
			ignoredFields: mergeIgnoredFields(
				ignoredBecause(
					"additional bandwidth, auth, and policy controls are mapped then dropped until separately reviewed for sublocation output",
					"upBandwidth",
					"dnBandwidth",
					"language",
					"basicAuthEnabled",
					"digestAuthEnabled",
					"kerberosAuth",
					"iotDiscoveryEnabled",
					"iotEnforcePolicySet",
					"cookiesAndProxy",
					"zappSSLScanEnabled",
					"xffForwardEnabled",
					"surrogateIP",
					"idleTimeInMinutes",
					"displayTimeUnit",
					"surrogateIPEnforcedForKnownBrowsers",
					"surrogateRefreshTimeInMinutes",
					"surrogateRefreshTimeUnit",
					"aupEnabled",
					"cautionEnabled",
					"aupBlockInternetUntilAccepted",
					"aupForceSslInspection",
					"aupTimeoutInDays",
				),
				ignoredBecause(
					"hierarchy, scope, and group references are mapped then dropped until separately modeled",
					"childCount",
					"matchInChild",
					"subLocScopeEnabled",
					"subLocScope",
					"subLocScopeValues",
					"subLocAccIds",
					"excludeFromDynamicGroups",
					"excludeFromManualGroups",
					"otherSubLocation",
					"other6SubLocation",
					"ecLocation",
					"dynamiclocationGroups",
					"staticLocationGroups",
					"virtualZenClusters",
					"virtualZens",
				),
				ignoredBecause(
					"geo, extranet, and IPv6 references are mapped then dropped until separately classified",
					"geoOverride",
					"ipv6Enabled",
					"defaultExtranetTsPool",
					"defaultExtranetDns",
					"extranet",
					"extranetIpPool",
					"extranetDns",
					"ipv6Dns64Prefix",
				),
			),
		},
		{
			name:         "sslinspection.SSLInspectionRules",
			resource:     resources.ProductZIA,
			resourceName: resourceSSLRules,
			typ:          reflect.TypeOf(sslinspection.SSLInspectionRules{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"action",
				"state",
				"order",
				"rank",
				"urlCategories",
				"platforms",
				"cloudApplications",
				"lastModifiedTime",
				"defaultRule",
				"predefined",
				"roadWarriorForKerberos",
				"userAgentTypes",
				"deviceTrustLevels",
				"lastModifiedBy",
				"labels",
				"timeWindows",
				"locations",
				"locationGroups",
				"departments",
				"groups",
				"users",
				"deviceGroups",
				"devices",
				"destIpGroups",
				"sourceIpGroups",
				"proxyGateways",
				"zpaAppSegments",
				"workloadGroups",
			},
			ignoredFields: ignoredBecause(
				"admin RBA access metadata is mapped then dropped until separately modeled",
				"accessControl",
			),
		},
		{
			name: "sslinspection.Action",
			typ:  reflect.TypeOf(sslinspection.Action{}),
			ignoredFields: ignoredBecause(
				"nested action fields are mapped so the parent action object can render its reviewed type while unmodeled sub-actions and certificate references drop",
				"type",
				"showEUN",
				"showEUNATP",
				"overrideDefaultCertificate",
				"sslInterceptionCert",
				"decryptSubActions",
				"doNotDecryptSubActions",
			),
		},
		{
			name: "sslinspection.SSLInterceptionCert",
			typ:  reflect.TypeOf(sslinspection.SSLInterceptionCert{}),
			ignoredFields: ignoredBecause(
				"covered by dropped action.sslInterceptionCert parent",
				"id",
				"name",
				"defaultCertificate",
			),
		},
		{
			name: "sslinspection.DecryptSubActions",
			typ:  reflect.TypeOf(sslinspection.DecryptSubActions{}),
			ignoredFields: ignoredBecause(
				"covered by dropped action.decryptSubActions parent",
				"serverCertificates",
				"ocspCheck",
				"blockSslTrafficWithNoSniEnabled",
				"minClientTLSVersion",
				"minServerTLSVersion",
				"blockUndecrypt",
				"http2Enabled",
			),
		},
		{
			name: "sslinspection.DoNotDecryptSubActions",
			typ:  reflect.TypeOf(sslinspection.DoNotDecryptSubActions{}),
			ignoredFields: ignoredBecause(
				"covered by dropped action.doNotDecryptSubActions parent",
				"bypassOtherPolicies",
				"serverCertificates",
				"ocspCheck",
				"blockSslTrafficWithNoSniEnabled",
				"minTLSVersion",
			),
		},
		{
			name:         "urlcategories.URLCategory",
			resource:     resources.ProductZIA,
			resourceName: resourceURLCategories,
			typ:          reflect.TypeOf(urlcategories.URLCategory{}),
			catalogFields: []string{
				"id",
				"configuredName",
				"description",
				"type",
				"customCategory",
				"editable",
				"customUrlsCount",
				"customIpRangesCount",
				"urlsRetainingParentCategoryCount",
				"ipRangesRetainingParentCategoryCount",
				"categoryGroup",
				"superCategory",
				"urlType",
				"urlKeywordCounts",
				"keywords",
				"keywordsRetainingParentCategory",
				"urls",
				"dbCategorizedUrls",
				"ipRanges",
				"ipRangesRetainingParentCategory",
				"regexPatterns",
				"regexPatternsRetainingParentCategory",
			},
			ignoredFields: ignoredBecause(
				"scope and opaque SDK helper fields are mapped then dropped until separately classified",
				"scopes",
				"val",
			),
		},
		{
			name: "urlcategories.URLKeywordCounts",
			typ:  reflect.TypeOf(urlcategories.URLKeywordCounts{}),
			ignoredFields: ignoredBecause(
				"nested count fields are explicitly modeled in the url-categories catalog; this entry catches SDK additions",
				"totalUrlCount",
				"retainParentUrlCount",
				"totalKeywordCount",
				"retainParentKeywordCount",
			),
		},
		{
			name: "urlcategories.Scopes",
			typ:  reflect.TypeOf(urlcategories.Scopes{}),
			ignoredFields: ignoredBecause(
				"covered by dropped scopes parent",
				"scopeGroupMemberEntities",
				"Type",
				"ScopeEntities",
			),
		},
		{
			name:         "urlfilteringpolicies.URLFilteringRule",
			resource:     resources.ProductZIA,
			resourceName: resourceURLRules,
			typ:          reflect.TypeOf(urlfilteringpolicies.URLFilteringRule{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"state",
				"order",
				"rank",
				"action",
				"protocols",
				"requestMethods",
				"urlCategories",
				"urlCategories2",
				"userRiskScoreLevels",
				"userAgentTypes",
				"sourceCountries",
				"lastModifiedTime",
				"enforceTimeValidity",
				"validityStartTime",
				"validityEndTime",
				"validityTimeZoneId",
				"blockOverride",
				"timeQuota",
				"sizeQuota",
				"ciparule",
				"browserEunTemplateId",
				"endUserNotificationUrl",
				"cbiProfileId",
				"cbiProfile",
				"labels",
				"timeWindows",
				"locations",
				"locationGroups",
				"sourceIpGroups",
				"departments",
				"groups",
				"users",
				"deviceGroups",
				"devices",
				"overrideUsers",
				"overrideGroups",
				"workloadGroups",
			},
			ignoredFields: ignoredBecause(
				"admin modifier identity and device trust levels are mapped then dropped until separately modeled",
				"deviceTrustLevels",
				"lastModifiedBy",
			),
		},
		{
			name:         "filteringrules.FirewallFilteringRules",
			resource:     resources.ProductZIA,
			resourceName: resourceFirewallRules,
			typ:          reflect.TypeOf(filteringrules.FirewallFilteringRules{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"state",
				"order",
				"rank",
				"action",
				"accessControl",
				"enableFullLogging",
				"defaultRule",
				"predefined",
				"lastModifiedTime",
				"sourceCountries",
				"destCountries",
				"excludeSrcCountries",
				"nwApplications",
				"srcIps",
				"destAddresses",
				"destIpCategories",
				"deviceTrustLevels",
				"labels",
				"timeWindows",
				"locations",
				"locationGroups",
				"departments",
				"groups",
				"users",
				"srcIpGroups",
				"destIpGroups",
				"nwServices",
				"nwServiceGroups",
				"nwApplicationGroups",
				"appServices",
				"appServiceGroups",
				"deviceGroups",
				"devices",
				"zpaAppSegments",
				"workloadGroups",
			},
			ignoredFields: ignoredBecause(
				"admin references are mapped then dropped by projection",
				"lastModifiedBy",
			),
		},
		{
			name:         "forwardingrules.ForwardingRules",
			resource:     resources.ProductZIA,
			resourceName: resourceForwardingRules,
			typ:          reflect.TypeOf(forwardingrules.ForwardingRules{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"type",
				"state",
				"order",
				"rank",
				"forwardMethod",
				"lastModifiedTime",
				"zpaBrokerRule",
				"destCountries",
				"srcIps",
				"destAddresses",
				"destIpCategories",
				"resCategories",
				"labels",
				"locations",
				"locationGroups",
				"ecGroups",
				"srcIpGroups",
				"srcIpv6Groups",
				"destIpGroups",
				"destIpv6Groups",
				"nwServices",
				"nwServiceGroups",
				"nwApplicationGroups",
				"appServiceGroups",
				"proxyGateway",
				"dedicatedIPGateway",
				"zpaGateway",
				"departments",
				"deviceGroups",
				"groups",
				"lastModifiedBy",
				"users",
				"zpaAppSegments",
				"zpaApplicationSegments",
				"zpaApplicationSegmentGroups",
			},
		},
		{
			name: "ziacommon.CBIProfile",
			typ:  reflect.TypeOf(ziacommon.CBIProfile{}),
			ignoredFields: ignoredBecause(
				"modeled explicitly under the url-filtering-rules cbiProfile catalog field; parent catalog sub-fields decide whether id/name/profileSeq can render and keep url secret",
				"id",
				"name",
				"url",
				"profileSeq",
			),
		},
		{
			name: "forwardingrules.ZPAApplicationSegments",
			typ:  reflect.TypeOf(forwardingrules.ZPAApplicationSegments{}),
			ignoredFields: ignoredBecause(
				"covered by zia/forwarding-rules zpaApplicationSegments nested field",
				"id",
				"name",
				"description",
				"zpaId",
				"deleted",
			),
		},
		{
			name: "forwardingrules.ZPAApplicationSegmentGroups",
			typ:  reflect.TypeOf(forwardingrules.ZPAApplicationSegmentGroups{}),
			ignoredFields: ignoredBecause(
				"covered by zia/forwarding-rules zpaApplicationSegmentGroups nested field",
				"id",
				"name",
				"zpaId",
				"deleted",
				"zpaAppSegmentsCount",
			),
		},
		{
			name: "ziacommon.IDName",
			typ:  reflect.TypeOf(ziacommon.IDName{}),
			ignoredFields: ignoredBecause(
				"currently used only inside dropped or explicitly modeled nested references",
				"id",
				"name",
				"parent",
			),
		},
		{
			name: "ziacommon.ZPAAppSegments",
			typ:  reflect.TypeOf(ziacommon.ZPAAppSegments{}),
			ignoredFields: ignoredBecause(
				"covered by dropped zpaAppSegments parent",
				"id",
				"name",
				"externalId",
			),
		},
		{
			name:         "ipsourcegroups.IPSourceGroups",
			resource:     resources.ProductZIA,
			resourceName: resourceIPSourceGroups,
			typ:          reflect.TypeOf(ipsourcegroups.IPSourceGroups{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"ipAddresses",
				"isNonEditable",
			},
		},
		{
			name:         "ipdestinationgroups.IPDestinationGroups",
			resource:     resources.ProductZIA,
			resourceName: resourceIPDestGroups,
			typ:          reflect.TypeOf(ipdestinationgroups.IPDestinationGroups{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"type",
				"addresses",
				"ipCategories",
				"countries",
				"isNonEditable",
			},
		},
		{
			name:         "networkservices.NetworkServices",
			resource:     resources.ProductZIA,
			resourceName: resourceNetworkServices,
			typ:          reflect.TypeOf(networkservices.NetworkServices{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"tag",
				"type",
				"protocol",
				"isNameL10nTag",
				"srcTcpPorts",
				"destTcpPorts",
				"srcUdpPorts",
				"destUdpPorts",
			},
		},
		{
			name: "networkservices.NetworkPorts",
			typ:  reflect.TypeOf(networkservices.NetworkPorts{}),
			ignoredFields: ignoredBecause(
				"nested port ranges are explicitly modeled in network service catalog fields; this entry catches SDK additions",
				"start",
				"end",
			),
		},
		{
			name:         "networkservicegroups.NetworkServiceGroups",
			resource:     resources.ProductZIA,
			resourceName: resourceNetworkSvcGroups,
			typ:          reflect.TypeOf(networkservicegroups.NetworkServiceGroups{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"services",
			},
		},
		{
			name: "networkservicegroups.Services",
			typ:  reflect.TypeOf(networkservicegroups.Services{}),
			ignoredFields: ignoredBecause(
				"ZIA network service groups render child services as id/name references only; query network-services for service details",
				"id",
				"name",
				"tag",
				"srcTcpPorts",
				"destTcpPorts",
				"srcUdpPorts",
				"destUdpPorts",
				"type",
				"description",
				"isNameL10nTag",
			),
		},
		{
			name:         "networkapplications.NetworkApplications",
			resource:     resources.ProductZIA,
			resourceName: resourceNetworkApps,
			typ:          reflect.TypeOf(networkapplications.NetworkApplications{}),
			catalogFields: []string{
				"id",
				"parentCategory",
				"description",
				"deprecated",
			},
		},
		{
			name:         "applicationservices.ApplicationServicesLite",
			resource:     resources.ProductZIA,
			resourceName: resourceAppServices,
			typ:          reflect.TypeOf(applicationservices.ApplicationServicesLite{}),
			catalogFields: []string{
				"id",
				"name",
				"nameL10nTag",
			},
		},
		{
			name:         "appservicegroups.ApplicationServicesGroupLite",
			resource:     resources.ProductZIA,
			resourceName: resourceAppServiceGroups,
			typ:          reflect.TypeOf(appservicegroups.ApplicationServicesGroupLite{}),
			catalogFields: []string{
				"id",
				"name",
				"nameL10nTag",
			},
		},
		{
			name:         "networkapplicationgroups.NetworkApplicationGroups",
			resource:     resources.ProductZIA,
			resourceName: resourceNetworkAppGroups,
			typ:          reflect.TypeOf(networkapplicationgroups.NetworkApplicationGroups{}),
			catalogFields: []string{
				"id",
				"name",
				"networkApplications",
				"description",
			},
		},
		{
			name:         "timewindow.TimeWindow",
			resource:     resources.ProductZIA,
			resourceName: resourceTimeWindows,
			typ:          reflect.TypeOf(timewindow.TimeWindow{}),
			catalogFields: []string{
				"id",
				"name",
				"startTime",
				"endTime",
				"dayOfWeek",
			},
		},
		{
			name:         "proxies.Proxies",
			resource:     resources.ProductZIA,
			resourceName: resourceProxies,
			typ:          reflect.TypeOf(proxies.Proxies{}),
			catalogFields: []string{
				"id",
				"name",
				"type",
				"address",
				"port",
				"description",
				"insertXauHeader",
				"base64EncodeXauHeader",
				"cert",
				"lastModifiedTime",
			},
			ignoredFields: ignoredBecause(
				"admin references are mapped then dropped by projection",
				"lastModifiedBy",
			),
		},
		{
			name:         "proxygateways.ProxyGateways",
			resource:     resources.ProductZIA,
			resourceName: resourceProxyGateways,
			typ:          reflect.TypeOf(proxygateways.ProxyGateways{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"failClosed",
				"type",
				"primaryProxy",
				"secondaryProxy",
				"lastModifiedTime",
			},
			ignoredFields: ignoredBecause(
				"admin references are mapped then dropped by projection",
				"lastModifiedBy",
			),
		},
		{
			name:         "proxies.DedicatedIPGateways",
			resource:     resources.ProductZIA,
			resourceName: resourceDedicatedIPGWs,
			typ:          reflect.TypeOf(proxies.DedicatedIPGateways{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"primaryDataCenter",
				"secondaryDataCenter",
				"createTime",
				"lastModifiedTime",
				"default",
			},
			ignoredFields: ignoredBecause(
				"admin references are mapped then dropped by projection",
				"lastModifiedBy",
			),
		},
		{
			name:         "timeintervals.TimeInterval",
			resource:     resources.ProductZIA,
			resourceName: resourceTimeIntervals,
			typ:          reflect.TypeOf(timeintervals.TimeInterval{}),
			catalogFields: []string{
				"id",
				"name",
				"startTime",
				"endTime",
				"daysOfWeek",
			},
		},
		{
			name:         "bandwidthclasses.BandwidthClasses",
			resource:     resources.ProductZIA,
			resourceName: resourceBandwidthClasses,
			typ:          reflect.TypeOf(bandwidthclasses.BandwidthClasses{}),
			catalogFields: []string{
				"id",
				"isNameL10nTag",
				"name",
				"getfileSize",
				"fileSize",
				"type",
				"webApplications",
				"urls",
				"applicationServiceGroups",
				"networkApplications",
				"networkServices",
				"urlCategories",
				"applications",
			},
		},
		{
			name:         "bandwidthcontrolrules.BandwidthControlRules",
			resource:     resources.ProductZIA,
			resourceName: resourceBandwidthRules,
			typ:          reflect.TypeOf(bandwidthcontrolrules.BandwidthControlRules{}),
			catalogFields: []string{
				"id",
				"name",
				"order",
				"state",
				"description",
				"maxBandwidth",
				"minBandwidth",
				"rank",
				"lastModifiedTime",
				"accessControl",
				"defaultRule",
				"protocols",
				"deviceTrustLevels",
				"bandwidthClasses",
				"locationGroups",
				"labels",
				"devices",
				"deviceGroups",
				"locations",
				"timeWindows",
			},
			ignoredFields: ignoredBecause(
				"admin references are mapped then dropped by projection",
				"lastModifiedBy",
			),
		},
		{
			name:         "dnsgateways.DNSGateways",
			resource:     resources.ProductZIA,
			resourceName: resourceDNSGateways,
			typ:          reflect.TypeOf(dnsgateways.DNSGateways{}),
			catalogFields: []string{
				"id",
				"name",
				"dnsGatewayType",
				"primaryIpOrFqdn",
				"primaryPorts",
				"secondaryIpOrFqdn",
				"secondaryPorts",
				"protocols",
				"failureBehavior",
				"lastModifiedTime",
				"autoCreated",
				"natZtrGateway",
				"dnsGatewayProtocols",
			},
			ignoredFields: ignoredBecause(
				"admin references are mapped then dropped by projection",
				"lastModifiedBy",
			),
		},
		{
			name:         "natcontrol.NatControlPolicies",
			resource:     resources.ProductZIA,
			resourceName: resourceNATRules,
			typ:          reflect.TypeOf(natcontrol.NatControlPolicies{}),
			catalogFields: []string{
				"accessControl",
				"id",
				"name",
				"order",
				"rank",
				"description",
				"state",
				"redirectFqdn",
				"redirectIp",
				"redirectPort",
				"lastModifiedTime",
				"trustedResolverRule",
				"enableFullLogging",
				"predefined",
				"defaultRule",
				"destAddresses",
				"srcIps",
				"destCountries",
				"destIpCategories",
				"resCategories",
				"locations",
				"locationGroups",
				"groups",
				"departments",
				"users",
				"timeWindows",
				"srcIpGroups",
				"srcIpv6Groups",
				"destIpGroups",
				"destIpv6Groups",
				"nwServices",
				"nwServiceGroups",
				"devices",
				"deviceGroups",
				"labels",
			},
			ignoredFields: ignoredBecause(
				"admin references are mapped then dropped by projection",
				"lastModifiedBy",
			),
		},
		{
			name:         "usergroups.Groups",
			resource:     resources.ProductZIA,
			resourceName: resourceGroups,
			typ:          reflect.TypeOf(usergroups.Groups{}),
			catalogFields: []string{
				"id",
				"name",
				"idpId",
				"comments",
				"isSystemDefined",
			},
		},
		{
			name:         "userdepartments.Department",
			resource:     resources.ProductZIA,
			resourceName: resourceDepartments,
			typ:          reflect.TypeOf(userdepartments.Department{}),
			catalogFields: []string{
				"id",
				"name",
				"idpId",
				"comments",
				"deleted",
			},
		},
		{
			name:         "ziausers.Users",
			resource:     resources.ProductZIA,
			resourceName: resourceUsers,
			typ:          reflect.TypeOf(ziausers.Users{}),
			catalogFields: []string{
				"id",
				"name",
				"email",
				"groups",
				"department",
				"comments",
				"tempAuthEmail",
				"authMethods",
				"password",
				"adminUser",
				"type",
				"deleted",
			},
		},
		{
			name:         "ziacommon.UserGroups (users)",
			resource:     resources.ProductZIA,
			resourceName: resourceUsers,
			typ:          reflect.TypeOf(ziacommon.UserGroups{}),
			catalogFields: []string{
				"id",
				"name",
			},
			ignoredFields: ignoredBecause(
				"user group references under zia/users render id/name only; query zia/groups for group metadata",
				"idp_id",
				"comments",
				"isSystemDefined",
			),
		},
		{
			name:         "ziacommon.UserDepartment (users)",
			resource:     resources.ProductZIA,
			resourceName: resourceUsers,
			typ:          reflect.TypeOf(ziacommon.UserDepartment{}),
			catalogFields: []string{
				"id",
				"name",
			},
			ignoredFields: ignoredBecause(
				"user department reference under zia/users renders id/name only; query zia/departments for department metadata",
				"idp_id",
				"comments",
				"deleted",
			),
		},
		{
			name:         "devicegroups.DeviceGroups",
			resource:     resources.ProductZIA,
			resourceName: resourceDeviceGroups,
			typ:          reflect.TypeOf(devicegroups.DeviceGroups{}),
			catalogFields: []string{
				"id",
				"name",
				"groupType",
				"description",
				"osType",
				"predefined",
				"deviceNames",
				"deviceCount",
			},
		},
		{
			name:         "devicegroups.Devices",
			resource:     resources.ProductZIA,
			resourceName: resourceDevices,
			typ:          reflect.TypeOf(devicegroups.Devices{}),
			catalogFields: []string{
				"id",
				"name",
				"deviceGroupType",
				"deviceModel",
				"osType",
				"osVersion",
				"description",
				"ownerUserId",
				"ownerName",
				"hostName",
			},
		},
		{
			name:         "workloadgroups.WorkloadGroup",
			resource:     resources.ProductZIA,
			resourceName: resourceWorkloadGroups,
			typ:          reflect.TypeOf(workloadgroups.WorkloadGroup{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"expression",
				"lastModifiedTime",
			},
			ignoredFields: mergeIgnoredFields(
				ignoredBecause(
					"excluded forever: JSON twin of the already-classified expression string; modeling the tree would duplicate (or widen) the standard-only expression exposure",
					"expressionJson",
				),
				ignoredBecause(
					"admin identity reference is mapped then dropped by projection",
					"lastModifiedBy",
				),
			),
		},
		{
			name:         "alerts.AlertSubscriptions",
			resource:     resources.ProductZIA,
			resourceName: resourceAlertSubs,
			typ:          reflect.TypeOf(alerts.AlertSubscriptions{}),
			catalogFields: []string{
				"id",
				"description",
				"email",
				"deleted",
				"pt0Severities",
				"secureSeverities",
				"manageSeverities",
				"complySeverities",
				"systemSeverities",
			},
		},
		{
			name:         "activation.Activation",
			resource:     resources.ProductZIA,
			resourceName: resourceActivationStatus,
			typ:          reflect.TypeOf(activation.Activation{}),
			catalogFields: []string{
				"status",
			},
		},
		{
			name:         "activation.ZiaEusaStatus",
			resource:     resources.ProductZIA,
			resourceName: resourceEUSAStatus,
			typ:          reflect.TypeOf(activation.ZiaEusaStatus{}),
			catalogFields: []string{
				"id",
				"version",
				"acceptedStatus",
			},
		},
		{
			name:         "userauthsettings.ExemptedUrls",
			resource:     resources.ProductZIA,
			resourceName: resourceAuthExemptedURLs,
			typ:          reflect.TypeOf(userauthsettings.ExemptedUrls{}),
			catalogFields: []string{
				"urls",
			},
		},
		{
			name:         "intermediatecacertificates.IntermediateCACertificate",
			resource:     resources.ProductZIA,
			resourceName: resourceIntermediateCAs,
			typ:          reflect.TypeOf(intermediatecacertificates.IntermediateCACertificate{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"type",
				"region",
				"status",
				"defaultCertificate",
				"certStartDate",
				"certExpDate",
				"currentState",
				"publicKey",
				"keyGenerationTime",
				"hsmAttestationVerifiedTime",
				"csrFileName",
				"csrGenerationTime",
			},
		},
		{
			name:         "cloudappinstances.CloudApplicationInstances",
			resource:     resources.ProductZIA,
			resourceName: resourceCloudAppInsts,
			typ:          reflect.TypeOf(cloudappinstances.CloudApplicationInstances{}),
			catalogFields: []string{
				"instanceId",
				"instanceType",
				"instanceName",
				"modifiedAt",
				"modifiedBy",
				"instanceIdentifiers",
			},
		},
		{
			name: "cloudappinstances.InstanceIdentifiers",
			typ:  reflect.TypeOf(cloudappinstances.InstanceIdentifiers{}),
			ignoredFields: ignoredBecause(
				"covered by dropped instanceIdentifiers parent",
				"instanceId",
				"instanceIdentifier",
				"instanceIdentifierName",
				"identifierType",
				"modifiedAt",
				"modifiedBy",
			),
		},
		{
			name:         "tenancyrestriction.TenancyRestrictionProfile",
			resource:     resources.ProductZIA,
			resourceName: resourceTenancyProfiles,
			typ:          reflect.TypeOf(tenancyrestriction.TenancyRestrictionProfile{}),
			catalogFields: []string{
				"id",
				"name",
				"appType",
				"description",
				"itemTypePrimary",
				"itemTypeSecondary",
				"restrictPersonalO365Domains",
				"allowGoogleConsumers",
				"msLoginServicesTrV2",
				"allowGoogleVisitors",
				"allowGcpCloudStorageRead",
				"itemDataPrimary",
				"itemDataSecondary",
				"itemValue",
				"lastModifiedTime",
				"lastModifiedUserId",
			},
		},
		{
			name:         "vzenclusters.VZENClusters",
			resource:     resources.ProductZIA,
			resourceName: resourceVZENClusters,
			typ:          reflect.TypeOf(vzenclusters.VZENClusters{}),
			catalogFields: []string{
				"id",
				"name",
				"status",
				"ipAddress",
				"subnetMask",
				"defaultGateway",
				"type",
				"ipSecEnabled",
				"virtualZenNodes",
			},
		},
		{
			name:         "vzennodes.VZENNodes",
			resource:     resources.ProductZIA,
			resourceName: resourceVZENNodes,
			typ:          reflect.TypeOf(vzennodes.VZENNodes{}),
			catalogFields: []string{
				"id",
				"zgatewayId",
				"name",
				"status",
				"inProduction",
				"ipAddress",
				"subnetMask",
				"defaultGateway",
				"type",
				"ipSecEnabled",
				"onDemandSupportTunnelEnabled",
				"establishSupportTunnelEnabled",
				"loadBalancerIpAddress",
				"deploymentMode",
				"clusterName",
				"vzenSkuType",
			},
		},
		{
			name:         "dlpicapservers.DLPICAPServers",
			resource:     resources.ProductZIA,
			resourceName: resourceDLPICAPServers,
			typ:          reflect.TypeOf(dlpicapservers.DLPICAPServers{}),
			catalogFields: []string{
				"id",
				"name",
				"url",
				"status",
			},
		},
		{
			name:         "dlpengines.DLPEngines",
			resource:     resources.ProductZIA,
			resourceName: resourceDLPEngines,
			typ:          reflect.TypeOf(dlpengines.DLPEngines{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"predefinedEngineName",
				"engineExpression",
				"customDlpEngine",
			},
		},
		{
			name:         "dlpdictionaries.DlpDictionary",
			resource:     resources.ProductZIA,
			resourceName: resourceDLPDictionaries,
			typ:          reflect.TypeOf(dlpdictionaries.DlpDictionary{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"confidenceThreshold",
				"customPhraseMatchType",
				"nameL10nTag",
				"custom",
				"thresholdType",
				"dictionaryType",
				"proximity",
				"phrases",
				"patterns",
				"exactDataMatchDetails",
				"idmProfileMatchAccuracyDetails",
				"ignoreExactMatchIdmDict",
				"includeBinNumbers",
				"binNumbers",
				"dictTemplateId",
				"predefinedClone",
				"predefinedCountActionType",
				"proximityLengthEnabled",
				"proximityEnabledForCustomDictionary",
				"dictionaryCloningEnabled",
				"customPhraseSupported",
				"hierarchicalDictionary",
				"hierarchicalIdentifiers",
				"predefinedPhrases",
				"thresholdAllowed",
				"confidenceLevelForPredefinedDict",
			},
		},
		{
			name:         "dlpexactdatamatch.DLPEDMSchema",
			resource:     resources.ProductZIA,
			resourceName: resourceDLPEDMSchemas,
			typ:          reflect.TypeOf(dlpexactdatamatch.DLPEDMSchema{}),
			catalogFields: []string{
				"schemaId",
				"edmClient",
				"projectName",
				"revision",
				"filename",
				"originalFileName",
				"fileUploadStatus",
				"schemaStatus",
				"origColCount",
				"lastModifiedTime",
				"modifiedBy",
				"createdBy",
				"cellsUsed",
				"schemaActive",
				"schedulePresent",
				"tokenList",
				"schedule",
			},
		},
		{
			name:         "browserisolation.CBIProfile",
			resource:     resources.ProductZIA,
			resourceName: resourceBrowserIsolation,
			typ:          reflect.TypeOf(browserisolation.CBIProfile{}),
			catalogFields: []string{
				"id",
				"name",
				"url",
				"defaultProfile",
			},
		},
		{
			name:         "dlpedmlite.DLPEDMLite",
			resource:     resources.ProductZIA,
			resourceName: resourceDLPEDMLite,
			typ:          reflect.TypeOf(dlpedmlite.DLPEDMLite{}),
			catalogFields: []string{
				"schema",
				"tokenList",
			},
		},
		{
			name:         "dcexclusions.DCExclusions",
			resource:     resources.ProductZIA,
			resourceName: resourceDCExclusions,
			typ:          reflect.TypeOf(dcexclusions.DCExclusions{}),
			catalogFields: []string{
				"dcid",
				"expired",
				"startTime",
				"endTime",
				"description",
				"dcName",
			},
		},
		{
			name:         "subclouds.SubClouds",
			resource:     resources.ProductZIA,
			resourceName: resourceSubClouds,
			typ:          reflect.TypeOf(subclouds.SubClouds{}),
			catalogFields: []string{
				"id",
				"name",
				"dcs",
				"exclusions",
			},
		},
		{
			name:         "ipv6config.IPv6Config",
			resource:     resources.ProductZIA,
			resourceName: resourceIPv6Config,
			typ:          reflect.TypeOf(ipv6config.IPv6Config{}),
			catalogFields: []string{
				"ipV6Enabled",
				"natPrefixes",
				"dnsPrefix",
			},
		},
		{
			name:         "ipv6config.IPv6ConfigPrefix (dns64)",
			resource:     resources.ProductZIA,
			resourceName: resourceIPv6DNS64Prefix,
			typ:          reflect.TypeOf(ipv6config.IPv6ConfigPrefix{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"prefixMask",
				"dnsPrefix",
				"nonEditable",
			},
		},
		{
			name:         "ipv6config.IPv6ConfigPrefix (nat64)",
			resource:     resources.ProductZIA,
			resourceName: resourceIPv6NAT64Prefix,
			typ:          reflect.TypeOf(ipv6config.IPv6ConfigPrefix{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"prefixMask",
				"dnsPrefix",
				"nonEditable",
			},
		},
		{
			name:         "pacfiles.PACFileConfig",
			resource:     resources.ProductZIA,
			resourceName: resourcePACFiles,
			typ:          reflect.TypeOf(pacfiles.PACFileConfig{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"domain",
				"pacUrl",
				"pacContent",
				"editable",
				"pacSubURL",
				"pacUrlObfuscated",
				"pacVerificationStatus",
				"pacVersionStatus",
				"pacVersion",
				"pacCommitMessage",
				"totalHits",
				"lastModificationTime",
				"lastModifiedBy",
				"createTime",
			},
		},
		{
			name:         "cloudappcontrol.WebApplicationRules",
			resource:     resources.ProductZIA,
			resourceName: resourceCloudAppControl,
			typ:          reflect.TypeOf(cloudappcontrol.WebApplicationRules{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"actions",
				"state",
				"rank",
				"type",
				"order",
				"timeQuota",
				"sizeQuota",
				"cascadingEnabled",
				"accessControl",
				"applications",
				"numberOfApplications",
				"eunEnabled",
				"eunTemplateId",
				"browserEunTemplateId",
				"predefined",
				"validityStartTime",
				"validityEndTime",
				"validityTimeZoneId",
				"userAgentTypes",
				"lastModifiedTime",
				"enforceTimeValidity",
				"deviceTrustLevels",
				"userRiskScoreLevels",
				"labels",
				"timeWindows",
				"locations",
				"locationGroups",
				"tenancyProfileIds",
			},
			ignoredFields: ignoredBecause(
				"user/group/device references and nested instance/profile structures are held until separately modeled",
				"cbiProfile",
				"cloudAppInstances",
				"cloudAppRiskProfile",
				"departments",
				"deviceGroups",
				"devices",
				"groups",
				"users",
			),
		},
		{
			name:         "cloudapplications.CloudApplications (policy)",
			resource:     resources.ProductZIA,
			resourceName: resourceCloudAppPolicy,
			typ:          reflect.TypeOf(cloudapplications.CloudApplications{}),
			catalogFields: []string{
				"app",
				"appName",
				"parent",
				"parentName",
			},
		},
		{
			name:         "cloudapplications.CloudApplications (ssl policy)",
			resource:     resources.ProductZIA,
			resourceName: resourceCloudAppSSLPol,
			typ:          reflect.TypeOf(cloudapplications.CloudApplications{}),
			catalogFields: []string{
				"app",
				"appName",
				"parent",
				"parentName",
			},
		},
		{
			name:         "saassecurityapi.DomainProfiles",
			resource:     resources.ProductZIA,
			resourceName: resourceDomainProfiles,
			typ:          reflect.TypeOf(saassecurityapi.DomainProfiles{}),
			catalogFields: []string{
				"profileId",
				"profileName",
				"includeCompanyDomains",
				"includeSubdomains",
				"description",
				"customDomains",
				"predefinedEmailDomains",
			},
		},
		{
			name:         "saassecurityapi.QuarantineTombstoneLite",
			resource:     resources.ProductZIA,
			resourceName: resourceCASBTombstones,
			typ:          reflect.TypeOf(saassecurityapi.QuarantineTombstoneLite{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
			},
		},
		{
			name:         "saassecurityapi.CasbEmailLabel",
			resource:     resources.ProductZIA,
			resourceName: resourceCASBEmailLabels,
			typ:          reflect.TypeOf(saassecurityapi.CasbEmailLabel{}),
			catalogFields: []string{
				"id",
				"name",
				"labelDesc",
				"labelColor",
				"labelDeleted",
			},
		},
		{
			name:         "saassecurityapi.CasbTenants",
			resource:     resources.ProductZIA,
			resourceName: resourceCASBTenants,
			typ:          reflect.TypeOf(saassecurityapi.CasbTenants{}),
			catalogFields: []string{
				"tenantId",
				"modifiedTime",
				"lastTenantValidationTime",
				"tenantDeleted",
				"tenantWebhookEnabled",
				"reAuth",
				"featuresSupported",
				"status",
				"enterpriseTenantId",
				"tenantName",
				"saasApplication",
				"zscalerAppTenantId",
			},
		},
		{
			name:         "casbdlprules.CasbDLPRules",
			resource:     resources.ProductZIA,
			resourceName: resourceCASBDLPRules,
			typ:          reflect.TypeOf(casbdlprules.CasbDLPRules{}),
			catalogFields: []string{
				"type",
				"id",
				"order",
				"rank",
				"lastModifiedTime",
				"name",
				"state",
				"action",
				"severity",
				"description",
				"bucketOwner",
				"externalAuditorEmail",
				"contentLocation",
				"numberOfInternalCollaborators",
				"numberOfExternalCollaborators",
				"recipient",
				"quarantineLocation",
				"accessControl",
				"watermarkDeleteOldVersion",
				"includeCriteriaDomainProfile",
				"includeEmailRecipientProfile",
				"withoutContentInspection",
				"includeEntityGroups",
				"fileTypes",
				"collaborationScope",
				"domains",
				"components",
				"deviceTrustLevels",
				"objectTypes",
				"buckets",
				"labels",
				"includedDomainProfiles",
				"excludedDomainProfiles",
				"criteriaDomainProfiles",
				"emailRecipientProfiles",
				"devices",
				"deviceGroups",
				"entityGroups",
				"cloudAppTenants",
				"users",
				"groups",
				"departments",
				"dlpEngines",
				"lastModifiedBy",
				"auditor",
				"zscalerIncidentReceiver",
				"auditorNotification",
				"tag",
				"watermarkProfile",
				"redactionProfile",
				"casbEmailLabel",
				"casbTombstoneTemplate",
				"receiver",
			},
		},
		{
			name:         "casbmalwarerules.CasbMalwareRules",
			resource:     resources.ProductZIA,
			resourceName: resourceCASBMalwareRules,
			typ:          reflect.TypeOf(casbmalwarerules.CasbMalwareRules{}),
			catalogFields: []string{
				"type",
				"id",
				"order",
				"name",
				"state",
				"action",
				"quarantineLocation",
				"scanInboundEmailLink",
				"lastModifiedTime",
				"accessControl",
				"lastModifiedBy",
				"casbEmailLabel",
				"casbTombstoneTemplate",
				"buckets",
				"labels",
				"cloudAppTenantIds",
				"cloudAppTenants",
				"cloudApplicationTenant",
			},
		},
		{
			name:         "browsercontrolsettings.BrowserControlSettings",
			resource:     resources.ProductZIA,
			resourceName: resourceBrowserControl,
			typ:          reflect.TypeOf(browsercontrolsettings.BrowserControlSettings{}),
			catalogFields: []string{
				"pluginCheckFrequency",
				"bypassPlugins",
				"bypassApplications",
				"blockedInternetExplorerVersions",
				"blockedChromeVersions",
				"blockedFirefoxVersions",
				"blockedSafariVersions",
				"blockedOperaVersions",
				"smartIsolationUsers",
				"smartIsolationGroups",
				"smartIsolationProfile",
				"bypassAllBrowsers",
				"allowAllBrowsers",
				"enableWarnings",
				"enableSmartBrowserIsolation",
				"smartIsolationProfileId",
			},
		},
		{
			name:         "securebrowsing.SupportedBrowserVersion",
			resource:     resources.ProductZIA,
			resourceName: resourceSupportedBrowsers,
			typ:          reflect.TypeOf(securebrowsing.SupportedBrowserVersion{}),
			catalogFields: []string{
				"browserType",
				"versions",
				"olderVersions",
			},
		},
		{
			name:         "ftpcontrolpolicy.FTPControlPolicy",
			resource:     resources.ProductZIA,
			resourceName: resourceFTPControl,
			typ:          reflect.TypeOf(ftpcontrolpolicy.FTPControlPolicy{}),
			catalogFields: []string{
				"ftpOverHttpEnabled",
				"ftpEnabled",
				"urlCategories",
				"urls",
			},
		},
		{
			name:         "remoteassistance.RemoteAssistance",
			resource:     resources.ProductZIA,
			resourceName: resourceRemoteAssistance,
			typ:          reflect.TypeOf(remoteassistance.RemoteAssistance{}),
			catalogFields: []string{
				"viewOnlyUntil",
				"fullAccessUntil",
				"usernameObfuscated",
				"deviceInfoObfuscate",
			},
		},
		{
			name:         "ziaadminusers.AdminUsers",
			resource:     resources.ProductZIA,
			resourceName: resourceAdminUsers,
			typ:          reflect.TypeOf(ziaadminusers.AdminUsers{}),
			catalogFields: []string{
				"id",
				"loginName",
				"userName",
				"email",
				"comments",
				"disabled",
				"password",
				"pwdLastModifiedTime",
				"isNonEditable",
				"isPasswordLoginAllowed",
				"isPasswordExpired",
				"isAuditor",
				"isSecurityReportCommEnabled",
				"isServiceUpdateCommEnabled",
				"isProductUpdateCommEnabled",
				"isExecMobileAppEnabled",
				"adminScopescopeGroupMemberEntities",
				"adminScopeScopeEntities",
				"adminScopeType",
				"role",
				"execMobileAppTokens",
			},
		},
		{
			name:         "ziaadminroles.AdminRoles",
			resource:     resources.ProductZIA,
			resourceName: resourceAdminRoles,
			typ:          reflect.TypeOf(ziaadminroles.AdminRoles{}),
			catalogFields: []string{
				"id",
				"rank",
				"name",
				"policyAccess",
				"alertingAccess",
				"usernameAccess",
				"deviceInfoAccess",
				"dashboardAccess",
				"reportAccess",
				"analysisAccess",
				"adminAcctAccess",
				"isAuditor",
				"permissions",
				"featurePermissions",
				"extFeaturePermissions",
				"isNonEditable",
				"logsLimit",
				"roleType",
				"reportTimeDuration",
			},
		},
		{
			name:         "dlpidmprofilelite.DLPIDMProfileLite",
			resource:     resources.ProductZIA,
			resourceName: resourceDLPIDMLite,
			typ:          reflect.TypeOf(dlpidmprofilelite.DLPIDMProfileLite{}),
			catalogFields: []string{
				"profileId",
				"templateName",
				"clientVm",
				"numDocuments",
				"lastModifiedTime",
				"modifiedBy",
			},
		},
		{
			name:         "dlpidmprofiles.DLPIDMProfile",
			resource:     resources.ProductZIA,
			resourceName: resourceDLPIDMProfiles,
			typ:          reflect.TypeOf(dlpidmprofiles.DLPIDMProfile{}),
			catalogFields: []string{
				"profileId",
				"profileName",
				"profileDesc",
				"profileType",
				"host",
				"port",
				"profileDirPath",
				"scheduleType",
				"scheduleDay",
				"scheduleDayOfMonth",
				"scheduleDayOfWeek",
				"scheduleTime",
				"scheduleDisabled",
				"uploadStatus",
				"userName",
				"version",
				"idmClient",
				"volumeOfDocuments",
				"numDocuments",
				"lastModifiedTime",
				"modifiedBy",
			},
		},
		{
			name:         "dlpwebrules.WebDLPRules",
			resource:     resources.ProductZIA,
			resourceName: resourceDLPWebRules,
			typ:          reflect.TypeOf(dlpwebrules.WebDLPRules{}),
			catalogFields: []string{
				"id",
				"order",
				"accessControl",
				"protocols",
				"rank",
				"name",
				"description",
				"fileTypes",
				"cloudApplications",
				"minSize",
				"action",
				"state",
				"matchOnly",
				"lastModifiedTime",
				"withoutContentInspection",
				"ocrEnabled",
				"dlpDownloadScanEnabled",
				"zccNotificationsEnabled",
				"zscalerIncidentReceiver",
				"eunTemplateId",
				"externalAuditorEmail",
				"auditor",
				"lastModifiedBy",
				"notificationTemplate",
				"icapServer",
				"receiver",
				"locations",
				"locationGroups",
				"groups",
				"departments",
				"users",
				"urlCategories",
				"dlpEngines",
				"timeWindows",
				"labels",
				"excludedGroups",
				"excludedDepartments",
				"excludedUsers",
				"includedDomainProfiles",
				"excludedDomainProfiles",
				"sourceIpGroups",
				"workloadGroups",
				"fileTypeCategories",
				"severity",
				"parentRule",
				"subRules",
				"userRiskScoreLevels",
				"dlpContentLocationsScopes",
				"inspectHttpGetEnabled",
			},
		},
		{
			name:         "dlpincidentreceivers.IncidentReceiverServers",
			resource:     resources.ProductZIA,
			resourceName: resourceDLPIncidentRcvs,
			typ:          reflect.TypeOf(dlpincidentreceivers.IncidentReceiverServers{}),
			catalogFields: []string{
				"id",
				"name",
				"url",
				"status",
				"flags",
			},
		},
		{
			name:         "dlpnotificationtemplates.DlpNotificationTemplates",
			resource:     resources.ProductZIA,
			resourceName: resourceDLPNotifyTmpls,
			typ:          reflect.TypeOf(dlpnotificationtemplates.DlpNotificationTemplates{}),
			catalogFields: []string{
				"id",
				"name",
				"subject",
				"attachContent",
				"plainTextMessage",
				"htmlMessage",
				"tlsEnabled",
			},
		},
		{
			name:         "c2cincidentreceiver.C2CIncidentReceiver",
			resource:     resources.ProductZIA,
			resourceName: resourceC2CIncidentRcvs,
			typ:          reflect.TypeOf(c2cincidentreceiver.C2CIncidentReceiver{}),
			catalogFields: []string{
				"id",
				"name",
				"status",
				"modifiedTime",
				"lastTenantValidationTime",
				"lastValidationMsg",
				"lastModifiedBy",
				"onboardableEntity",
			},
		},
		{
			name:         "filetypecontrol.FileTypeRules",
			resource:     resources.ProductZIA,
			resourceName: resourceFileTypeRules,
			typ:          reflect.TypeOf(filetypecontrol.FileTypeRules{}),
			catalogFields: []string{
				"accessControl",
				"activeContent",
				"browserEunTemplateId",
				"capturePCAP",
				"cloudApplications",
				"departments",
				"description",
				"deviceGroups",
				"deviceTrustLevels",
				"devices",
				"fileTypes",
				"filteringAction",
				"groups",
				"id",
				"labels",
				"lastModifiedBy",
				"lastModifiedTime",
				"locationGroups",
				"locations",
				"maxSize",
				"minSize",
				"name",
				"operation",
				"order",
				"passwordProtected",
				"protocols",
				"rank",
				"sizeQuota",
				"state",
				"timeQuota",
				"timeWindows",
				"unscannable",
				"urlCategories",
				"users",
				"zpaAppSegments",
			},
		},
		{
			name:         "sandboxrules.SandboxRules",
			resource:     resources.ProductZIA,
			resourceName: resourceSandboxRules,
			typ:          reflect.TypeOf(sandboxrules.SandboxRules{}),
			catalogFields: []string{
				"accessControl",
				"baPolicyCategories",
				"baRuleAction",
				"byThreatScore",
				"defaultRule",
				"departments",
				"description",
				"deviceGroups",
				"devices",
				"fileTypes",
				"firstTimeEnable",
				"firstTimeOperation",
				"groups",
				"id",
				"labels",
				"lastModifiedBy",
				"lastModifiedTime",
				"locationGroups",
				"locations",
				"mlActionEnabled",
				"name",
				"order",
				"protocols",
				"rank",
				"state",
				"timeWindows",
				"urlCategories",
				"users",
				"zpaAppSegments",
			},
		},
		{
			name:         "firewalldnscontrolpolicies.FirewallDNSRules",
			resource:     resources.ProductZIA,
			resourceName: resourceFirewallDNSRules,
			typ:          reflect.TypeOf(firewalldnscontrolpolicies.FirewallDNSRules{}),
			catalogFields: []string{
				"accessControl",
				"action",
				"applicationGroups",
				"applications",
				"blockResponseCode",
				"capturePCAP",
				"defaultDnsRuleNameUsed",
				"defaultRule",
				"departments",
				"description",
				"destAddresses",
				"destCountries",
				"destIpCategories",
				"destIpGroups",
				"destIpv6Groups",
				"deviceGroups",
				"devices",
				"dnsGateway",
				"dnsRuleRequestTypes",
				"ednsEcsObject",
				"groups",
				"id",
				"isWebEunEnabled",
				"labels",
				"lastModifiedBy",
				"lastModifiedTime",
				"locationGroups",
				"locations",
				"name",
				"order",
				"predefined",
				"protocols",
				"rank",
				"redirectIp",
				"resCategories",
				"sourceCountries",
				"srcIpGroups",
				"srcIps",
				"srcIpv6Groups",
				"state",
				"timeWindows",
				"users",
				"zpaIpGroup",
			},
		},
		{
			name:         "ips_signature_rules.IPSSignatureRules",
			resource:     resources.ProductZIA,
			resourceName: resourceIPSSignatureRules,
			typ:          reflect.TypeOf(ipssignaturerules.IPSSignatureRules{}),
			catalogFields: []string{
				"id",
				"name",
				"ruleText",
				"description",
				"category",
				"enabled",
				"deleted",
				"promoteTime",
				"ruleTextModTime",
				"dynamicValidationSubmitted",
				"dynamicValidationRejected",
				"dynamicValidationSucceeded",
				"disabledFromZSCM",
				"dynamicValRejectCode",
			},
		},
		{
			name: "ips_signature_rules.IPSSignatureCategory",
			typ:  reflect.TypeOf(ipssignaturerules.IPSSignatureCategory{}),
			ignoredFields: ignoredBecause(
				"threat category sub-fields are explicitly modeled in the ips-signature-rules category catalog field; this entry catches SDK additions",
				"id",
				"name",
				"isNameL10nTag",
			),
		},
		{
			name:         "ipspolicies.FirewallIPSRules",
			resource:     resources.ProductZIA,
			resourceName: resourceIPSPolicies,
			typ:          reflect.TypeOf(ipspolicies.FirewallIPSRules{}),
			catalogFields: []string{
				"accessControl",
				"action",
				"capturePCAP",
				"defaultRule",
				"departments",
				"description",
				"destAddresses",
				"destCountries",
				"destIpCategories",
				"destIpGroups",
				"destIpv6Groups",
				"deviceGroups",
				"devices",
				"enableFullLogging",
				"eunTemplateId",
				"groups",
				"id",
				"isEunEnabled",
				"labels",
				"lastModifiedBy",
				"lastModifiedTime",
				"locationGroups",
				"locations",
				"name",
				"nwServiceGroups",
				"nwServices",
				"order",
				"predefined",
				"rank",
				"resCategories",
				"sourceCountries",
				"srcIpGroups",
				"srcIps",
				"srcIpv6Groups",
				"state",
				"threatCategories",
				"timeWindows",
				"users",
				"zpaAppSegments",
			},
		},
		{
			name:         "customfiletypes.CustomFileTypes",
			resource:     resources.ProductZIA,
			resourceName: resourceCustomFileTypes,
			typ:          reflect.TypeOf(customfiletypes.CustomFileTypes{}),
			catalogFields: []string{
				"description",
				"extension",
				"fileTypeId",
				"id",
				"name",
			},
		},
		{
			name:         "riskprofiles.RiskProfiles",
			resource:     resources.ProductZIA,
			resourceName: resourceRiskProfiles,
			typ:          reflect.TypeOf(riskprofiles.RiskProfiles{}),
			catalogFields: []string{
				"adminAuditLogs",
				"certifications",
				"createTime",
				"customTags",
				"dataBreach",
				"dataEncryptionInTransit",
				"dnsCaaPolicy",
				"domainBasedMessageAuth",
				"domainKeysIdentifiedMail",
				"evasive",
				"excludeCertificates",
				"fileSharing",
				"httpSecurityHeaders",
				"id",
				"lastModTime",
				"malwareScanningForContent",
				"mfaSupport",
				"modifiedBy",
				"passwordStrength",
				"poorItemsOfService",
				"profileName",
				"profileType",
				"remoteScreenSharing",
				"riskIndex",
				"senderPolicyFramework",
				"sourceIpRestrictions",
				"sslCertKeySize",
				"sslCertValidity",
				"sslPinned",
				"status",
				"supportForWaf",
				"vulnerability",
				"vulnerabilityDisclosure",
				"vulnerableToHeartBleed",
				"vulnerableToLogJam",
				"vulnerableToPoodle",
				"weakCipherSupport",
			},
		},
		{
			name:         "nssservers.NSSServers",
			resource:     resources.ProductZIA,
			resourceName: resourceNSSServers,
			typ:          reflect.TypeOf(nssservers.NSSServers{}),
			catalogFields: []string{
				"icapSvrId",
				"id",
				"name",
				"state",
				"status",
				"type",
			},
		},
		{
			name:         "cloudnss.NSSFeed",
			resource:     resources.ProductZIA,
			resourceName: resourceNSSFeeds,
			typ:          reflect.TypeOf(cloudnss.NSSFeed{}),
			catalogFields: []string{
				"actionFilter",
				"activity",
				"advUserAgents",
				"advancedThreats",
				"alerts",
				"auditLogType",
				"authenticationToken",
				"authenticationUrl",
				"base64EncodedCertificate",
				"buckets",
				"casbAction",
				"casbApplications",
				"casbFileType",
				"casbFileTypeSuperCategories",
				"casbPolicyTypes",
				"casbSeverity",
				"casbTenant",
				"channelName",
				"clientDestinationIps",
				"clientDestinationPorts",
				"clientId",
				"clientIps",
				"clientSecret",
				"clientSourceIps",
				"clientSourcePorts",
				"cloudNss",
				"connectionHeaders",
				"connectionURL",
				"countries",
				"customEscapedCharacter",
				"departments",
				"direction",
				"dlpDictionaries",
				"dlpEngines",
				"dnsActions",
				"dnsRequestTypes",
				"dnsResponseTypes",
				"dnsResponses",
				"domains",
				"downloadTime",
				"durations",
				"emailDLPLogType",
				"emailDlpPolicyAction",
				"endPointDLPLogType",
				"epsRateLimit",
				"event",
				"externalCollaborators",
				"externalOwners",
				"feedOutputFormat",
				"feedStatus",
				"fileName",
				"fileSizes",
				"fileSource",
				"fileTypeCategories",
				"fileTypeSuperCategories",
				"firewallActions",
				"firewallLoggingMode",
				"fullUrls",
				"grantType",
				"hostNames",
				"id",
				"inBoundBytes",
				"internalCollaborators",
				"internalIps",
				"itsmObjectType",
				"jsonArrayToggle",
				"lastSuccessFullTest",
				"locationGroups",
				"locations",
				"malwareClasses",
				"malwareNames",
				"maxBatchSize",
				"messageSize",
				"name",
				"natActions",
				"nssFeedType",
				"nssLogType",
				"nssType",
				"nwApplications",
				"nwServices",
				"oauthAuthentication",
				"objectName",
				"objectType",
				"objectType1",
				"objectType2",
				"outBoundBytes",
				"pageRiskIndexes",
				"policyReasons",
				"projectName",
				"protocolTypes",
				"refererUrls",
				"repoName",
				"requestMethods",
				"requestSizes",
				"responseCodes",
				"responseSizes",
				"rules",
				"scanTime",
				"scope",
				"senderName",
				"serverDestinationIps",
				"serverIps",
				"serverSourceIps",
				"serverSourcePorts",
				"sessionCounts",
				"siemType",
				"testConnectivityCode",
				"threatNames",
				"timeZone",
				"trafficForwards",
				"transactionSizes",
				"tunnelDestIps",
				"tunnelIps",
				"tunnelSourceIps",
				"tunnelSourcePort",
				"tunnelTypes",
				"urlCategories",
				"urlClasses",
				"urlSuperCategories",
				"userAgents",
				"userObfuscation",
				"users",
				"vpnCredentials",
				"webApplicationClasses",
				"webApplications",
				"webTrafficForwards",
			},
		},
		{
			name:         "zpagateways.ZPAGateways",
			resource:     resources.ProductZIA,
			resourceName: resourceZPAGateways,
			typ:          reflect.TypeOf(zpagateways.ZPAGateways{}),
			catalogFields: []string{
				"description",
				"id",
				"lastModifiedBy",
				"lastModifiedTime",
				"name",
				"type",
				"zpaAppSegments",
				"zpaServerGroup",
				"zpaTenantId",
			},
		},
		{
			name: "zpagateways.ZPAServerGroup",
			typ:  reflect.TypeOf(zpagateways.ZPAServerGroup{}),
			ignoredFields: ignoredBecause(
				"nested ZPA server-group references are explicitly modeled in the zpa-gateways catalog; this entry catches SDK additions",
				"id",
				"name",
				"externalId",
				"extensions",
			),
		},
		{
			name: "zpagateways.ZPAAppSegments",
			typ:  reflect.TypeOf(zpagateways.ZPAAppSegments{}),
			ignoredFields: ignoredBecause(
				"nested ZPA application-segment references are explicitly modeled in the zpa-gateways catalog; this entry catches SDK additions",
				"id",
				"name",
				"externalId",
				"extensions",
			),
		},
		{
			name:         "emailprofiles.EmailProfiles",
			resource:     resources.ProductZIA,
			resourceName: resourceEmailProfiles,
			typ:          reflect.TypeOf(emailprofiles.EmailProfiles{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"emails",
			},
		},
		{
			name:          "advancedsettings.AdvancedSettings",
			resource:      resources.ProductZIA,
			resourceName:  resourceAdvancedSettings,
			typ:           reflect.TypeOf(advancedsettings.AdvancedSettings{}),
			catalogFields: catalogFieldsFor(resources.ProductZIA, resourceAdvancedSettings),
		},
		{
			name:          "advancedthreatsettings.AdvancedThreatSettings",
			resource:      resources.ProductZIA,
			resourceName:  resourceAdvancedThreatSettings,
			typ:           reflect.TypeOf(advancedthreatsettings.AdvancedThreatSettings{}),
			catalogFields: catalogFieldsFor(resources.ProductZIA, resourceAdvancedThreatSettings),
		},
		{
			name:          "mobilethreatsettings.MobileAdvanceThreatSettings",
			resource:      resources.ProductZIA,
			resourceName:  resourceMobileThreatSettings,
			typ:           reflect.TypeOf(mobilethreatsettings.MobileAdvanceThreatSettings{}),
			catalogFields: catalogFieldsFor(resources.ProductZIA, resourceMobileThreatSettings),
		},
		{
			name:          "sandboxsettings.BaAdvancedSettings",
			resource:      resources.ProductZIA,
			resourceName:  resourceSandboxSettings,
			typ:           reflect.TypeOf(sandboxsettings.BaAdvancedSettings{}),
			catalogFields: catalogFieldsFor(resources.ProductZIA, resourceSandboxSettings),
		},
		{
			name:          "endusernotification.UserNotificationSettings",
			resource:      resources.ProductZIA,
			resourceName:  resourceEndUserNotification,
			typ:           reflect.TypeOf(endusernotification.UserNotificationSettings{}),
			catalogFields: catalogFieldsFor(resources.ProductZIA, resourceEndUserNotification),
		},
		{
			name:          "organizationdetails.Organization",
			resource:      resources.ProductZIA,
			resourceName:  resourceOrgInformation,
			typ:           reflect.TypeOf(organizationdetails.Organization{}),
			catalogFields: catalogFieldsFor(resources.ProductZIA, resourceOrgInformation),
		},
		{
			name:          "malwareprotection.MalwarePolicy",
			resource:      resources.ProductZIA,
			resourceName:  resourceATPMalwarePolicy,
			typ:           reflect.TypeOf(malwareprotection.MalwarePolicy{}),
			catalogFields: catalogFieldsFor(resources.ProductZIA, resourceATPMalwarePolicy),
		},
		{
			name:          "malwareprotection.MalwareSettings",
			resource:      resources.ProductZIA,
			resourceName:  resourceATPMalwareSettings,
			typ:           reflect.TypeOf(malwareprotection.MalwareSettings{}),
			catalogFields: catalogFieldsFor(resources.ProductZIA, resourceATPMalwareSettings),
		},
		{
			name:          "malwareprotection.ATPMalwareInspection",
			resource:      resources.ProductZIA,
			resourceName:  resourceATPMalwareInspection,
			typ:           reflect.TypeOf(malwareprotection.ATPMalwareInspection{}),
			catalogFields: catalogFieldsFor(resources.ProductZIA, resourceATPMalwareInspection),
		},
		{
			name:          "malwareprotection.ATPMalwareProtocols",
			resource:      resources.ProductZIA,
			resourceName:  resourceATPMalwareProtocols,
			typ:           reflect.TypeOf(malwareprotection.ATPMalwareProtocols{}),
			catalogFields: catalogFieldsFor(resources.ProductZIA, resourceATPMalwareProtocols),
		},
		{
			name:          "advancedthreatsettings.MaliciousURLs",
			resource:      resources.ProductZIA,
			resourceName:  resourceMaliciousURLs,
			typ:           reflect.TypeOf(advancedthreatsettings.MaliciousURLs{}),
			catalogFields: catalogFieldsFor(resources.ProductZIA, resourceMaliciousURLs),
		},
		{
			name:          "advancedthreatsettings.SecurityExceptions",
			resource:      resources.ProductZIA,
			resourceName:  resourceSecurityExceptions,
			typ:           reflect.TypeOf(advancedthreatsettings.SecurityExceptions{}),
			catalogFields: catalogFieldsFor(resources.ProductZIA, resourceSecurityExceptions),
		},
		{
			name:          "securitypolicysettings.ListUrls/allow",
			resource:      resources.ProductZIA,
			resourceName:  resourceSecurityPolicyURLAllowlist,
			typ:           reflect.TypeOf(securitypolicysettings.ListUrls{}),
			catalogFields: catalogFieldsFor(resources.ProductZIA, resourceSecurityPolicyURLAllowlist),
		},
		{
			name:          "securitypolicysettings.ListUrls/deny",
			resource:      resources.ProductZIA,
			resourceName:  resourceSecurityPolicyURLDenylist,
			typ:           reflect.TypeOf(securitypolicysettings.ListUrls{}),
			catalogFields: catalogFieldsFor(resources.ProductZIA, resourceSecurityPolicyURLDenylist),
		},
	}
}
