package zscaler

import (
	"reflect"

	"github.com/dvmrry/zscalerctl/internal/resources"

	zccadminroles "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/admin_roles"
	zccadminusers "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/admin_users"
	zccappprofiles "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/application_profiles"
	zcccompany "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/company"
	zcccustomip "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/custom_ip_apps"
	zccdevices "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/devices"
	zccentitlements "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/entitlements"
	zccfailopen "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/failopen_policy"
	zccfwdprofile "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/forwarding_profile"
	zccnotiftmpl "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/notification_template"
	zccpredefip "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/predefined_ip_apps"
	zccprocessapps "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/process_based_apps"
	zcctrustednet "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/trusted_network"
	zccwebappsvc "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/web_app_service"
	zccziaposture "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zcc/services/zia_posture"
)

func reviewedSDKShapesZCC() []sdkShapeReview {
	return []sdkShapeReview{
		{
			name:         "zccfailopen.WebFailOpenPolicy",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCFailOpenPolicy,
			typ:          reflect.TypeOf(zccfailopen.WebFailOpenPolicy{}),
			catalogFields: []string{
				"active",
				"captivePortalWebSecDisableMinutes",
				"companyId",
				"createdBy",
				"editedBy",
				"enableCaptivePortalDetection",
				"enableFailOpen",
				"enableStrictEnforcementPrompt",
				"enableWebSecOnProxyUnreachable",
				"enableWebSecOnTunnelFailure",
				"id",
				"strictEnforcementPromptDelayMinutes",
				"strictEnforcementPromptMessage",
				"tunnelFailureRetryCount",
			},
		},
		{
			name:         "zccfwdprofile.ForwardingProfile",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCFwdProfiles,
			typ:          reflect.TypeOf(zccfwdprofile.ForwardingProfile{}),
			catalogFields: []string{
				"id",
				"active",
				"name",
				"conditionType",
				"dnsServers",
				"dnsSearchDomains",
				"enableLWFDriver",
				"hostname",
				"resolvedIpsForHostname",
				"trustedSubnets",
				"trustedGateways",
				"trustedDhcpServers",
				"trustedEgressIps",
				"predefinedTrustedNetworks",
				"predefinedTnAll",
				"forwardingProfileActions",
				"forwardingProfileZpaActions",
				"enableUnifiedTunnel",
				"unifiedTunnel",
				"enableAllDefaultAdaptersTN",
				"enableSplitVpnTN",
				"evaluateTrustedNetwork",
				"skipTrustedCriteriaMatch",
				"trustedNetworkIds",
				"trustedNetworks",
				"trustedNetworkIdsSelected",
			},
		},
		{
			name:         "zcctrustednet.TrustedNetwork",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCTrustedNets,
			typ:          reflect.TypeOf(zcctrustednet.TrustedNetwork{}),
			catalogFields: []string{
				"id",
				"active",
				"companyId",
				"conditionType",
				"createdBy",
				"dnsSearchDomains",
				"dnsServers",
				"editedBy",
				"guid",
				"hostnames",
				"networkName",
				"resolvedIpsForHostname",
				"ssids",
				"trustedDhcpServers",
				"trustedEgressIps",
				"trustedGateways",
				"trustedSubnets",
			},
		},
		{
			name:         "zccwebappsvc.WebAppService",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCWebAppServices,
			typ:          reflect.TypeOf(zccwebappsvc.WebAppService{}),
			catalogFields: []string{
				"id",
				"appVersion",
				"appSvcId",
				"appName",
				"active",
				"uid",
				"appDataBlob",
				"appDataBlobV6",
				"createdBy",
				"editedBy",
				"editedTimestamp",
				"zappDataBlob",
				"zappDataBlobV6",
				"version",
			},
		},
		{
			name:         "zccappprofiles.ApplicationProfile",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCAppProfiles,
			typ:          reflect.TypeOf(zccappprofiles.ApplicationProfile{}),
			catalogFields: []string{
				"deviceType",
				"id",
				"name",
				"description",
				"pac_url",
				"active",
				"ruleOrder",
				"logMode",
				"logLevel",
				"logFileSize",
				"reauth_period",
				"reactivateWebSecurityMinutes",
				"highlightActiveControl",
				"sendDisableServiceReason",
				"refreshKerberosToken",
				"enableDeviceGroups",
				"groups",
				"deviceGroups",
				"onNetPolicy",
				"notificationTemplateContract",
				"notificationTemplateId",
				"forwardingProfileId",
				"ziaPostureConfigId",
				"policyToken",
				"tunnelZappTraffic",
				"groupAll",
				"users",
				"policyExtension",
				"disasterRecovery",
				"ziaPostureConfig",
				"groupIds",
				"deviceGroupIds",
				"userIds",
				"bypassAppIds",
				"appServiceIds",
				"bypassCustomAppIds",
				"bypassApps",
				"bypassCustomApps",
				"appServices",
				"passcode",
				"logout_password",
				"disable_password",
				"uninstall_password",
				"showVPNTunNotification",
				"useTunnelSDK4_3",
				"ipv6Mode",
			},
		},
		{
			name:         "zcccustomip.CustomIPApp",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCCustomIPApps,
			typ:          reflect.TypeOf(zcccustomip.CustomIPApp{}),
			catalogFields: []string{
				"id",
				"appName",
				"active",
				"uid",
				"appDataBlob",
				"appDataBlobV6",
				"createdBy",
				"editedBy",
				"editedTimestamp",
				"zappDataBlob",
				"zappDataBlobV6",
			},
		},
		{
			name:         "zccpredefip.PredefinedIPApp",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCPredefIPApps,
			typ:          reflect.TypeOf(zccpredefip.PredefinedIPApp{}),
			catalogFields: []string{
				"id",
				"appVersion",
				"appSvcId",
				"appName",
				"active",
				"uid",
				"appDataBlob",
				"appDataBlobV6",
				"createdBy",
				"editedBy",
				"editedTimestamp",
				"zappDataBlob",
				"zappDataBlobV6",
			},
		},
		{
			name:         "zccprocessapps.ProcessBasedApp",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCProcessApps,
			typ:          reflect.TypeOf(zccprocessapps.ProcessBasedApp{}),
			catalogFields: []string{
				"id",
				"appName",
				"fileNames",
				"filePaths",
				"matchingCriteria",
				"signaturePayload",
				"certificatePayload",
				"createdBy",
				"editedBy",
				"editedTimestamp",
			},
		},
		{
			name:         "zccentitlements.ZpaGroupEntitlements",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCZPAEntitle,
			typ:          reflect.TypeOf(zccentitlements.ZpaGroupEntitlements{}),
			catalogFields: []string{
				"computeDeviceGroupsForZPA",
				"deviceGroupList",
				"groupList",
				"machineTunEnabledForAll",
				"totalCount",
				"zpaEnableForAll",
			},
		},
		{
			name:         "zccentitlements.ZdxGroupEntitlements",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCZDXEntitle,
			typ:          reflect.TypeOf(zccentitlements.ZdxGroupEntitlements{}),
			catalogFields: []string{
				"collectZdxLocation",
				"computeDeviceGroupsForZDX",
				"logoutZCCForZDXService",
				"totalCount",
				"upmDeviceGroupList",
				"upmEnableForAll",
				"upmGroupList",
			},
		},
		{
			name:         "zccnotiftmpl.NotificationTemplate",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCNotifTmpls,
			typ:          reflect.TypeOf(zccnotiftmpl.NotificationTemplate{}),
			catalogFields: []string{
				"id",
				"name",
				"isDefaultTemplate",
				"enableClient",
				"enableZia",
				"enableAppUpdates",
				"enableServiceStatus",
				"durationInSeconds",
				"enablePersistent",
				"enableDoNotDisturb",
				"createdBy",
				"editedBy",
				"ziaNotificationTemplate",
				"zpaNotificationTemplate",
			},
		},
		{
			name:         "zccziaposture.ZIAPosture",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCZIAPostures,
			typ:          reflect.TypeOf(zccziaposture.ZIAPosture{}),
			catalogFields: []string{
				"id",
				"name",
				"platform",
				"highTrustCriteria",
				"mediumTrustCriteria",
				"lowTrustCriteria",
			},
		},
		{
			name:         "zccdevices.GetDevices",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCDevices,
			typ:          reflect.TypeOf(zccdevices.GetDevices{}),
			catalogFields: []string{
				"agentVersion",
				"companyName",
				"config_download_time",
				"deregistrationTimestamp",
				"detail",
				"download_count",
				"hardwareFingerprint",
				"keepAliveTime",
				"last_seen_time",
				"macAddress",
				"machineHostname",
				"manufacturer",
				"osVersion",
				"owner",
				"policyName",
				"registrationState",
				"registration_time",
				"state",
				"tunnelVersion",
				"type",
				"udid",
				"upmVersion",
				"user",
				"vpnState",
				"zappArch",
			},
		},
		{
			name:         "zccadminusers.AdminUser",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCAdminUsers,
			typ:          reflect.TypeOf(zccadminusers.AdminUser{}),
			catalogFields: []string{
				"accountEnabled",
				"companyId",
				"companyRole",
				"editEnabled",
				"id",
				"isDefaultAdmin",
				"serviceType",
				"userName",
			},
		},
		{
			name:         "zccadminroles.AdminRole",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCAdminRoles,
			typ:          reflect.TypeOf(zccadminroles.AdminRole{}),
			catalogFields: []string{
				"adminManagement",
				"administratorGroup",
				"androidProfile",
				"appBypass",
				"appProfileGroup",
				"auditLogs",
				"authSetting",
				"clientConnectorAppStore",
				"clientConnectorIdp",
				"clientConnectorNotifications",
				"clientConnectorSupport",
				"companyId",
				"createdBy",
				"dashboard",
				"ddilConfiguration",
				"dedicatedProxyPorts",
				"deviceGroups",
				"deviceOverview",
				"devicePosture",
				"enrolledDevicesGroup",
				"forwardingProfile",
				"id",
				"iosProfile",
				"isEditable",
				"linuxProfile",
				"macProfile",
				"machineTunnel",
				"obfuscateData",
				"partnerDeviceOverview",
				"publicApi",
				"roleName",
				"trustedNetwork",
				"updatedBy",
				"userAgent",
				"windowsProfile",
				"zpaPartnerLogin",
				"zscalerDeception",
				"zscalerEntitlement",
			},
		},
		{
			name:         "zcccompany.CompanyInfo",
			resource:     resources.ProductZCC,
			resourceName: resourceZCCCompanyInfo,
			typ:          reflect.TypeOf(zcccompany.CompanyInfo{}),
			catalogFields: []string{
				"orgId",
				"masterCustomerId",
				"name",
				"businessName",
				"businessContactNumber",
				"activationRecipient",
				"activationCopy",
				"mdmStatus",
				"sendEmail",
				"proxyEnabled",
				"zpnEnabled",
				"upmEnabled",
				"zadEnabled",
				"enableDeceptionForAll",
				"dlpEnabled",
				"tunnelProtocolType",
				"secureAgentBasic",
				"secureAgentAdvanced",
				"supportAdminEmail",
				"supportEnabled",
				"fetchLogsForAdminsEnabled",
				"enableRectifyUtils",
				"supportTicketEnabled",
				"disableLoggingControls",
				"defaultAuthType",
				"version",
				"policyActivationRequired",
				"enableAutofillUsername",
				"autoFillUsingLoginHint",
				"dcServiceReadOnly",
				"enableTunnelZappTrafficToggle",
				"machineIdpAuth",
				"linuxVisibility",
				"registryPathForPac",
				"usePollsetForSocketReactor",
				"enableDtlsForZpa",
				"useV8JsEngine",
				"disableParallelIpv4AndIPv6",
				"send64BitBuild",
				"useAddIfscopeRoute",
				"useClearArpCache",
				"useDnsPriorityOrdering",
				"enableBrowserAuth",
				"enablePublicAPI",
				"disableReasonVisibility",
				"followRoutingTable",
				"useDefaultAdapterForDNS",
				"enableMinimumDeviceCleanupAsOne",
				"dnsPriorityOrderingForTrustedDnsCriteria",
				"machineTunnelPosture",
				"zpaPartnerLogin",
				"proxyPort",
				"dnsCacheTtlWindows",
				"dnsCacheTtlMac",
				"dnsCacheTtlAndroid",
				"dnsCacheTtlIos",
				"dnsCacheTtlLinux",
				"zpaClientCertExpInDays",
				"enableFlowLogger",
				"flowLoggingBufferLimit",
				"flowLoggingTimeInterval",
				"postureBasedService",
				"enablePostureBasedProfile",
				"disasterRecovery",
				"ziaGlobalDbUrlForDR",
				"enableReactUI",
				"launchReactUIbyDefault",
				"dlpNotification",
				"vpnGatewayCharLimit",
				"deviceGroupsCount",
				"vpnBypassRefreshInterval",
				"destIncludeExcludeCharLimit",
				"ipV6SupportForTunnel2",
				"destIncludeExcludeCharLimitForIpv6",
				"enableSetProxyOnVPNAdapters",
				"disableDNSRouteExclusion",
				"showVPNTunNotification",
				"addAppBypassToVPNGateway",
				"enableZscalerFirewall",
				"persistentZscalerFirewall",
				"clearMupCache",
				"executeGpoUpdate",
				"enablePortBasedZPAFilter",
				"enableAntiTampering",
				"zpaReauthEnabled",
				"zpaAutoReauthTimeout",
				"enableZpaAuthUserName",
				"enableGlobalZCCTelemetry",
				"configureTunnel2fallbackForZia",
				"webAppConfig",
				"enableInstallWebView2",
				"enableCustomProxyPorts",
				"interceptZIATrafficAllAdapters",
				"swaggerLink",
				"enableOneIdAdmin",
				"enableOneIdUser",
				"restrictAdminAccess",
				"enableZiaUserDepartmentSync",
				"enableUDPTransportSelection",
				"computeDeviceGroupsForZIA",
				"computeDeviceGroupsForZPA",
				"computeDeviceGroupsForZDX",
				"computeDeviceGroupsForZAD",
				"useTunnel2SmeForTunnel1",
				"maCloudName",
				"ziaCloudName",
				"zt2HealthProbeInterval",
				"devicePostureFrequency",
				"zdxManualRollout",
				"winZdxLiteEnabled",
				"telemetryDefault",
			},
		},
	}
}
