package zscaler

import (
	"reflect"

	"github.com/dvmrry/zscalerctl/internal/resources"

	ziacommon "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/common"
	"github.com/zscaler/zscaler-sdk-go/v3/zscaler/zia/services/workloadgroups"
	zpaappconnectorcontroller "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/appconnectorcontroller"
	zpaappconnectorgroup "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/appconnectorgroup"
	zpaappconnschedule "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/appconnectorschedule"
	zpaapplicationsegment "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/applicationsegment"
	zpaappservercontroller "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/appservercontroller"
	zpabranchconnector "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/branch_connector"
	zpac2cipranges "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/c2c_ip_ranges"
	zpaclienttypes "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/clienttypes"
	zpacloudconnector "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/cloud_connector"
	zpacloudconnectorgroup "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/cloud_connector_group"
	zpacbibanner "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/cloudbrowserisolation/cbibannercontroller"
	zpacbiprofile "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/cloudbrowserisolation/cbiprofilecontroller"
	zpacbiregions "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/cloudbrowserisolation/cbiregions"
	zpacbizpaprofile "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/cloudbrowserisolation/cbizpaprofile"
	zpaisolationprofile "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/cloudbrowserisolation/isolationprofile"
	zpacommon "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/common"
	zpaconfigoverride "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/config_override"
	zpaversionprofile "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/customerversionprofile"
	zpainspectioncustom "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/inspectioncontrol/inspection_custom_controls"
	zpainspectionpredef "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/inspectioncontrol/inspection_predefined_controls"
	zpainspectionprofile "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/inspectioncontrol/inspection_profile"
	zpamachinegroup "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/machinegroup"
	zpamicrotenants "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/microtenants"
	zpaplatforms "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/platforms"
	zpapostureprofile "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/postureprofile"
	zpapraapproval "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/privilegedremoteaccess/praapproval"
	zpapraconsole "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/privilegedremoteaccess/praconsole"
	zpapraportal "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/privilegedremoteaccess/praportal"
	zpasegmentgroup "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/segmentgroup"
	zpaservergroup "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/servergroup"
	zpaserviceedgecontroller "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/serviceedgecontroller"
	zpaserviceedgegroup "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/serviceedgegroup"
	zpaserviceedgeschedule "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/serviceedgeschedule"
	zpataggroup "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/tag_controller/tag_group"
	zpatagkey "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/tag_controller/tag_key"
	zpatagnamespace "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/tag_controller/tag_namespace"
	zpatrustednetwork "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/trustednetwork"
	zpauserportalaup "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/userportal/aup"
	zpauserportal "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/userportal/portal_controller"
	zpauserportallink "github.com/zscaler/zscaler-sdk-go/v3/zscaler/zpa/services/userportal/portal_link"
	ztwcommon "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/common"
	ztwnetworkservicegroups "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/policyresources/networkservicegroups"
	ztwnetworkservices "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/policyresources/networkservices"
	ztwworkloadgroups "github.com/zscaler/zscaler-sdk-go/v3/zscaler/ztw/services/workload_groups"
)

func reviewedSDKShapesZPA() []sdkShapeReview {
	return []sdkShapeReview{
		{
			name:         "zpamicrotenants.MicroTenant",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAMicrotenants,
			typ:          reflect.TypeOf(zpamicrotenants.MicroTenant{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"enabled",
				"criteriaAttribute",
				"criteriaAttributeValues",
				"privilegedApprovalsEnabled",
				"operator",
				"priority",
				"creationTime",
				"modifiedBy",
				"modifiedTime",
				"roles",
				"user",
			},
		},
		{
			name:         "zpaversionprofile.CustomerVersionProfile",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAVersionProfiles,
			typ:          reflect.TypeOf(zpaversionprofile.CustomerVersionProfile{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"creationTime",
				"modifiedBy",
				"modifiedTime",
				"customerId",
				"customScopeCustomerIds",
				"customScopeRequestCustomerIds",
				"versions",
				"visibilityScope",
				"upgradePriority",
				"numberOfAssistants",
				"numberOfCustomers",
				"numberOfPrivateBrokers",
				"numberOfSiteControllers",
				"numberOfUpdatedAssistants",
				"numberOfUpdatedPrivateBrokers",
				"numberOfUpdatedSiteControllers",
			},
		},
		{
			name:         "zpaclienttypes.ClientTypes",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAClientTypes,
			typ:          reflect.TypeOf(zpaclienttypes.ClientTypes{}),
			catalogFields: []string{
				"zpn_client_type_exporter",
				"zpn_client_type_exporter_noauth",
				"zpn_client_type_browser_isolation",
				"zpn_client_type_machine_tunnel",
				"zpn_client_type_ip_anchoring",
				"zpn_client_type_edge_connector",
				"zpn_client_type_zapp",
				"zpn_client_type_slogger",
				"zpn_client_type_branch_connector",
				"zpn_client_type_zapp_partner",
				"zpn_client_type_vdi",
				"zpn_client_type_zia_inspection",
			},
		},
		{
			name:         "zpaplatforms.Platforms",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAPlatforms,
			typ:          reflect.TypeOf(zpaplatforms.Platforms{}),
			catalogFields: []string{
				"linux",
				"android",
				"windows",
				"ios",
				"mac",
			},
		},
		{
			name:         "zpaappconnschedule.AssistantSchedule",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAAppConnectorSchedule,
			typ:          reflect.TypeOf(zpaappconnschedule.AssistantSchedule{}),
			catalogFields: []string{
				"id",
				"customerId",
				"deleteDisabled",
				"enabled",
				"frequency",
				"frequencyInterval",
			},
		},
		{
			name:         "zpaserviceedgeschedule.AssistantSchedule",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAServiceEdgeSchedule,
			typ:          reflect.TypeOf(zpaserviceedgeschedule.AssistantSchedule{}),
			catalogFields: []string{
				"id",
				"customerId",
				"deleteDisabled",
				"enabled",
				"frequency",
				"frequencyInterval",
			},
		},
		{
			name:         "zpainspectionprofile.InspectionProfile",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAInspectionProfiles,
			typ:          reflect.TypeOf(zpainspectionprofile.InspectionProfile{}),
			catalogFields: []string{
				"id", "name", "description", "apiProfile", "overrideAction",
				"creationTime", "zsDefinedControlChoice", "globalControlActions",
				"incarnationNumber", "modifiedBy", "modifiedTime", "paranoiaLevel",
				"predefinedControlsVersion", "checkControlDeploymentStatus",
				"commonGlobalOverrideActionsConfig", "controlsInfo", "customControls",
				"predefinedApiControls", "predefinedControls", "websocketControls",
				"threatlabzControls",
			},
		},
		{
			name:         "zpainspectioncustom.InspectionCustomControl",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAInspectionCustomCtl,
			typ:          reflect.TypeOf(zpainspectioncustom.InspectionCustomControl{}),
			catalogFields: []string{
				"id", "name", "description", "action", "actionValue",
				"associatedInspectionProfileNames", "controlNumber", "controlType",
				"controlRuleJson", "creationTime", "defaultAction", "defaultActionValue",
				"modifiedBy", "modifiedTime", "paranoiaLevel", "protocolType", "rules",
				"severity", "type", "version",
			},
		},
		{
			name:         "zpainspectionpredef.PredefinedControls",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAInspectionPredefinedCtl,
			typ:          reflect.TypeOf(zpainspectionpredef.PredefinedControls{}),
			catalogFields: []string{
				"id", "name", "description", "action", "actionValue",
				"associatedInspectionProfileNames", "attachment", "controlGroup",
				"controlType", "controlNumber", "creationTime", "defaultAction",
				"defaultActionValue", "modifiedBy", "modifiedTime", "paranoiaLevel",
				"protocolType", "severity", "version",
			},
		},
		{
			name:         "zpataggroup.TagGroup",
			resource:     resources.ProductZPA,
			resourceName: resourceZPATagGroups,
			typ:          reflect.TypeOf(zpataggroup.TagGroup{}),
			catalogFields: []string{
				"id", "name", "description", "microtenantId", "microtenantName", "tags",
			},
		},
		{
			name:         "zpatagkey.TagKey",
			resource:     resources.ProductZPA,
			resourceName: resourceZPATagKeys,
			typ:          reflect.TypeOf(zpatagkey.TagKey{}),
			catalogFields: []string{
				"id", "customerId", "name", "description", "enabled", "namespaceId",
				"origin", "type", "microtenantId", "microtenantName", "skipAudit",
				"tagValues",
			},
		},
		{
			name:         "zpatagnamespace.Namespace",
			resource:     resources.ProductZPA,
			resourceName: resourceZPATagNamespaces,
			typ:          reflect.TypeOf(zpatagnamespace.Namespace{}),
			catalogFields: []string{
				"id", "name", "description", "enabled", "origin", "type",
				"microtenantId", "microtenantName",
			},
		},
		{
			name:         "zpacbibanner.CBIBannerController",
			resource:     resources.ProductZPA,
			resourceName: resourceZPACBIBanners,
			typ:          reflect.TypeOf(zpacbibanner.CBIBannerController{}),
			catalogFields: []string{
				"id",
				"name",
				"primaryColor",
				"textColor",
				"notificationTitle",
				"notificationText",
				"logo",
				"banner",
				"isDefault",
				"persist",
			},
		},
		{
			name:         "zpacbiprofile.IsolationProfile",
			resource:     resources.ProductZPA,
			resourceName: resourceZPACBIProfiles,
			typ:          reflect.TypeOf(zpacbiprofile.IsolationProfile{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"enabled",
				"creationTime",
				"modifiedBy",
				"modifiedTime",
				"cbiTenantId",
				"cbiProfileId",
				"cbiUrl",
				"bannerId",
				"securityControls",
				"isDefault",
				"regions",
				"regionIds",
				"href",
				"userExperience",
				"certificates",
				"certificateIds",
				"banner",
				"debugMode",
			},
		},
		{
			name:         "zpacbiregions.CBIRegions",
			resource:     resources.ProductZPA,
			resourceName: resourceZPACBIRegions,
			typ:          reflect.TypeOf(zpacbiregions.CBIRegions{}),
			catalogFields: []string{
				"id",
				"name",
			},
		},
		{
			name:         "zpaisolationprofile.IsolationProfile",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAIsolationProfiles,
			typ:          reflect.TypeOf(zpaisolationprofile.IsolationProfile{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"enabled",
				"creationTime",
				"modifiedBy",
				"modifiedTime",
				"isolationProfileId",
				"isolationTenantId",
				"isolationUrl",
			},
		},
		{
			name:         "zpabranchconnector.BranchConnector",
			resource:     resources.ProductZPA,
			resourceName: resourceZPABranchConnectors,
			typ:          reflect.TypeOf(zpabranchconnector.BranchConnector{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"enabled",
				"creationTime",
				"modifiedBy",
				"modifiedTime",
				"branchConnectorGroupId",
				"branchConnectorGroupName",
				"edgeConnectorGroupId",
				"edgeConnectorGroupName",
				"enrollmentCert",
				"fingerprint",
				"ipAcl",
				"issuedCertId",
			},
		},
		{
			name:         "zpapraapproval.PrivilegedApproval",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAPRAApprovals,
			typ:          reflect.TypeOf(zpapraapproval.PrivilegedApproval{}),
			catalogFields: []string{
				"id",
				"applications",
				"creationTime",
				"emailIds",
				"endTime",
				"microtenantId",
				"microtenantName",
				"modifiedBy",
				"modifiedTime",
				"startTime",
				"status",
				"workingHours",
			},
		},
		{
			name:         "zpapraconsole.PRAConsole",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAPRAConsoles,
			typ:          reflect.TypeOf(zpapraconsole.PRAConsole{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"enabled",
				"creationTime",
				"modifiedBy",
				"modifiedTime",
				"iconText",
				"microtenantId",
				"microtenantName",
				"praApplication",
				"praPortals",
			},
		},
		{
			name:         "zpapraportal.PRAPortal",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAPRAPortals,
			typ:          reflect.TypeOf(zpapraportal.PRAPortal{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"enabled",
				"creationTime",
				"modifiedBy",
				"modifiedTime",
				"action",
				"approvalReviewers",
				"cName",
				"certManagedByZsRadio",
				"certificateId",
				"certificateName",
				"domain",
				"extDomain",
				"extDomainName",
				"extDomainTranslation",
				"extLabel",
				"getcName",
				"hideInfoTooltip",
				"isSRAPortal",
				"managedByZs",
				"microtenantId",
				"microtenantName",
				"objectType",
				"restrictedEntity",
				"scopeName",
				"userNotification",
				"userNotificationEnabled",
				"userPortalGid",
				"userPortalName",
			},
		},
		{
			name:         "zpauserportal.UserPortalController",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAUserPortals,
			typ:          reflect.TypeOf(zpauserportal.UserPortalController{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"enabled",
				"creationTime",
				"modifiedBy",
				"modifiedTime",
				"certificateId",
				"certificateName",
				"domain",
				"extDomain",
				"extDomainName",
				"extDomainTranslation",
				"extLabel",
				"getcName",
				"imageData",
				"managedByZs",
				"microtenantId",
				"microtenantName",
				"userNotification",
				"userNotificationEnabled",
			},
		},
		{
			name:         "zpauserportalaup.UserPortalAup",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAUserPortalAups,
			typ:          reflect.TypeOf(zpauserportalaup.UserPortalAup{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"enabled",
				"creationTime",
				"modifiedBy",
				"modifiedTime",
				"aup",
				"email",
				"microtenantId",
				"microtenantName",
				"phoneNum",
			},
		},
		{
			name:         "zpauserportallink.UserPortalLink",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAUserPortalLinks,
			typ:          reflect.TypeOf(zpauserportallink.UserPortalLink{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"enabled",
				"creationTime",
				"modifiedBy",
				"modifiedTime",
				"applicationId",
				"iconText",
				"link",
				"linkPath",
				"microtenantId",
				"microtenantName",
				"nameWithoutTrim",
				"protocol",
				"userPortalId",
				"userPortals",
			},
		},
		{
			name:         "zpaservergroup.ServerGroup",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAServerGroups,
			typ:          reflect.TypeOf(zpaservergroup.ServerGroup{}),
			catalogFields: []string{
				"id",
				"enabled",
				"name",
				"description",
				"ipAnchored",
				"configSpace",
				"dynamicDiscovery",
				"extranetEnabled",
				"creationTime",
				"modifiedBy",
				"modifiedTime",
				"microtenantId",
				"microtenantName",
				"readOnly",
				"restrictionType",
				"zscalerManaged",
				"appConnectorGroups",
				"servers",
				"applications",
				"extranetDTO",
			},
		},
		{
			name:         "zpasegmentgroup.SegmentGroup",
			resource:     resources.ProductZPA,
			resourceName: resourceZPASegmentGroups,
			typ:          reflect.TypeOf(zpasegmentgroup.SegmentGroup{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"enabled",
				"configSpace",
				"creationTime",
				"modifiedBy",
				"modifiedTime",
				"policyMigrated",
				"tcpKeepAliveEnabled",
				"microtenantId",
				"microtenantName",
				"addedApps",
				"deletedApps",
				"applications",
				"applicationNames",
			},
		},
		{
			name:         "zpaapplicationsegment.ApplicationSegmentResource",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAAppSegments,
			typ:          reflect.TypeOf(zpaapplicationsegment.ApplicationSegmentResource{}),
			catalogFields: []string{
				"adpEnabled",
				"apiProtectionEnabled",
				"appRecommendationId",
				"applications",
				"autoAppProtectEnabled",
				"bypassOnReauth",
				"bypassType",
				"clientlessApps",
				"configSpace",
				"creationTime",
				"defaultIdleTimeout",
				"defaultMaxAge",
				"description",
				"domainNames",
				"doubleEncrypt",
				"enabled",
				"extranetEnabled",
				"fqdnDnsCheck",
				"healthCheckType",
				"healthReporting",
				"icmpAccessType",
				"id",
				"inspectTrafficWithZia",
				"ipAnchored",
				"isCnameEnabled",
				"isIncompleteDRConfig",
				"matchStyle",
				"microtenantId",
				"microtenantName",
				"modifiedBy",
				"modifiedTime",
				"name",
				"passiveHealthEnabled",
				"policyStyle",
				"readOnly",
				"restrictionType",
				"segmentGroupId",
				"segmentGroupName",
				"selectConnectorCloseToApp",
				"serverGroups",
				"shareToMicrotenants",
				"sharedMicrotenantDetails",
				"tags",
				"tcpKeepAlive",
				"tcpPortRange",
				"tcpPortRanges",
				"udpPortRange",
				"udpPortRanges",
				"useInDrMode",
				"weightedLoadBalancing",
				"zpnErId",
				"zscalerManaged",
			},
		},
		{
			name:         "zpaappconnectorcontroller.AppConnector",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAAppConnectors,
			typ:          reflect.TypeOf(zpaappconnectorcontroller.AppConnector{}),
			catalogFields: []string{
				"appConnectorGroupId",
				"appConnectorGroupName",
				"applicationStartTime",
				"assistantVersion",
				"controlChannelStatus",
				"creationTime",
				"ctrlBrokerName",
				"currentVersion",
				"description",
				"enabled",
				"enrollmentCert",
				"expectedUpgradeTime",
				"expectedVersion",
				"fingerprint",
				"id",
				"ipAcl",
				"issuedCertId",
				"lastBrokerConnectTime",
				"lastBrokerConnectTimeDuration",
				"lastBrokerDisconnectTime",
				"lastBrokerDisconnectTimeDuration",
				"lastUpgradeTime",
				"latitude",
				"location",
				"longitude",
				"microtenantId",
				"microtenantName",
				"modifiedBy",
				"modifiedTime",
				"name",
				"platform",
				"platformDetail",
				"previousVersion",
				"privateIp",
				"provisioningKeyId",
				"provisioningKeyName",
				"publicIp",
				"readOnly",
				"restrictionType",
				"runtimeOS",
				"sargeVersion",
				"upgradeAttempt",
				"upgradeStatus",
				"zpnSubModuleUpgradeList",
				"zscalerManaged",
			},
		},
		{
			name: "zpaappconnectorcontroller.AssistantVersion",
			typ:  reflect.TypeOf(zpaappconnectorcontroller.AssistantVersion{}),
			ignoredFields: ignoredBecause(
				"covered by dropped assistantVersion parent",
				"appConnectorGroupId",
				"applicationStartTime",
				"brokerId",
				"creationTime",
				"ctrlChannelStatus",
				"currentVersion",
				"disableAutoUpdate",
				"expectedVersion",
				"id",
				"lastBrokerConnectTime",
				"lastBrokerDisconnectTime",
				"lastUpgradedTime",
				"latitude",
				"loneWarrior",
				"longitude",
				"modifiedBy",
				"modifiedTime",
				"mtunnelId",
				"platform",
				"platformDetail",
				"previousVersion",
				"privateIp",
				"publicIp",
				"restartTimeInSec",
				"runtimeOS",
				"sargeVersion",
				"systemStartTime",
				"upgradeAttempt",
				"upgradeNowOnce",
				"upgradeStatus",
			),
		},
		{
			name: "zpacommon.ZPNSubModuleUpgrade",
			typ:  reflect.TypeOf(zpacommon.ZPNSubModuleUpgrade{}),
			ignoredFields: ignoredBecause(
				"covered by dropped zpnSubModuleUpgradeList parent",
				"creationTime",
				"currentVersion",
				"entityGid",
				"entityType",
				"expectedVersion",
				"id",
				"modifiedBy",
				"modifiedTime",
				"previousVersion",
				"role",
				"upgradeStatus",
				"upgradeTime",
			),
		},
		{
			name:         "zpaappconnectorgroup.AppConnectorGroup",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAConnectorGrps,
			typ:          reflect.TypeOf(zpaappconnectorgroup.AppConnectorGroup{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"enabled",
				"cityCountry",
				"countryCode",
				"creationTime",
				"dnsQueryType",
				"connectorGroupType",
				"geoLocationId",
				"latitude",
				"location",
				"longitude",
				"modifiedBy",
				"modifiedTime",
				"overrideVersionProfile",
				"praEnabled",
				"wafDisabled",
				"upgradeDay",
				"upgradeTimeInSecs",
				"versionProfileId",
				"versionProfileName",
				"versionProfileVisibilityScope",
				"tcpQuickAckApp",
				"tcpQuickAckAssistant",
				"useInDrMode",
				"tcpQuickAckReadAssistant",
				"lssAppConnectorGroup",
				"microtenantId",
				"microtenantName",
				"siteId",
				"siteName",
				"readOnly",
				"restrictionType",
				"zscalerManaged",
				"dcHostingInfo",
				"nameWithoutTrim",
				"serverGroups",
				"connectors",
				"npAssistantGroup",
				"enrollmentCertId",
			},
		},
		{
			name:         "zpaappservercontroller.ApplicationServer",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAAppServers,
			typ:          reflect.TypeOf(zpaappservercontroller.ApplicationServer{}),
			catalogFields: []string{
				"address",
				"appServerGroupIds",
				"configSpace",
				"creationTime",
				"description",
				"enabled",
				"id",
				"modifiedBy",
				"modifiedTime",
				"name",
				"microtenantId",
				"microtenantName",
			},
		},
		{
			name:         "zpamachinegroup.MachineGroup",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAMachineGroups,
			typ:          reflect.TypeOf(zpamachinegroup.MachineGroup{}),
			catalogFields: []string{
				"id",
				"name",
				"description",
				"enabled",
				"creationTime",
				"machines",
				"modifiedBy",
				"modifiedTime",
				"microtenantId",
				"microtenantName",
			},
		},
		{
			name:         "zpatrustednetwork.TrustedNetwork",
			resource:     resources.ProductZPA,
			resourceName: resourceZPATrustedNets,
			typ:          reflect.TypeOf(zpatrustednetwork.TrustedNetwork{}),
			catalogFields: []string{
				"creationTime",
				"domain",
				"id",
				"masterCustomerId",
				"modifiedBy",
				"modifiedTime",
				"name",
				"networkId",
				"zscalerCloud",
			},
		},
		{
			name:         "zpaserviceedgegroup.ServiceEdgeGroup",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAServiceGrps,
			typ:          reflect.TypeOf(zpaserviceedgegroup.ServiceEdgeGroup{}),
			catalogFields: []string{
				"altCloud",
				"city",
				"cityCountry",
				"countryCode",
				"creationTime",
				"description",
				"enabled",
				"enrollmentCertId",
				"exclusiveForBusinessContinuity",
				"geoLocationId",
				"graceDistanceEnabled",
				"graceDistanceValue",
				"graceDistanceValueUnit",
				"id",
				"isPublic",
				"latitude",
				"location",
				"longitude",
				"microtenantId",
				"microtenantName",
				"modifiedBy",
				"modifiedTime",
				"name",
				"nameWithoutTrim",
				"objectType",
				"overrideVersionProfile",
				"readOnly",
				"restrictedEntity",
				"restrictionType",
				"scopeName",
				"serviceEdges",
				"siteId",
				"siteName",
				"trustedNetworks",
				"upgradeDay",
				"upgradeTimeInSecs",
				"useInDrMode",
				"versionProfileId",
				"versionProfileName",
				"versionProfileVisibilityScope",
				"zscalerManaged",
			},
		},
		{
			name:         "zpaserviceedgecontroller.ServiceEdgeController",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAServiceEdges,
			typ:          reflect.TypeOf(zpaserviceedgecontroller.ServiceEdgeController{}),
			catalogFields: []string{
				"applicationStartTime",
				"controlChannelStatus",
				"creationTime",
				"ctrlBrokerName",
				"currentVersion",
				"description",
				"enabled",
				"enrollmentCert",
				"expectedUpgradeTime",
				"expectedVersion",
				"fingerprint",
				"id",
				"ipAcl",
				"issuedCertId",
				"lastBrokerConnectTime",
				"lastBrokerConnectTimeDuration",
				"lastBrokerDisconnectTime",
				"lastBrokerDisconnectTimeDuration",
				"lastUpgradeTime",
				"latitude",
				"listenIps",
				"location",
				"longitude",
				"microtenantId",
				"microtenantName",
				"modifiedBy",
				"modifiedTime",
				"name",
				"platform",
				"platformDetail",
				"previousVersion",
				"privateBrokerVersion",
				"privateIp",
				"provisioningKeyId",
				"provisioningKeyName",
				"publicIp",
				"publishIps",
				"publishIpv6",
				"runtimeOS",
				"sargeVersion",
				"serviceEdgeGroupId",
				"serviceEdgeGroupName",
				"upgradeAttempt",
				"upgradeStatus",
			},
		},
		{
			name:         "zpacloudconnectorgroup.CloudConnectorGroup",
			resource:     resources.ProductZPA,
			resourceName: resourceZPACloudConnGrps,
			typ:          reflect.TypeOf(zpacloudconnectorgroup.CloudConnectorGroup{}),
			catalogFields: []string{
				"cloudConnectors",
				"creationTime",
				"description",
				"enabled",
				"geoLocationId",
				"id",
				"modifiedBy",
				"modifiedTime",
				"name",
				"ziaCloud",
				"ziaOrgId",
				"znfGroupType",
			},
		},
		{
			name:         "zpacloudconnector.CloudConnector",
			resource:     resources.ProductZPA,
			resourceName: resourceZPACloudConns,
			typ:          reflect.TypeOf(zpacloudconnector.CloudConnector{}),
			catalogFields: []string{
				"creationTime",
				"description",
				"edgeConnectorGroupId",
				"edgeConnectorGroupName",
				"enabled",
				"enrollmentCert",
				"fingerprint",
				"id",
				"ipAcl",
				"issuedCertId",
				"modifiedBy",
				"modifiedTime",
				"name",
			},
		},
		{
			name:         "zpapostureprofile.PostureProfile",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAPostureProfs,
			typ:          reflect.TypeOf(zpapostureprofile.PostureProfile{}),
			catalogFields: []string{
				"applyToMachineTunnelEnabled",
				"creationTime",
				"crlCheckEnabled",
				"domain",
				"id",
				"masterCustomerId",
				"modifiedBy",
				"modifiedTime",
				"name",
				"nonExportablePrivateKeyEnabled",
				"platform",
				"postureType",
				"postureUdid",
				"rootCert",
				"zscalerCloud",
				"zscalerCustomerId",
			},
		},
		{
			name:         "zpacbizpaprofile.ZPAProfiles",
			resource:     resources.ProductZPA,
			resourceName: resourceZPACBIZPAProfs,
			typ:          reflect.TypeOf(zpacbizpaprofile.ZPAProfiles{}),
			catalogFields: []string{
				"cbiProfileId",
				"cbiTenantId",
				"cbiUrl",
				"creationTime",
				"description",
				"enabled",
				"id",
				"modifiedBy",
				"modifiedTime",
				"name",
			},
		},
		{
			name:         "zpac2cipranges.IPRanges",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAC2CIPRanges,
			typ:          reflect.TypeOf(zpac2cipranges.IPRanges{}),
			catalogFields: []string{
				"availableIps",
				"countryCode",
				"creationTime",
				"customerId",
				"description",
				"enabled",
				"id",
				"ipRangeBegin",
				"ipRangeEnd",
				"isDeleted",
				"latitudeInDb",
				"location",
				"locationHint",
				"longitudeInDb",
				"modifiedBy",
				"modifiedTime",
				"name",
				"sccmFlag",
				"subnetCidr",
				"totalIps",
				"usedIps",
			},
		},
		{
			name:         "zpaconfigoverride.ConfigOverrides",
			resource:     resources.ProductZPA,
			resourceName: resourceZPAConfigOvrds,
			typ:          reflect.TypeOf(zpaconfigoverride.ConfigOverrides{}),
			catalogFields: []string{
				"brokerName",
				"configKey",
				"configValue",
				"configValueInt",
				"customerId",
				"customerName",
				"description",
				"targetGid",
				"targetName",
				"targetType",
			},
		},
		{
			name: "zpacloudconnectorgroup.CloudConnectors",
			typ:  reflect.TypeOf(zpacloudconnectorgroup.CloudConnectors{}),
			ignoredFields: ignoredBecause(
				"covered by dropped cloudConnectors parent",
				"creationTime",
				"description",
				"enabled",
				"fingerprint",
				"id",
				"ipAcl",
				"issuedCertId",
				"microtenantId",
				"microtenantName",
				"modifiedBy",
				"modifiedTime",
				"name",
				"readOnly",
				"restrictionType",
				"signingCert",
				"zscalerManaged",
			),
		},
		{
			name: "workloadgroups.WorkloadTagExpression",
			typ:  reflect.TypeOf(workloadgroups.WorkloadTagExpression{}),
			ignoredFields: ignoredBecause(
				"covered by dropped expressionJson parent",
				"expressionContainers",
			),
		},
		{
			name: "workloadgroups.ExpressionContainer",
			typ:  reflect.TypeOf(workloadgroups.ExpressionContainer{}),
			ignoredFields: ignoredBecause(
				"covered by dropped expressionJson parent",
				"tagType",
				"operator",
				"tagContainer",
			),
		},
		{
			name: "workloadgroups.TagContainer",
			typ:  reflect.TypeOf(workloadgroups.TagContainer{}),
			ignoredFields: ignoredBecause(
				"covered by dropped expressionJson parent",
				"tags",
				"operator",
			),
		},
		{
			name: "workloadgroups.Tags",
			typ:  reflect.TypeOf(workloadgroups.Tags{}),
			ignoredFields: ignoredBecause(
				"covered by dropped expressionJson parent",
				"key",
				"value",
			),
		},
		{
			name: "ztwworkloadgroups.WorkloadTagExpression",
			typ:  reflect.TypeOf(ztwworkloadgroups.WorkloadTagExpression{}),
			ignoredFields: ignoredBecause(
				"covered by dropped expressionJson parent",
				"expressionContainers",
			),
		},
		{
			name: "ztwworkloadgroups.ExpressionContainer",
			typ:  reflect.TypeOf(ztwworkloadgroups.ExpressionContainer{}),
			ignoredFields: ignoredBecause(
				"covered by dropped expressionJson parent",
				"tagType",
				"operator",
				"tagContainer",
			),
		},
		{
			name: "ztwworkloadgroups.TagContainer",
			typ:  reflect.TypeOf(ztwworkloadgroups.TagContainer{}),
			ignoredFields: ignoredBecause(
				"covered by dropped expressionJson parent",
				"tags",
				"operator",
			),
		},
		{
			name: "ztwworkloadgroups.Tags",
			typ:  reflect.TypeOf(ztwworkloadgroups.Tags{}),
			ignoredFields: ignoredBecause(
				"covered by dropped expressionJson parent",
				"key",
				"value",
			),
		},
		{
			name: "ztwcommon.CommonIDNameExternalID",
			typ:  reflect.TypeOf(ztwcommon.CommonIDNameExternalID{}),
			ignoredFields: ignoredBecause(
				"used as id/name reference; additional metadata is dropped by nested catalog fields",
				"id",
				"name",
				"isNameL10nTag",
				"extensions",
				"deleted",
				"externalId",
				"associationTime",
			),
		},
		{
			name: "ztwcommon.CommonIDName",
			typ:  reflect.TypeOf(ztwcommon.CommonIDName{}),
			ignoredFields: ignoredBecause(
				"covered by modeled ztw id/name references",
				"id",
				"name",
			),
		},
		{
			name: "ztwcommon.RegionStatus",
			typ:  reflect.TypeOf(ztwcommon.RegionStatus{}),
			ignoredFields: ignoredBecause(
				"covered by ztw/public-cloud-info regionStatus nested field",
				"id",
				"name",
				"cloudType",
				"status",
			),
		},
		{
			name: "ztwcommon.SupportedRegions",
			typ:  reflect.TypeOf(ztwcommon.SupportedRegions{}),
			ignoredFields: ignoredBecause(
				"covered by ztw/public-cloud-info supportedRegions nested field",
				"id",
				"name",
				"cloudType",
			),
		},
		{
			name: "ztwcommon.ZPAApplicationSegments",
			typ:  reflect.TypeOf(ztwcommon.ZPAApplicationSegments{}),
			ignoredFields: ignoredBecause(
				"covered by ztw/forwarding-rules zpaApplicationSegments nested field",
				"id",
				"name",
				"description",
				"zpaId",
				"deleted",
			),
		},
		{
			name: "ztwcommon.ZPAApplicationSegmentGroups",
			typ:  reflect.TypeOf(ztwcommon.ZPAApplicationSegmentGroups{}),
			ignoredFields: ignoredBecause(
				"covered by ztw/forwarding-rules zpaApplicationSegmentGroups nested field",
				"id",
				"name",
				"zpaId",
				"deleted",
				"zpaAppSegmentsCount",
			),
		},
		{
			name: "ztwnetworkservices.NetworkPorts",
			typ:  reflect.TypeOf(ztwnetworkservices.NetworkPorts{}),
			ignoredFields: ignoredBecause(
				"covered by modeled network port range parent",
				"start",
				"end",
			),
		},
		{
			name: "ztwnetworkservicegroups.Services",
			typ:  reflect.TypeOf(ztwnetworkservicegroups.Services{}),
			ignoredFields: ignoredBecause(
				"network service groups render child services as id/name references only; ztw/network-services owns service details",
				"id",
				"name",
				"tag",
				"srcTcpPorts",
				"destTcpPorts",
				"srcUdpPorts",
				"destUdpPorts",
				"type",
				"description",
				"isNameL10nTag",
			),
		},
		{
			name: "ztwcommon.IDNameExtensions",
			typ:  reflect.TypeOf(ztwcommon.IDNameExtensions{}),
			ignoredFields: ignoredBecause(
				"covered by dropped lastModifiedBy parent",
				"id",
				"name",
				"extensions",
			),
		},
		{
			name: "ziacommon.IDNameExternalID",
			typ:  reflect.TypeOf(ziacommon.IDNameExternalID{}),
			ignoredFields: ignoredBecause(
				"currently used inside explicitly modeled nested references; this entry catches SDK additions",
				"id",
				"name",
				"externalId",
				"extensions",
			),
		},
	}
}
